### ISSUE TITLE
"httpcomponent.dll" cannot be run on the simplified Chinese version

### ISSUE THREAD

**Issue by zjswap** [ProfessorJTJ/HISuite-Proxy#1]
The patched "httpcomponent.dll" cannot be run on the simplified Chinese version of Windows 10, there is no problem with the English version of the system.

**Comment by ProfessorJTJ** [comment]
Can you kindly tell me what error does it give and send me your simplified Chinese httpcomponent.dll so I can reverse engine it manually and see what's up with it?

**Comment by flibblesan1984** [comment]
I'm having the same issue as well. Running Windows 10 Pro build 18363.

The app patches httpcomponent.dll producing an oversized file of 237kb, and this stops HiSuite opening with an error:

"HiSuite.exe - Bad Image

C:\Program Files (x86)\HiSuite\httpcomponent.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000130."

To see if it's a Windows 10 issue I install HiSuite into a Windows 7 virtual machine then patched the dll again which produced a 174kb file (same size as the original). Copying this onto my Windows 10 PC allowed me to open HiSuite and use the proxy app, and the update process worked fine.

I've attached the oversized dll in case it's useful for debugging this issue. 
[oversized-httpcomponent.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/4765706/oversized-httpcomponent.zip)

**Comment by ProfessorJTJ** [comment]
> I'm having a similar issue as well. Running Windows 10 Pro build 18363. This is an English (United Kingdom) installation.
> 
> The app patches httpcomponent.dll producing an oversized file of 237kb, and this stops HiSuite opening with an error:
> 
> "HiSuite.exe - Bad Image
> 
> C:\Program Files (x86)\HiSuite\httpcomponent.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000130."
> 
> To see if it's a Windows 10 issue I install HiSuite into a Windows 7 virtual machine then patched the dll again which produced a 174kb file (same size as the original). Copying this onto my Windows 10 PC allowed me to open HiSuite and use the proxy app, and the update process worked fine.
> 
> I've attached the oversized dll in case it's useful for debugging this issue.
> [oversized-httpcomponent.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/4765706/oversized-httpcomponent.zip)

I'm going to fix it soon but I need you to keep in touch to try it!

**Comment by flibblesan1984** [comment]
No problem!

**Comment by ProfessorJTJ** [comment]
> No problem!

Hopefully this gonna fix it

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/1.7.6/HiSutie.Proxy.zip

**Comment by flibblesan1984** [comment]
> > No problem!
> 
> Hopefully this gonna fix it
> 
> https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/1.7.6/HiSutie.Proxy.zip

This works for me, thank you.

**Comment by ProfessorJTJ** [comment]
> This works for me, thank you.
> 
> Edit: Just to be 100% sure, I compared the checksums of the file I patched under Windows 7 and the file I patched just now and they match. Thanks for the quick fix!

Actually the thank is yours for taking the time to test it, Thanks!

**Comment by pkobier** [comment]
I just checked and it is working for me also.

Thank you for fix!!
Can I buy you a beer somehow?

**Comment by ProfessorJTJ** [comment]
> I just checked and it is working for me also.
> 
> Thank you for fix!!
> Can I buy you a beer somehow?

No proble, glad that it worked!
Sure! 
[Buy me a beer!](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=fullclip39@gmail.com&item_name=HISuite+Proxy+Support&no_shipping=1&lc=US)
