### ISSUE TITLE
Can not use the Authentication Bridge

### ISSUE THREAD

**Issue by lhl881210** [ProfessorJTJ/HISuite-Proxy#10]
[10:45:29]: Connecting to Authentication Bridge
 [10:45:29]: Unexpected Response Received, Retrying...
 [10:45:29]: Connecting to Authentication Bridge
 [10:45:30]: Unexpected Response Received, Retrying...
 [10:45:30]: Connecting to Authentication Bridge
 [10:45:30]: Unexpected Response Received, Retrying...
 [10:45:30]: Connection to Authentication Bridge Failed, Process Aborted.

**Comment by ProfessorJTJ** [comment]
> [10:45:29]: Connecting to Authentication Bridge
> [10:45:29]: Unexpected Response Received, Retrying...
> [10:45:29]: Connecting to Authentication Bridge
> [10:45:30]: Unexpected Response Received, Retrying...
> [10:45:30]: Connecting to Authentication Bridge
> [10:45:30]: Unexpected Response Received, Retrying...
> [10:45:30]: Connection to Authentication Bridge Failed, Process Aborted.

Yeah, they banned the bridge. 

<img src="http://www.upsara.com/images/f914781_.jpg">

**Comment by google-mirror** [comment]
Nothing, just fuck Donald Trump

**Comment by lhl881210** [comment]
Thanks for your reply.
Do you have any other way to solve this problem?
Local bridge or some thing?
Or, do you know how to make a re-branded phone go back to the original brand?
Thanks

**Comment by ProfessorJTJ** [comment]
> Thanks for your reply.
> Do you have any other way to solve this problem?
> Local bridge or some thing?
> Or, do you know how to make a re-branded phone go back to the original brand?
> Thanks

I made the bridge remote to hide some sensitive data, other than that I can make it direct, local, and faster, however some sensitive data of the users will be at risk. Because it uses other people's phone information ( which I used without their permission too lol ) to authenticate for your phone.

**Comment by ProfessorJTJ** [comment]
Try this, hopefully gonna fix it

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/tag/1.8.7

**Comment by lhl881210** [comment]
> Try this, hopefully gonna fix it
> 
> https://github.com/ProfessorJTJ/HISuite-Proxy/releases/tag/1.8.7

Thanks for your help!
I have tried the 1.8.7 but there is a error that shows "Make sure that HiSuite_proxy.authenticate.resources is properly embedded or connected to assembly HiSuite proxy, or make sure that all required satellite assemblies are loaded and fully signed" 
（the error message is in Chinese）
![image](https://user-images.githubusercontent.com/15242269/94123670-0cfe6b00-fe8f-11ea-8a25-479ab83e2bfc.png)

**Comment by du365** [comment]
> > Try this, hopefully gonna fix it
> > https://github.com/ProfessorJTJ/HISuite-Proxy/releases/tag/1.8.7
> 
> Thanks for your help!
> I have tried the 1.8.7 but there is a error that shows "Make sure that HiSuite_proxy.authenticate.resources is properly embedded or connected to assembly HiSuite proxy, or make sure that all required satellite assemblies are loaded and fully signed"
> （the error message is in Chinese）
> ![image](https://user-images.githubusercontent.com/15242269/94123670-0cfe6b00-fe8f-11ea-8a25-479ab83e2bfc.png)

the same with this.
