### ISSUE TITLE
problem after downgrade

### ISSUE THREAD

**Issue by ciorax20** [ProfessorJTJ/HISuite-Proxy#100]
Hello profesore.
i have downgrade my p40 pro, with hiproxy
but instead of ELS-N29, i put ELS-N39
my phone working but, cannot conect to pc. only charging. cannot make ota updates.
![image3A215](https://user-images.githubusercontent.com/87233719/132948139-91fb04bb-c123-4464-a707-ba70ddee6c52.jpg)

**Comment by ciorax20** [comment]
[SystemUpdate_20210905_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7147860/SystemUpdate_20210905_00.log)
here is the log. i cannot connect anymore to pc. how can i go back?

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210905_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7147860/SystemUpdate_20210905_00.log)
> here is the log. i cannot connect anymore to pc. how can i go back?

When you downgrade USB and Fast Charge stop working, it's a new security system by Huawei. Upgrading to latest EMUI fixes the issue.

There's 2 things you can try,

1. Booting to eRecovery then updating from there. -> IT CAN BRICK YOUR PHONE IN CERTAIN CASES.... ( if it finds only base and preload packages for EMUI 11 and proceeds, you will have cust 10.1 with base 11, which in turn will give you a dead phone )

2. Booting into Fastboot and using HiSuite's rescue mode, I don't think it's possible to install a rom which doesn't match with your current one in the model ( ELS-N29 over ELS-N39 ) but you could give it a shot.

There's a low chance for both of the methods to work, however this dude can fix it for you using paid tools.
https://ministryofsolutions.com/

**Comment by ciorax20** [comment]
i can access tru the usb c stick, i can upgrade from there, with dload. but i dunnno wich files sould i put!

**Comment by ProfessorJTJ** [comment]
> i can access tru the usb c stick, i can upgrade from there, with dload. but i dunnno wich files sould i put!

The files which are on firmfinder.ml cannot be installed by dload...

But this is a dload package https://androidhost.ru/1O2J
HUAWEI P40 PRO ELS-NX9 ELS-N29 HW EU ELSA-N29D 10.1.0.176(C432E8R6P1) FIRMWARE EMUI10.1.0 05016PSR [ANDROIDHOST.RU].ZIP

**Comment by ciorax20** [comment]
i have try this load. But after restart, its says wrong files to install.

**Comment by ProfessorJTJ** [comment]
> i have try this load. But after restart, its says wrong files to install.

This is probably because your cust model is N39

**Comment by ciorax20** [comment]
so its dead end?

**Comment by ProfessorJTJ** [comment]
> so its dead end?

You could risk trying eRecovery update. or just spend couple of $$ to ministry of solutions. or if its under warranty I recommend you to take it to a Huawei service center..

**Comment by ciorax20** [comment]
you can guide me to eRecovery?

**Comment by ProfessorJTJ** [comment]
> you can guide me to eRecovery?

https://www.youtube.com/watch?v=qLOmm26zoMs

**Comment by ciorax20** [comment]
I have entered there, and give update, but i get "Get package info failed"

offffffff

**Comment by ciorax20** [comment]
i spoke with that guy that told me. the only thing at the moment is to find N39 dload 11 and upgrade tru usb otg!

but i cannot find. can u help me? please

**Comment by ProfessorJTJ** [comment]
> i spoke with that guy that told me. the only thing at the moment is to find N39 dload 11 and upgrade tru usb otg!
> 
> but i cannot find. can u help me? please

You want to install N39 rom over your N29 phone? installing the base of N39 might completely brick your phone as it's N29..

**Comment by ciorax20** [comment]
this was the info from ministry of solution!

**Comment by ProfessorJTJ** [comment]
> this was the info from ministry of solution!

Well then

ELS-N39 11.0.0.180(C432E3R5P4)
https://androidhost.ru/1OD5

**Comment by ciorax20** [comment]
![image](https://user-images.githubusercontent.com/87233719/132950813-92c578b3-cc89-4fed-b7cf-5fbf94ffe7b3.png)

**Comment by ProfessorJTJ** [comment]
Brother, It is better if take your phone to a Huawei service center, N39 over N29 can kill your phone.

**Comment by ciorax20** [comment]
i will try with n29 emui 11. maybe is working. im not risking to make with 39. i just said what he said to.me.

**Comment by ciorax20** [comment]
i have succed to upgrade to 11. with n29 dload, but cust and prel n39. because if i put 29 cust, invalid soft to install.

**Comment by ciorax20** [comment]
![241736729_554842675635214_3758453721921058885_n](https://user-images.githubusercontent.com/87233719/132993496-fc5b0f96-2c32-48ea-8665-5850c9784c8e.jpg)

**Comment by ciorax20** [comment]
and fastcharge and connect to pc not working

**Comment by ProfessorJTJ** [comment]
> and fastcharge and connect to pc not working

If you boot your phone to fastboot mode, does your pc recognize it?

**Comment by ciorax20** [comment]
no. i have reach there, to the screen with white
FASTBOOT &Rescu mode

Please connect usb cable to your pc and open Hisute.

I have open Hisuite.. but nothing.

**Comment by ProfessorJTJ** [comment]
> no. i have reach there, to the screen with white
> FASTBOOT &Rescu mode
> 
> Please connect usb cable to your pc and open Hisute.
> 
> I have open Hisuite.. but nothing.

Then try erecovery, see if it will find any update for you

**Comment by ciorax20** [comment]
I tryed to connect to wifi, succes, is writen Package: 11.0.0.180
and with this error message: Getting package info failed

**Comment by gzxief** [comment]
china english:Use WLAN of HISuite 11.0.0.510（Chinese version） or WLAN of HISuite 10.1.0.550（Chinese version） together with HISuite.Proxy2.3.7

**Comment by Loggsie** [comment]
> no. i have reach there, to the screen with white FASTBOOT &Rescu mode
> 
> Please connect usb cable to your pc and open Hisute.
> 
> I have open Hisuite.. but nothing.

Swap the USB-C cable you are using. Then you can try flashing correct version through HiSuite/HiSuite Proxy. I can confirm simply swapping the USB-C cable fixed this issue for me. 

See issue https://github.com/ProfessorJTJ/HISuite-Proxy/issues/127
