### ISSUE TITLE
Downgrade

### ISSUE THREAD

**Issue by hmsdy** [ProfessorJTJ/HISuite-Proxy#101]
**can i downgrade emui 11.0.0.198 to emui 10**

**Comment by hmsdy** [comment]
[19:49:53]: Patch failed, Aborting process....
 [19:49:54]: Please Contact Developer If Error Continues
i got this issue from my PC

**Comment by ProfessorJTJ** [comment]
> [19:49:53]: Patch failed, Aborting process....
> [19:49:54]: Please Contact Developer If Error Continues
> i got this issue from my PC

Use hisuite 10.1
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

To downgrade to emui 10.0 it's recommended that you first downgrade to emui 10.1 then to 10.0

ALERT ⚠: ONCE you downgrade from latest emui 11 you will lose fast charging and USB connection to pc. You will not be able to use hisuite proxy. You will need to upgrade to latest emui to fix it.

**Comment by brkhnbkr** [comment]
> 
> 
> > [19:49:53]: Patch failed, Aborting process....
> > [19:49:54]: Please Contact Developer If Error Continues
> > i got this issue from my PC
> 
> Use hisuite 10.1
> https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
> 
> To downgrade to emui 10.0 it's recommended that you first downgrade to emui 10.1 then to 10.0
> 
> ALERT ⚠: ONCE you downgrade from latest emui 11 you will lose fast charging and USB connection to pc. You will not be able to use hisuite proxy. You will need to upgrade to latest emui to fix it.

Hello ProfessorJTJ.  I'm facing the exact issue. I'm using P30 Pro and downgraded it from Emui 11 to 10.0. I immediately lost supercharging feature and phone cannot connect to my laptop via its regular charging cable.

However I was lucky since I managed to connect it with a usb-c to usb-c cable. It now connects and Hisuite pops up without a problem. As I understand from your message, I have to upgrade it to Emui 11 again if I want to gain those features back. Will it be okay if I use latest version of Hisuite to install Emui 11 back?

And how can I still downgrade to 10.0 without facing these issues again? Do I need to downgrade Emui 11 to 10.1 first and then 10.0?

**Comment by ProfessorJTJ** [comment]
> > > [19:49:53]: Patch failed, Aborting process....
> > > [19:49:54]: Please Contact Developer If Error Continues
> > > i got this issue from my PC
> > 
> > 
> > Use hisuite 10.1
> > https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
> > To downgrade to emui 10.0 it's recommended that you first downgrade to emui 10.1 then to 10.0
> > ALERT ⚠: ONCE you downgrade from latest emui 11 you will lose fast charging and USB connection to pc. You will not be able to use hisuite proxy. You will need to upgrade to latest emui to fix it.
> 
> Hello ProfessorJTJ. I'm facing the exact issue. I'm using P30 Pro and downgraded it from Emui 11 to 10.0. I immediately lost supercharging feature and phone cannot connect to my laptop via its regular charging cable.
> 
> However I was lucky since I managed to connect it with a usb-c to usb-c cable. It now connects and Hisuite pops up without a problem. As I understand from your message, I have to upgrade it to Emui 11 again if I want to gain those features back. Will it be okay if I use latest version of Hisuite to install Emui 11 back?
> 
> And how can I still downgrade to 10.0 without facing these issues again? Do I need to downgrade Emui 11 to 10.1 first and then 10.0?

You don't need latest hisuite, but it's fine if you use latest hisuite.

So far no one could do a downgrade without losing the usb connection, for some type c to type c did not work either...
