### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Soriasis** [ProfessorJTJ/HISuite-Proxy#102]
So I changed my proxy and the stuff is now blue, but when I click on Add ROM it says get Hi Suite Proxy. I tried copying the links and placing them and then I get "Group version not match" Help?

**Comment by ProfessorJTJ** [comment]
Click on "setup* and be sure it succeeds.
Tick the boxes of cust and preload in hisuite proxy.

**Comment by Megsxz** [comment]
GOOD EVENING SIR I ENCOUNTERED A PROBLEM DURING ADDING ROM IN FIRMFINDER WHEN I CLICKED ADD ROM IT SAYS "COULDN'T ADD THE ROM (GET HIPROXY)" WHICH IS ALREADY INSTALLED AND OPEN AND IT IS IN LATEST VERSION PLEASE HELP SIR THANK YOU

**Comment by ProfessorJTJ** [comment]
> GOOD EVENING SIR I ENCOUNTERED A PROBLEM DURING ADDING ROM IN FIRMFINDER WHEN I CLICKED ADD ROM IT SAYS "COULDN'T ADD THE ROM (GET HIPROXY)" WHICH IS ALREADY INSTALLED AND OPEN AND IT IS IN LATEST VERSION PLEASE HELP SIR THANK YOU

When you click "setup" in hisuite proxy does it show error?

If not, if you're using breve browser, try with Firefox or chrome

If hisuite proxy is showing error, open command prompt as admin and write
netstat -a -b

See which application is using port 7777, close that app

**Comment by Megsxz** [comment]
![image](https://user-images.githubusercontent.com/97403841/148695693-322cb533-2ce4-4e89-80df-ed77770928fd.png)

THAT'S WHAT IT SHOWS WHEN I CLICK SET UP

**Comment by Megsxz** [comment]
AND I'M USING CHROME

**Comment by Megsxz** [comment]
sir i changed the version of the hiproxy and it shows like this 
![image](https://user-images.githubusercontent.com/97403841/148696336-be0c05e3-75d8-49db-a695-06c9d0a476b4.png)

**Comment by Megsxz** [comment]
WHAT I AM SUPPOSED TO DO TO SOLVE IT

**Comment by ProfessorJTJ** [comment]
> WHAT I AM SUPPOSED TO DO TO SOLVE IT

View your firewall settings?

**Comment by Megsxz** [comment]
i already close it and turn off all anti virus and protection 
and i found out that the one using 7777 port is hisuit proxy server
any possible solution?

**Comment by ProfessorJTJ** [comment]
> i already close it and turn off all anti virus and protection and i found out that the one using 7777 port is hisuit proxy server any possible solution?

You have to go to firewall settings and allow hisuite proxy from there, can you do that?

**Comment by Megsxz** [comment]
thank you for replying sir you helped a lot really i hope you have a great day!

my problem now is no internet connection when im about to downgrade the version

**Comment by ProfessorJTJ** [comment]
> thank you for replying sir you helped a lot really i hope you have a great day!
> 
> my problem now is no internet connection when im about to downgrade the version

If you're using hisuite 11, open the hisuite with red icon, you can find it on desktop
