### ISSUE TITLE
usb disabled

### ISSUE THREAD

**Issue by 2867631077** [ProfessorJTJ/HISuite-Proxy#106]
usb was disabled after rollback,only charge mode was working,the phone can not connect with my computer.

**Comment by ProfessorJTJ** [comment]
Update to latest version and it gets fixed.

**Comment by 2867631077** [comment]
![image](https://user-images.githubusercontent.com/5899936/134315247-7c68832d-f6d1-4430-a998-3ef7403b0a19.png)

why does this happen?

**Comment by ProfessorJTJ** [comment]
Translate it, I am not Chinese....

**Comment by 2867631077** [comment]
unable to connect to the network,please check your network settings.

**Comment by ProfessorJTJ** [comment]
> unable to connect to the network,please check your network settings.

If you're using hisuite 11 open the hisuite with red icon, it's on desktop

**Comment by 2867631077** [comment]
sorry, the problem was also occurred is the lasted version, use debugging was also disabled, could not connect with my computer and my phone

**Comment by ProfessorJTJ** [comment]
> sorry, the problem was also occurred in the lasted version, use debugging was also disabled, could not connect with my computer and my phone

Open Huawei's Support app and choose "Update" there, see if it will find any update of not boot to erecovery and see if it will find any update from there

**Comment by 2867631077** [comment]
> > sorry, the problem was also occurred in the lasted version, use debugging was also disabled, could not connect with my computer and my phone
> 
> Open Huawei's Support app and choose "Update" there, see if it will find any update of not boot to erecovery and see if it will find any update from there 

can not find any update there.
I think downgrade is disabled by huawei,I can only choose harmony os 2.0.0.165 or emui 11.0.0.155 to use.

**Comment by gzxief** [comment]
china english:Use WLAN of HISuite 11.0.0.510（Chinese version） or WLAN of HISuite 10.1.0.550（Chinese version） together with HISuite.Proxy2.3.7 to update Emui11 or HarmonyOS

**Comment by 2867631077** [comment]
> china english:Use WLAN of HISuite 11.0.0.510（Chinese version） or WLAN of HISuite 10.1.0.550（Chinese version） together with HISuite.Proxy2.3.7 to update Emui11 or HarmonyOS

I know this solution, but my purpose is that I want to downgrade from HarmonyOS to EMUI 9.1 and usb debugging is working.
Usb debugging was disabled since I downgraded to 10.0.185 with Hisuite Proxy one week ago.

**Comment by trustport** [comment]
> 
> 
> > china english:Use WLAN of HISuite 11.0.0.510（Chinese version） or WLAN of HISuite 10.1.0.550（Chinese version） together with HISuite.Proxy2.3.7 to update Emui11 or HarmonyOS
> 
> I know this solution, but my purpose is that I want to downgrade from HarmonyOS to EMUI 9.1 and usb debugging is working.
> Usb debugging was disabled since I downgraded to 10.0.185 with Hisuite Proxy one week ago.

没办法的，华为的安全机制。之前作者回答过这个问题，说是华为限制的。

**Comment by gzxief** [comment]
> > > 中文英语：使用HISuite 11.0.0.510（中文版）或HISuite 10.1.0.550（中文版）的WLAN与HISuite.代理2.3.7一起更新Eoui11或和谐
> > 
> > 
> > 我知道这个解决方案， 但我的目的是， 我想从 Harmonyos 降级到 Emui 9.1， usb 调试正在工作。自从一周前我通过 Hisuite 代理降级到 10.0.185 以来， Usb 调试被禁用了。
> 
> 没办法的，华为的安全机制。之前作者回答过这个问题，说是华为限制的。

QQ群里华为内部工程师（未验证）说，提取有USB的固件中HwTrustCircle.apk和iConnect.apk和inputDevices.apk，替换到你要降级的固件里，然后自己建立服务器，修改验证固件的XML文件中md5和sha256，通过HISuite-Prox降级后有USB

Huawei's internal Engineer (unverified) said that HwTrustCircle.apk, iConnect.apk and inputDevices.apk in the firmware with USB are extracted and integrated into the firmware you want to downgrade, and then build your own server and modify MD5 and sha256 in the XML file verifying the firmware

**Comment by gzxief** [comment]
> > > 中文英语：使用HISuite 11.0.0.510（中文版）或HISuite 10.1.0.550（中文版）的WLAN与HISuite.代理2.3.7一起更新Eoui11或和谐
> > 
> > 
> > 我知道这个解决方案， 但我的目的是， 我想从 Harmonyos 降级到 Emui 9.1， usb 调试正在工作。自从一周前我通过 Hisuite 代理降级到 10.0.185 以来， Usb 调试被禁用了。
> 
> 没办法的，华为的安全机制。之前作者回答过这个问题，说是华为限制的。

QQ群里华为内部工程师（未验证）说，提取有USB的固件中HwTrustCircle.apk和iConnect.apk和inputDevices.apk，替换到你要降级的固件里，然后自己建立服务器，修改验证固件的XML文件中md5和sha256，通过HISuite-Prox降级后有USB

Huawei's internal Engineer (unverified) said that HwTrustCircle.apk, iConnect.apk and inputDevices.apk in the firmware with USB are extracted and integrated into the firmware you want to downgrade, and then build your own server and modify MD5 and sha256 in the XML file verifying the firmware

**Comment by 2867631077** [comment]
> > > > 中文英语：使用HISuite 11.0.0.510（中文版）或HISuite 10.1.0.550（中文版）的WLAN与HISuite.代理2.3.7一起更新Eoui11或和谐
> > > 
> > > 
> > > 我知道这个解决方案， 但我的目的是， 我想从 Harmonyos 降级到 Emui 9.1， usb 调试正在工作。自从一周前我通过 Hisuite 代理降级到 10.0.185 以来， Usb 调试被禁用了。
> > 
> > 没办法的，华为的安全机制。之前作者回答过这个问题，说是华为限制的。
> 
> QQ群里华为内部工程师（未验证）说，提取有USB的固件中HwTrustCircle.apk和iConnect.apk和inputDevices.apk，替换到你要降级的固件里，然后自己建立服务器，修改验证固件的XML文件中md5和sha256，通过HISuite-Prox降级后有USB
> 
> Huawei's internal Engineer (unverified) said that HwTrustCircle.apk, iConnect.apk and inputDevices.apk in the firmware with USB are extracted and integrated into the firmware you want to downgrade, and then build your own server and modify MD5 and sha256 in the XML file verifying the firmware

How complex it is,but thank you for sharing very much.

**Comment by Loggsie** [comment]
> > china english:Use WLAN of HISuite 11.0.0.510（Chinese version） or WLAN of HISuite 10.1.0.550（Chinese version） together with HISuite.Proxy2.3.7 to update Emui11 or HarmonyOS
> 
> I know this solution, but my purpose is that I want to downgrade from HarmonyOS to EMUI 9.1 and usb debugging is working. Usb debugging was disabled since I downgraded to 10.0.185 with Hisuite Proxy one week ago.

Get yourself back to 10.0.185. Swap your USB-C cable and USB functions should return. From there you can roll back to EMUI 9.0/9.1 without needing HiSuite Proxy. 

See recent issue https://github.com/ProfessorJTJ/HISuite-Proxy/issues/127
