### ISSUE TITLE
Harmony Os Last updated

### ISSUE THREAD

**Issue by ybn3** [ProfessorJTJ/HISuite-Proxy#107]
First, thank you for this work ..

The latest update on the site. for device HUAWEI NOVA 4E
MAR-AL00 - C00

Version number 102.0.0.X

After downloading and updating, the boot did not work
Because the correct number must be
Version number 2.0.0.X
Because version Harmony  2.x.x.x . and not 102.x.x.x

**Comment by ProfessorJTJ** [comment]
Hey, did you add cust and preload packages or only base?
I assume you added only base, in such case you need to boot into fastboot and try system recovery with base, cust and preload of 102

And harmony os programmatically is being named as 102 but shows 2.0 for the user

**Comment by ybn3** [comment]
I added the three parts of the rum. As I did previously.
When the installation and use fails
The number 102.x.x.x appears.

I'll take pictures and try to send them

**Comment by ProfessorJTJ** [comment]
Send the installation log file

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by ybn3** [comment]
Really sorry I installed a new version of
HISuite
I have erased the old ..SystemUpdate_20211003_00

Thanks for the help, it took up a lot of your time.
.
