### ISSUE TITLE
please ayuda LYA-LGRP2-OVS 10.1.0.321 

### ISSUE THREAD

**Issue by cano49ers** [ProfessorJTJ/HISuite-Proxy#11]
gbc group version no match appears in hisuite proxy and http://update.dbankcdn.com/TDS/data/files/p3/s15/G5816/g1755/v463132/f1/full/ and when I enter hisuite that message appears What I can do ???

**Comment by ProfessorJTJ** [comment]
Cust version has to match your Base ex both should be 10 or 10.1 or 11
Also same to preload.
So you need three packages, base, cust and preload.
