### ISSUE TITLE
EVR-L29 upgrade to emui11 fails and fastboot no longer provides USB connection 

### ISSUE THREAD

**Issue by jeffedstrom** [ProfessorJTJ/HISuite-Proxy#110]
I have a mate20x that was on emui9, I tried going to 11 using hisuiteproxy and it failed. Not a huge deal but I can't get fastboot to connect over USB anymore. I bought a sub to funkyhauwei out fo desperation(as teh erecovery still connects to WIFI) and it seems they are not longer a thing but they still take payments =(. 

If I try to Erecover it installs 11.0.0.142 but still won't boot. 

Any idea how I can get myself out of this pickle? Can I make a wifi hotspot and point my etc/host to 127 and get hisuiteproxy to take over erecovery? Any advice would be HUGELY appreciated.

**Comment by jeffedstrom** [comment]
I think that would work but what's hanging me up is when I do the dload method, I can't find a version it will accept. If I place a 9-10 emui version it states that they are incompatible. I assume I need come version of 11 to proceed but can'd find a dload with the three zips anywhere including where you just shared.

**Comment by ProfessorJTJ** [comment]
Dunno your exact region and model but I assume

http://huawei-firmware.com/rom/huawei-mate-20-x-(5g)/evr-n29/49807

**Comment by jeffedstrom** [comment]
I have the Dl'd now but how does one dload those files. I've found that I need update_sd_base.zip, update_sd_cust_EVR-L29_hw_eu.zip, update_sd_preload_EVR-L29_hw_eu_R1.zip for the dload to see it as a plausible update file. Is there anyway to convert update.app to that layout?

**Comment by jeffedstrom** [comment]
This is kinda my catch 22. I have a few older dload firmwares but recovery says they are incompatible. I can't find an 11 version that is a proper dload file.

**Comment by ProfessorJTJ** [comment]
> Is there any way to get the files hisuite proxy downloads directly? Maybe I could use those to dload recover?

Unfortunately those files are online firmwares like the one you downloaded before, they cannot be installed through dload

**Comment by jeffedstrom** [comment]
I did the 2 month 40$ subscription. I was going to go to paypal for a refund today. Total silence on all fronts from funky.

**Comment by ProfessorJTJ** [comment]
> I did the 2 month 40$ subscription. I was going to go to paypal for a refund today. Total silence on all fronts from funky.

Take a refund, find dload for your phone on halabtech, get an sd card ( your phone supports sd cards right? )
Install the dload through sd card
