### ISSUE TITLE
Can´t update

### ISSUE THREAD

**Issue by Sp33d23** [ProfessorJTJ/HISuite-Proxy#111]
![Unbenannt](https://user-images.githubusercontent.com/92217172/136660192-4ed618d6-61bc-47e3-adbc-b5c5857a184a.jpg)

Can you help me?

**Comment by ProfessorJTJ** [comment]
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Sp33d23** [comment]
![Unbenannt](https://user-images.githubusercontent.com/92217172/136661209-54db14ba-da83-4ec6-aed5-54b1da8302ff.jpg)

Ok thank u. thats the new window.

I can´t downgrade to version LYA-LGRP2-OVS 10.1.0.341   they told me on Hi Suite the version is up to date :(

**Comment by ProfessorJTJ** [comment]
The configurations are wrong, take a screenshot from hisuite proxy
