### ISSUE TITLE
cant connect the phone even i enable debug

### ISSUE THREAD

**Issue by jfsd25** [ProfessorJTJ/HISuite-Proxy#113]
![cant connect the phone even i enable debug](https://user-images.githubusercontent.com/54447428/137344742-93b3db80-5321-4fbb-9cfc-6c3f7a74901f.PNG)

**Comment by ProfessorJTJ** [comment]
Did you downgrade from latest emui 11?
If so, your only option to fix the USB is upgrading to emui 11 ( using phone's ota or erecovery )

**Comment by jfsd25** [comment]
> Did you downgrade from latest emui 11? If so, your only option to fix the USB is upgrading to emui 11 ( using phone's ota or erecovery )

no its emui 10 i have nova 7i

**Comment by jfsd25** [comment]
after patching new hisuite in to red one i can't get the code or whatt its just can't get anything its just cant connect the red one with my phone but the blue one is good

**Comment by ProfessorJTJ** [comment]
> after patching new hisuite in to red one i can't get the code or whatt its just can't get anything its just cant connect the red one with my phone but the blue one is good

After you enable USB Debugging, enable USB Debugging in charging mode, or when you connect your phone choose file transfer, that way your phone will be connected in USB Debugging mode to the pc.
