### ISSUE TITLE
P40 Lite (JNY-LX1)

### ISSUE THREAD

**Issue by PaKo0o92** [ProfessorJTJ/HISuite-Proxy#114]
Hello,

I am trying to downgrade the firmware on my P40 Lite from 10.1.0.353 to 10.0.1.136. I am following the guide, but the process crashes after around 10% into the installation process.

These are the settings I am using on Proxy. I tried with both Force Auth Bridge on and off with no success. I also tried using the HiSuite 10 and 11 versions, using the APKs provided by you in the other topics. The same error occurs.
![image](https://user-images.githubusercontent.com/92579496/137475375-606b2058-97e1-4c8d-865a-ff6f80881b64.png)

The error just says "Failed to update", nothing else.

Any idea what's going on?

**Comment by PaKo0o92** [comment]
Fixed now, you can ignore the above.

**Comment by Fnrs-Wlan** [comment]
What do you mean with that?
