### ISSUE TITLE
HiSuite_11.0.0.510_OVE non vede la rete

### ISSUE THREAD

**Issue by pierio232** [ProfessorJTJ/HISuite-Proxy#115]
Salve, non riesco a portare a termine il downgrade. Dopo aver caricato base, cast e preload ed aver lanciato il setup, al momento di trasferire la rom nel p40 pro, l'HIsuite, che vede il telefono collegato via usb, si blocca e mi dice che manca il collegamento a internet che è perfettamente funzionante. cosa posso fare?

**Comment by ProfessorJTJ** [comment]
Be sure you're on HiSuite 11.0 or 10.1, and then tick the box "Force Auth Bridge"

**Comment by pierio232** [comment]
Come da titolo sono dulla 11.0.0.510_OVE,  dove trovo la "Force Auth Bridge" da selezionare?
Perdona l'ignoranza 
Ti ringrazio

**Comment by pierio232** [comment]
trovata, scusa mi era sfuggita
