### ISSUE TITLE
hisuite update 

### ISSUE THREAD

**Issue by moadov10** [ProfessorJTJ/HISuite-Proxy#116]
hisuite want me to update it

**Comment by ProfessorJTJ** [comment]
Don't update it?

**Comment by moadov10** [comment]
i would not let me use it withou updating

**Comment by moadov10** [comment]
![Uploading IMG_20211017_115637.jpg…]()

**Comment by ProfessorJTJ** [comment]
The image is not uploaded properly, please try again.

**Comment by moadov10** [comment]
![IMG_20211017_115637](https://user-images.githubusercontent.com/92666031/137618176-676797bf-6a56-4411-b91e-e050bdc84f5e.jpg)

**Comment by moadov10** [comment]
the same messge poped up

**Comment by moadov10** [comment]
message**
