### ISSUE TITLE
problems downgrading my matepad pro (wifi only)

### ISSUE THREAD

**Issue by mendel185** [ProfessorJTJ/HISuite-Proxy#118]
Hello, I'm having problems downgrading my matepad pro from emui version 11.0.0.217 to any emui 10 version. I'm stuck when on www.firmfinder.ml they ask me the region. The only problem is that not having the diler on my matepad pro I can't access the ProjectMenu. Is there any other way to get the downgrade done?
Thanks in advanced!

**Comment by ProfessorJTJ** [comment]
Connect your phone to pc, open HiSuite and click update
A log file will be generated at
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

It will have your phone details including region.

Alai consider:
"Be careful if you are downgrading, you will lose usb connection and fast charging

The only way to fix it is by updating back to latest emui 11

You cannot upgrade using hisuite, only by phone's ota, erecovery or dload through memory card

If Huawei did not show you ota update your only chance of fixing your phone will be dload through memory card"
