### ISSUE TITLE
[Offline Packages] Directory

### ISSUE THREAD

**Issue by solari21** [ProfessorJTJ/HISuite-Proxy#120]
Hi,

I've a doubt. If we want install the new firmware using the Offline Packages in which folder we have to put the base, cust and preload PKG files?

Thanks in advance. 

BR

**Comment by badmania98** [comment]
Hi,
I have tried this variant. Without internet connections it doesn't work.  It is not supposed to work without internet connection?

**Comment by ProfessorJTJ** [comment]
> Hi, I have tried this variant. Without internet connections it doesn't work. It is not supposed to work without internet connection?

Yes Internet connection is required for authentication from Huawei

**Comment by badmania98** [comment]
> > Hi, I have tried this variant. Without internet connections it doesn't work. It is not supposed to work without internet connection?
> 
> Yes Internet connection is required for authentication from Huawei

In case the firmware.ml site is down, can I use this method without problems, having the files on my computer?

**Comment by ProfessorJTJ** [comment]
> > > Hi, I have tried this variant. Without internet connections it doesn't work. It is not supposed to work without internet connection?
> > 
> > 
> > Yes Internet connection is required for authentication from Huawei
> 
> In case the firmware.ml site is down, can I use this method without problems, having the files on my computer?

Yes but you should also have the roms ids and use the old link format which includes the id in the url of the rom

**Comment by badmania98** [comment]
This is great. I got the point regarding old link format. Thank you.
