### ISSUE TITLE
HUAWEI P10 plus EMUI5.1upgrade

### ISSUE THREAD

**Issue by xinyuexiaogui** [ProfessorJTJ/HISuite-Proxy#122]
Upgrade from emui5.1 to emui8,Do you only need cust and preload packages?

**Comment by mleone11** [comment]
I just successfully upgraded from EMUI 5.1/Android 7.0 to EMUI 8.0/Android 8.0!

I chose the newest 8.0.0.# version for my model
![image](https://user-images.githubusercontent.com/34455989/140418094-662a4748-a3d4-4681-a873-3191031b0e52.png)

and followed the directions in the complete guide with no issue
![image](https://user-images.githubusercontent.com/34455989/140418274-87c0e582-b201-476f-88c1-4f4f66433c1c.png)

just like @ProfessorJTJ said, for EMUI 8 you only need the base package, so @xinyuexiaogui I think your mistake was checking the "CUST PKG" and "Preloaded PKG" options but not supplying those packages at the top!

**Comment by mleone11** [comment]
@ProfessorJTJ to then upgrade from 8 to 9, do you know if only Base and CUST packages are needed?

![image](https://user-images.githubusercontent.com/34455989/140428127-e9695bf5-baf7-4739-b691-f78e2207a74f.png)

And do the version numbers need to be the same? If I were to choose the newest OVS and CUST they would be 9.1.0.297 nand 9.1.0.5 respectively....

And should I use the one with the highest RomID when there are duplicates versions?

**Comment by ProfessorJTJ** [comment]
> @ProfessorJTJ to then upgrade from 8 to 9, do you know if only Base and CUST packages are needed?
> 
> ![image](https://user-images.githubusercontent.com/34455989/140428127-e9695bf5-baf7-4739-b691-f78e2207a74f.png)
> 
> And do the version numbers need to be the same? If I were to choose the newest OVS and CUST they would be 9.1.0.297 and 9.1.0.5 respectively....And should I use the one with the highest RomID when there are duplicates versions?
> 
> This is what I think I should attempt:
> 
> VTR-LGRP2-OVS 9.1.0.297 - 563786 VTR-L29-CUST 9.1.0.5(C432) - 563738
> 
> do I check "Old Firmware" or not?

Hey, as you're on emui 8 you still cannot install any firmware that has cust and preload, there are some emui 9.0 packages which work by the same method as emui 8, these firmwares don't have LGRP, CUST or Preload tags in their names:


Here's one:
VTR-L29 9.0.1.190(C432E1R1P9) : https://www.firmfinder.ml/295169

Just add it as base and tick the box "Old firmware"

**Comment by mleone11** [comment]
@ProfessorJTJ thank you for the guidance! funny enough my phone got an OTA update for 9... must be now that I'm officially out of the dark ages, the OTA updates can finally work

big thank you for making this tool and sharing knowledge about firmfinder - not possible without your efforts. cheers

**Comment by xinyuexiaogui** [comment]
> 我刚刚成功从EMUI 5.1/Android 7.0升级到EMUI 8.0/Android 8.0！
> 
> 我为我的模型选择了最新的 8.0.0.# 版本 ![图片](https://user-images.githubusercontent.com/34455989/140418094-662a4748-a3d4-4681-a873-3191031b0e52.png)
> 
> 并按照完整指南中的说明操作，没有任何问题 ![图片](https://user-images.githubusercontent.com/34455989/140418274-87c0e582-b201-476f-88c1-4f4f66433c1c.png)
> 
> 就像@ProfessorJTJ说的，对于 EMUI 8，你只需要基础包，所以@xinyuexiaogui我认为你的错误是检查了“CUST PKG”和“Preloaded PKG”选项，但没有在顶部提供这些包！

Let me try

**Comment by xinyuexiaogui** [comment]
> 我刚刚成功从EMUI 5.1/Android 7.0升级到EMUI 8.0/Android 8.0！
> 
> 我为我的模型选择了最新的 8.0.0.# 版本 ![图片](https://user-images.githubusercontent.com/34455989/140418094-662a4748-a3d4-4681-a873-3191031b0e52.png)
> 
> 并按照完整指南中的说明操作，没有任何问题 ![图片](https://user-images.githubusercontent.com/34455989/140418274-87c0e582-b201-476f-88c1-4f4f66433c1c.png)
> 
> 就像@ProfessorJTJ说的，对于EMUI 8，你只需要基础包，所以@xinyuexiaogui我认为你的错误是检查了“CUST PKG”和“Preloaded PKG”选项，但没有在顶部提供这些包！

![image](https://user-images.githubusercontent.com/93392291/140499223-a98a50b7-7651-407e-a61d-506ec9c614fd.png)
Whai is the reason for this

**Comment by mleone11** [comment]
your phone model is VKY-AL00 and mine is VTR-L29 so you can't use the same package as I did, it will not be compatible

**Comment by xinyuexiaogui** [comment]
> 你的手机型号是 VKY-AL00 而我的是 VTR-L29 所以你不能使用和我一样的包装，它不会兼容

我用的这个
![捕获12](https://user-images.githubusercontent.com/93392291/140596699-93cb5236-b37b-4724-8347-2729004acb02.PNG)
