### ISSUE TITLE
Still getting the message "You're now using the latest official version" how do i get update instead

### ISSUE THREAD

**Issue by Cooker9** [ProfessorJTJ/HISuite-Proxy#124]
I am using firmware finder for pc using DRA-LX2 1.0.0.175(C185) firmware which is approved

But i have done everything and it checks finished
Yet i still get that i already have the latest version

Question what im supposed to do now?

Im trying to reflash my firmware with official version because i have used sp flash to flash my device with official firmware i found on google, but it turned out that its missing lots of firmware apps

I wanted to fix failed verification error on startup after trying to unlock bootloader (but it still not fixed) :(

But phone still works fine it goes past the error but everytime i restart i still get it

Also i am using hisuite 11.exe

**Comment by ProfessorJTJ** [comment]
Hi, please careful read and watch the guides.

https://www.youtube.com/watch?v=CdYpZlXlgOQ

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by Cooker9** [comment]
Thanks for answering :)
But thing is there is no dra-lx2 in firmfinder.ml
What am supposed to do??

Thanks again

**Comment by ProfessorJTJ** [comment]
> Thanks for answering :) But thing is there is no dra-lx2 in firmfinder.ml What am supposed to do??
> 
> Thanks again

Read step 3 of the guide

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by Cooker9** [comment]
In my phone there is no version info option
I am using emiui 8.0 phone android 8.1 oreo

**Comment by ProfessorJTJ** [comment]
In this case, read the log file at:
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

It will have the details of your phone

**Comment by Cooker9** [comment]
Can i use firmware finder database instead?
Also i turned off my laptop so i will try again tomorrow

**Comment by Cooker9** [comment]
I realized that i did everything right, maybe it has something to do with hisuite not recognizing firmware update

**Comment by ProfessorJTJ** [comment]
> Can i use firmware finder database instead? Also i turned off my laptop so i will try again tomorrow

Huawei switched its servers, all the links on firmware finder don't work anymore, that's why we created firm finder.

https://www.firmfinder.ml

**Comment by Cooker9** [comment]
Where can i find the links for y5 prime 2018 dra-lx2 1.0.0.175 (C185)
Its not on the website?

**Comment by ProfessorJTJ** [comment]
> Where can i find the links for y5 prime 2018 dra-lx2 1.0.0.175 (C185) Its not on the website?

Send the log file when you turn your laptop on
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by Cooker9** [comment]
[SystemUpdate_20211025_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7449608/SystemUpdate_20211025_00.log)

**Comment by ProfessorJTJ** [comment]
DeviceName:DURA-L22
C_Version:C185
FirmWare:DRA-LX2 1.0.0.175(C185)

I'll try to look further into it tomorrow as it's 11pm here, if I find a firmware for this model, I'll notify you.

**Comment by Cooker9** [comment]
Okay thank you very much :)

**Comment by ProfessorJTJ** [comment]
Add this link for base version:

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/08/v3/23cac5ddd91b43298149be7205d80e34/full/filelist.xml

This is the rom name:
DRA-LX2 1.0.0.175(C185)

This is the rom ID:
390421

Tick the box "Old firmware" and happy flashing, sorry for the delay, I had ( and still have ) health issues.

**Comment by Cooker9** [comment]
I actually flashed my phone again but using "format and download" option on sp flash and that got rid of the failed verification error
But i will use this to update my phone whenever needed tysm

& Also hope you get well bro :)
