### ISSUE TITLE
How to downgrade a Honor 8

### ISSUE THREAD

**Issue by Nuc1eoN** [ProfessorJTJ/HISuite-Proxy#126]
Hi, sorry for asking a question here but I could not find the answer anywhere using a search engine or the documentation.

I would like to downgrade an Honor 8 phone, currently on EMUI 8 to an older firmware. Do you think it would work?

![01](https://user-images.githubusercontent.com/2538022/140020951-20cee7c8-be5c-45c9-9a7e-e3fea736ee1f.jpg)
![02](https://user-images.githubusercontent.com/2538022/140020954-b7d21941-00d7-41ae-867d-3435f83a2502.jpg)

As you see there are no entries like Base, Cust or PRELOAD as descibed in the wiki https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

But I figured this might be a fitting version https://www.firmfinder.ml/63548 (first rom ever released I think)
But I dunno about Cust and Preload, do I also need such files??

Also what should I select at `OS Type`? `Normal OS` or `Roll-Back OS`?? And what about the checkbox `Old Firmware`?
Unfortunately it isn't documented,

Thanks in advance!

**Comment by ProfessorJTJ** [comment]
Hey, for emui 8 and below you only need base package.
If you're downgrading choose OS type as Rollback

For emui 8 and earlier versions which don't have cust and preload you should tick the box "Old firmware"

**Comment by Nuc1eoN** [comment]
I had read some older sources that mentioned that a "Rollback update" is needed, and then a "base" firmware, e.g. [here ](https://www.androidsage.com/2016/12/05/download-honor-8-nougat-and-marshmallow-emui-5-0-4-1-stock-firmware-update/#how-to-install-nougat-beta-firmware-on-honor-8).
On [this site](https://rootmygalaxy.net/downgrade-honor-8-from-nougat-to-marshmallow/) they also mention a rollback package. However I cannot find any of these rollback packages anymore.
Are they needed as the articles say? or do I only need the base image as you have mentioned?

Some guides also mentioned a two step flash process, for example [here ](https://www-android--hilfe-de.translate.goog/forum/original-firmwares-fuer-honor-8.2838/honor-8-emui-5-android-7-0-frd-l09c432b380-anleitung-download.821278.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=nui,sc)
> (the update consists of 2 files (update.zip and update_data_full_hw_eu.zip)), the build no. will only be updated after the 2 file on B380.)

where there is a first and second UPDATE.APP. (although this is about upgrading, not downgrading)

But I wonder why they would need two steps?

Is anything of the above something to worry about? Otherwise I would proceed and trying to install the old rom on my phone :)

**Comment by ProfessorJTJ** [comment]
Usually any FullOTA firmware works for downgrade, however it shouldn't be too older than your firmware
For example if your version is B300 installing B280-B270 should be fine but B200 or B190 it might be dangerous

**Comment by Nuc1eoN** [comment]
According to my phone settings I am currently on [FRD-L09 8.0.0.521(C432)
](https://www.firmfinder.ml/159456)So maybe [FRD-L09C432B131](https://www.firmfinder.ml/63548) would be a too hard downgrade.

I have looked throught the firmware images and maybe FRD-L09C432B407 is my best bet?
The rom ID `151658` is just under `159456` of the previous rom.
There is also Android 7 [FRD-L09C432B418](https://www.firmfinder.ml/365414) but the Rom ID `365414` is a lot higher than my current one.

**Comment by Nuc1eoN** [comment]
Damn... So first of all B407 was probably the best choice I could make, because I found older posts where users still had the option to Downgrade from 8.0.0.521 -> B407, this was their screenshot:
![Nougatauswahl](https://user-images.githubusercontent.com/2538022/140165434-2689b47e-8dcb-41ca-bcbf-94d619ca898a.jpg)

Now I have tried the same with HiSuite Proxy and it it very similar:
![nougatenproxy](https://user-images.githubusercontent.com/2538022/140165777-b6d9b1e2-3bca-490d-b2c3-60453c2eb1ef.PNG)

But interestingly as you can see, the description is different. Maybe this means Huawei had an extra Rollback ROM?

Becasue I have tried to update it, but unfortunately after the phone restarts and tries to install the ROM the installation fails :(

**Comment by Nuc1eoN** [comment]
Thank you. Here it is
![hiproxy](https://user-images.githubusercontent.com/2538022/140193091-2b1cb986-08ef-476a-965d-fc1f8bfa32df.PNG)

**Comment by ProfessorJTJ** [comment]
Hey, I am sorry for the delay, I just had a lot going on and health issues.
anyway, yeah unfortunately Huawei has got rid of rom 151658, meaning now you cannot install it even if you have the files ( being it doesn't authenticate it for installation )
However rom FRD-L09C432B418 id 365414 is still approved for installation, the rom id doesn't really matter just the version does matter

**Comment by Nuc1eoN** [comment]
Nevermind, thank you for the support and I hope you are doing well!

Ok so I think I am gonna try `FRD-L09C432B418` then.. is this the only rom currently approved for my phone? How do they block older roms from being installed??

But before I try `FRD-L09C432B418` are you sure to install it with "Roll-back OS`? Because it seems to me maybe this option meant only for the special "rollback roms" but for "normal" roms maybe Im better off choosing "Normal OS"? (If there even is a difference in the install process...)

**Comment by ProfessorJTJ** [comment]
> Nevermind, thank you for the support and I hope you are doing well!
> 
> Ok so I think I am gonna try `FRD-L09C432B418` then.. is this the only rom currently approved for my phone? How do they block older roms from being installed??
> 
> But before I try `FRD-L09C432B418` are you sure to install it with "Roll-back OS`? Because it seems to me, maybe, this option meant only for the special "rollback roms" but for "normal" roms maybe Im better off choosing "Normal OS"? Is there even a difference in the install process or is it just a gui thing?

When you're downgrading, after installing the rom you have to do a data & cache wipe otherwise your phone doesn't boot, if you choose normal os, it will not wipe the data, and you will stuck in boot loop until you wipe the data manually, but if you choose rollback os it does wipe the data for you.

That's the only difference I've noticed according people's feedback...

**Comment by Nuc1eoN** [comment]
Tried `FRD-L09C432B418` with roll-back option as suggested,
but now after phone reboots, I get a failure with the message
>Software update failed!
The update package does not exist.
Please download the package again.

:(
