### ISSUE TITLE
Fix for USB/Fast Boot/Fast Charging

### ISSUE THREAD

**Issue by Loggsie** [ProfessorJTJ/HISuite-Proxy#128]
Change the USB-C cable you are using from when you performed a downgrade, you can revert back to this later on.

To achieve USB funtion again dial `*#*#2846579#*#*` on the menu choose Background Settings, and then USB Port Settings. Three options will appear, choose the one at the bottom, HiSuite Mode and close the dialogue box. Disconnect the USB-C cable and reinsert it into your device and PC again. Within my PC you should now be able to see the device and the HiSuite CD Drive. At this point you can revert to any USB-C cable. Do note however, rebooting your device may result in USB functions being lost. In this instance repeat the above steps.

**Comment by Gregor0819** [comment]
Hi. After downgrade firmware in Huawei p40pro to 10...131 no USB connection, fast charging.  Erecovery updated only to 10...176 the problem is still there. The described solutions are not effective. Irritating lack of fast charging

**Comment by Loggsie** [comment]
![EMUI 11](https://user-images.githubusercontent.com/89365430/140633292-22d3ff4e-3fd8-4002-aa55-91c8f86196aa.jpg)
![EMUI 9 0](https://user-images.githubusercontent.com/89365430/140633295-a303cc3d-ad1b-4b03-9534-5aba99959329.jpg)
![Device Manager](https://user-images.githubusercontent.com/89365430/140633297-6b1d6724-0e7f-425a-891b-d1c7dbee6a6d.jpg)
![Device Manager (2)](https://user-images.githubusercontent.com/89365430/140633303-bcf952e7-c261-48a0-af37-5b1ff88f980b.jpg)

Try the below and let me know how you get on.

With the phone connected to the PC and using an alternative USB-C cable (none original cable), enable HiSuite Mode in USB settings from the dial screen as mentioned above. Then disconnect your device from the PC directly and swap to an alternative USB port. If you don't hear an immediate USB connection sound, remove and reconnect to the same USB port a couple of times waiting a few seconds inbetween each time. 

If this doesn't work disconnect it from your PC again and reboot your device. Go back to the dial screen and ensure HiSuite Mode remains selected, if it is reconnect your phone to the PC again. Otherwise start over until HiSuite Mode remains the default choice, reboot your device again if needed.

The outcome we are looking for is to have HiSuite Mode activate a connection to the PC. I'm unsure why, but this doesn't seem to work with the original cable. The second and most important part is ensuring HiSuite Mode remains the selected option following a device reboot.

**Comment by ProfessorJTJ** [comment]
I guess throwing in any cable will not work, you might need this exact one

![1](https://user-images.githubusercontent.com/49002275/140633958-f6090a2b-cd5a-4636-bb3d-347bc1b37078.png)

![2](https://user-images.githubusercontent.com/49002275/140633963-8c7d59c9-53f4-4733-bf09-78ba0d77108b.jpg)

**Comment by Loggsie** [comment]
Any variant of USB-C should be suffice for connecting to the PC, but for Fast Charge it needs to meet the Qualcomm 3.0+ Quick Charge Standard. The one I am using is an [Asumo Fast Charge 3.1](https://www.amazon.co.uk/gp/product/B07SB37SRX/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1). The original cable works for charging and with other Android devices on the PC first time around, just it fails to respond until the device is initiated with an alternative cable first when used with the downgraded Huwaei.

**Comment by Loggsie** [comment]
In case this is of any use to anyone, these are the interaces the Mate 20 Pro is using following downgrade

![ADB](https://user-images.githubusercontent.com/89365430/140635416-ebec4484-2398-4fab-88da-86f018ae8f4b.jpg)

**Comment by Gregor0819** [comment]
""Try the below and let me know how you get on.

With the phone connected to the PC and using an alternative USB-C cable (none original cable), enable HiSuite Mode in USB settings from the dial screen as mentioned above. Then disconnect your device from the PC directly and swap to an alternative USB port. If you don't hear an immediate USB connection sound, remove and reconnect to the same USB port a couple of times waiting a few seconds inbetween each time.

If this doesn't work disconnect it from your PC again and reboot your device. Go back to the dial screen and ensure HiSuite Mode remains selected, if it is reconnect your phone to the PC again. Otherwise start over until HiSuite Mode remains the default choice, reboot your device again if needed.

The outcome we are looking for is to have HiSuite Mode activate a connection to the PC. I'm unsure why, but this doesn't seem to work with the original cable. The second and most important part is ensuring HiSuite Mode remains the selected option following a device reboot.""


No reaction, just the sound of loading.The computer still can't see your phone :(

**Comment by Gregor0819** [comment]
https://ibb.co/JdG3sKq
https://ibb.co/7tnKLgQ
https://ibb.co/wz3pNvz
https://imgbb.com/9HJV01q

**Comment by Gregor0819** [comment]
Question is why don't I have an update above? All stop at 10...176
https://forum.xda-developers.com/t/phone-doesnt-recognise-usb.4299303/  
https://forum.xda-developers.com/t/gms-on-latest-emui-11-0-0-223-c432e3r5p3-and-how-to-get-back-to-older-firmware-working.4355011/
Same problems: /

**Comment by ProfessorJTJ** [comment]
> Question is why don't I have an update above? All stop at 10...176 https://forum.xda-developers.com/t/phone-doesnt-recognise-usb.4299303/ https://forum.xda-developers.com/t/gms-on-latest-emui-11-0-0-223-c432e3r5p3-and-how-to-get-back-to-older-firmware-working.4355011/ Same problems: /

Try to update from Huawei's support app or by booting to erecovery and updating from there.

If none worked you'll need to use dload package through sd card

**Comment by Gregor0819** [comment]
""Try to update from Huawei's support app or by booting to erecovery and updating from there"""
eRecovery has only updated from 10..131 to ... 176 further package error somewhere such an error

**Comment by Gregor0819** [comment]
So I have to buy a card

**Comment by Gregor0819** [comment]
"" from Huawei's support app""    the same no updates

**Comment by Loggsie** [comment]
You could try using the Pro Team MT.ru - firmware finder for [Android]()https://m.apkpure.com/firmware-finder-for-huawei/com.teammt.gmanrainy.huaweifirmwarefinder/[PC]()http://pro-teammt.ru/projects/hwff/v2/GetLatestVersion.action. 

Hotspot your phone to your PC and switch the PC DNS to that of Pro Team MT, register the ROM update and boot eRecovery and try and force an upgrade this way, it has a similar affect to HiSuite Proxy. Their DNS server is still live as far as I know.

**Comment by Mrdofbeer** [comment]
Been at this all day, no luck for me this side. Think I might give Harmony TP a go. Inexpensive if it solves the problem!

**Comment by Gregor0819** [comment]
I bought a memory card, uploaded by dload 10...176 and everything updated correctly. I gave up on Google. I don't need them that much ;)

**Comment by mersun1969** [comment]
Use computer USB3.0, and use USB3.0 data cable, you can connect normally

**Comment by Gregor0819** [comment]
I use USB 3.0 all the time ;)   dload has restored the phone to its pre-downgrade state.  So far, as you can see, there is no way to Google. Strange that there is no custom Rom on these phones with gms: /

**Comment by badmania98** [comment]
> Hi. After downgrade firmware in Huawei p40pro to 10...131 no USB connection, fast charging. Erecovery updated only to 10...176 the problem is still there. The described solutions are not effective. Irritating lack of fast charging

Dont use 131. Use 121. You will get upgrade OTA after GMS install.
