### ISSUE TITLE
Mate30Pro(11.0.0.215 ) can't be downgrade to EMUI10

### ISSUE THREAD

**Issue by Pongchaan** [ProfessorJTJ/HISuite-Proxy#129]
I do this very times, it's so work.
But not If Mate 30 Pro has EMUI11 and build number 11.0.0.215  November 2021 lastest version, the phone will can not to be downgrade to EMUI10.
When you do it the phone will appear black screen and message that Software install failed.

Please....

**Comment by Pongchaan** [comment]
Help me please

**Comment by ProfessorJTJ** [comment]
Downgrade to a slightly lower version of emui 11
If downgrade succeeds then try downgrading to 10.1

**Comment by Pongchaan** [comment]
I did it but still not work "Install failed" as before.

> Downgrade to a slightly lower version of emui 11 If downgrade succeeds then try downgrading to 10.1

**Comment by pobaraljon** [comment]
hi im also using the same build no. and i can confirm that theres an error during the update, any thoughts on this? thanks

**Comment by nampolitehc** [comment]
I have the same problem with update 11.0.0.215 on LIO-L29, pls help me
![Uploading H4sIAAAAAAAAAD2PwU7DMBBE_8XngnZtr5Pl1BAnKhfEoZwrJ3GDpdat0iQIEP-OG0UcZ-dpZ-ZHTDc_7L-uXjwJFBvRXT7jKlWSx3Dyr-58l3N4CDQgAG3ELfXTjNCxla2skAdeY5VRyUSlFVY7WoK0p15iVlA6oy0Ja_ZxMpSrJCmRVGksVpazZnUL3_r9_HCa_dFv37wrx-wcO0YGBIAEAAA==.png…]()

**Comment by pobaraljon** [comment]
tried downgrading to the nearest last firmware 11.0.0.212, still the same. looks like were doomed if we upgrade to 11.0.0.215.

**Comment by pobaraljon** [comment]
it would install up to 5% (verifying update) then will error after that forcing you to restart.

Anybody fixed it?

![1637552204754](https://user-images.githubusercontent.com/94509766/142797255-1c304412-8db7-4998-aa7e-2dbb018f2b50.jpg)

**Comment by gg19844** [comment]
same issue
anyway, HISuite Proxy seems to be the only useful tool i found on the internet. really good job
I hope the next version shall fix it

> it would install up to 5% (verifying update) then will error after that forcing you to restart.
> 
> Anybody fixed it?
> 
> ![1637552204754](https://user-images.githubusercontent.com/94509766/142797255-1c304412-8db7-4998-aa7e-2dbb018f2b50.jpg)

**Comment by Pongchaan** [comment]
I found some youtuber fix it by up to 12 and then down to 10, It's work.
Try to do then tell us the good news too : )

**Comment by Upin3** [comment]
Mate30Pro(11.0.0.215 )
Only supported hisuite 11 latest version.
11 hisuite older not supported mount os.
If you use hisuite latest in system recovery edit hisuite.xml it works, flashing successful, but must find the latest firmware, if opening proxy rollback can't, proxy cannot patching on hisuite latest version.

**Comment by Upin3** [comment]
So solution, hisuite proxy must upgrade for supported hisuite 11 latest version,
Must work rollback

**Comment by Upin3** [comment]
Maybe there is a way to downgrade on the old hisuite 11 with the system recovery method, but the proxy must be able to patch only updates base, without preload and cust, the old EMUI 11 firmware, just downgraded to emu 10, if it keeps going down to emui 10 it's also okay, no  will bootloop, if bootloop only flash emui 10 full 3 package

**Comment by gg19844** [comment]
sadly my mate 30 pro(region C636) cant upgrade to EMUI12
> I found some youtuber fix it by up to 12 and then down to 10, It's work. Try to do then tell us the good news too : )

i tried. the recovery method did not work and also OTG method too.
> Maybe there is a way to downgrade on the old hisuite 11 with the system recovery method, but the proxy must be able to patch only updates base, without preload and cust, the old EMUI 11 firmware, just downgraded to emu 10, if it keeps going down to emui 10 it's also okay, no will bootloop, if bootloop only flash emui 10 full 3 package

hence, i shall now only wait for EMUI12 or hisuite proxy updated

**Comment by Upin3** [comment]
How many days will you get miui 12 after joining

**Comment by badmania98** [comment]
> I found some youtuber fix it by up to 12 and then down to 10, It's work. Try to do then tell us the good news too : )

Could you post the link to that YT video?

**Comment by Pongchaan** [comment]
> 

https://youtu.be/QUcL8ud-k7U

**Comment by Pongchaan** [comment]
> How many days will you get miui 12 after joining

about 10 days
