### ISSUE TITLE
Apparently Firm(s) is/are not approved for installation

### ISSUE THREAD

**Issue by VladimirKrylov** [ProfessorJTJ/HISuite-Proxy#13]
Hello!
It is not an issue, it is a question.
At the end of the process I have got information window:
```
Apparently Firm(s) is/are not approved for installation and proccess will most likely fail in phone.
You might want to consider cancelling it to avoid time waste.
```

Is it mean that I can't use the method through HiSuite Proxy at all?

**Comment by ProfessorJTJ** [comment]
> Hello!
> It is not an issue, it is a question.
> At the end of the process I have got information window:
> 
> ```
> Apparently Firm(s) is/are not approved for installation and proccess will most likely fail in phone.
> You might want to consider cancelling it to avoid time waste.
> ```
> 
> Is it mean that I can't use the method through HiSuite Proxy at all?

The firmware you're trying to install is not approved yet, it's when huawei uploads a Firmware, it takes two weeks or a month for it to be approved.
You might want to try another firmware or wait a few weeks

**Comment by VladimirKrylov** [comment]
Thank you very much for your answer!
Now it is understandable.
