### ISSUE TITLE
Huawei P40 lite always at "newest firmware" 

### ISSUE THREAD

**Issue by Fnrs-Wlan** [ProfessorJTJ/HISuite-Proxy#131]
Phone : Huawei p40 lite
Url : http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/c8/v3/e7384400e8424caaad57d39dd0477dc9/full/filelist.xml
Using newest Hisuite Proxy
Using Hisuite 10.1.0.5

Problem is that Hisuite always shows that it's the newest firmware even tho Hisuite Proxy showed everything as fine 

I can send logs when I'm at Home

**Comment by ProfessorJTJ** [comment]
You need to add base, cust and preload packages.

Please watch this guide to avoid bricking your phone in the process

https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by Fnrs-Wlan** [comment]
I will test when at home.
Where do I find the cust and preload packages

**Comment by Fnrs-Wlan** [comment]
Ok rn doin system update it finally showed the lower version now,
It worked with Cust, Preload and Base with nothing else ticked

**Comment by Fnrs-Wlan** [comment]
Ok everything worked fine! i even have google installed now.
But i cant connect my phone to my pc do you know why?

**Comment by ProfessorJTJ** [comment]
"- ALERT : Downgrading from Latest EMUI 11 disables your phone's Fast Charging, Fastboot, USB Connection and TestPoint.
- The only way to fix it is updating through OTA, E-Recovery or Dload by memory card to latest EMUI 11. 
"

**Comment by Fnrs-Wlan** [comment]
Sry for bothering you
Saw that too but thougt it doesnt matter cause i have emui 10 
To everyone reading this Using this method works and gives Google Services
Also works after updating to highest again
Thanks alot to you man i appreciate your work
