### ISSUE TITLE
Upgrade proxy to 580

### ISSUE THREAD

**Issue by Jhamesdev** [ProfessorJTJ/HISuite-Proxy#134]
please upgrade ur proxy software because if i use 510 doesnt work cant update and saying no internet connection.

**Comment by ProfessorJTJ** [comment]
Use the hisuite with red icon on desktop

**Comment by Jhamesdev** [comment]
![image](https://user-images.githubusercontent.com/69801305/141775339-2859cb59-aa72-43c0-8fab-f38f1b2f7b8c.png)
Now sir icant switch version how?

**Comment by Jhamesdev** [comment]
i would like to rollback but

**Comment by ProfessorJTJ** [comment]
You need to add base, cust and preload packages please watch this guide carefully

https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by Jhamesdev** [comment]
![image](https://user-images.githubusercontent.com/69801305/141777760-c15e961c-b489-4ca7-a8b6-cc339cd16c20.png)
still

**Comment by Jhamesdev** [comment]
thank you now working i didnt just understand but i try my best then now working thank you!!
