### ISSUE TITLE
honor 6 plus PE-TL10 area code c185

### ISSUE THREAD

**Issue by Alharthi6** [ProfessorJTJ/HISuite-Proxy#135]
I checked your tools but nothing for my area I want to downgrade from latest update android 6.0 EMUI 4.0.1 to android 5.1.1 EMUI 3.1
Thanks in advance.
PE-TL10 area code c185​
Device name: PE-TL10
Firmware version: PE-TL10C185B561
The EMUI version: _4.0.1
Processor: Hisilicon Kirin 925
Oeminfo: hw/meafnaf

**Comment by ProfessorJTJ** [comment]
If there's no firmware available for your model on the website you cannot use hisuite proxy, try to find a dload package for your phone model

**Comment by Alharthi6** [comment]
Could You please give me tips where to find?
I never find nowhere, all links are not working!
Do I have to use same c185 only?
