### ISSUE TITLE
Does not ask for cell phone connection

### ISSUE THREAD

**Issue by walves2017** [ProfessorJTJ/HISuite-Proxy#136]
I have a mate 30 pro, and performed the installation of HiSuite_11.0.0.510_OVE and the entire hdb process, started Hisuite.Proxy and pointed to the correct information for the device that normally generated the new red icon on the desktop, started the new Hisuite(red), but in no way connects to the device to continue.

**Comment by ProfessorJTJ** [comment]
Enabled USB Debugging in your phone settings
