### ISSUE TITLE
Patch failed, Aborting process.... Please Contact Developer If Error Continues

### ISSUE THREAD

**Issue by roldz667** [ProfessorJTJ/HISuite-Proxy#137]
I keep on getting this error

**Comment by ProfessorJTJ** [comment]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Relected** [comment]
@ProfessorJTJ doesnt work

**Comment by yuanzhongP10** [comment]
你好，我点击这个下载链接，下载速度只有几KB,而且下到一半就自己断了，显示无法下载，网络问题，再次点击恢复就是无法下载，需要授权！！ 能麻烦解答一下么？
