### ISSUE TITLE
P20 Pro System Recovery fail

### ISSUE THREAD

**Issue by tristanleboss** [ProfessorJTJ/HISuite-Proxy#138]
Hello,

Thanks for your work. I tried to revive a P20 Pro which stays stuck on the HUAWEI logo (same for the eRecovery mode).

I installed latest version of HISuite-Proxy and tried with both HISuite 11.0.0.510_OVE and 10.0.1.100_OVE.

I followed the procedure and everything seems to be fine but after entering rescue mode, HISuite says "No recovery package has been found for this mobile phone" (translated as accurately as possible from French).

![image](https://user-images.githubusercontent.com/1431508/142518371-26517ac4-7794-4b7b-bd70-4258080b2263.png)

![image](https://user-images.githubusercontent.com/1431508/142518332-c95ed8f3-740b-4067-9a14-b890114a61aa.png)

I attach log file of HISuite.

How can I log the request made by HISuite? Indeed, the log file ends with:

```
[HiSuite_SystemUpdate][[[CAUSE: ]]][[[DATA1: full_recovery result body=[{"status": "1","versionPackageCheckResults": [{"status": "1","versionPackageType": 2},{"status": "1","autoPollingCycle": "1","versionPackageType": 3,"checkEnd": "1"},{"status": "1","autoPollingCycle": "1","versionPackageType": 4,"checkEnd": "1"}]}][tid=5608]]]]
[HiSuite_SystemUpdate][[[CAUSE: ]]][[[DATA1: Enter BL UpdateResBL[tid=5608]]]][[[DATA2: ?]]][[[DATA3: ]]]
[HiSuite_SystemUpdate][[[CAUSE: ?]]][[[DATA1: devD[s_xxx_n],devM[CLT-L29],req[AE6174BA40DB35853E7857643A6EFB47][tid=5608]]]][[[DATA2: ?]]][[[DATA3: ?]]]
[HiSuite_SystemUpdate][[[CAUSE: ]]][[[DATA1: recovery bl_result body=[{"status": "1","versionPackageCheckResults": [{"status": "1","versionPackageType": 2},{"status": "1","autoPollingCycle": "1","versionPackageType": 3,"checkEnd": "1"},{"status": "1","autoPollingCycle": "1","versionPackageType": 4,"checkEnd": "1"}]}][tid=5608]]]][[[DATA2: ]]][[[DATA3: ]]]
[HiSuite_SystemUpdate][[[DATA1: reader parse format ok.[tid=5608]]]]
[RESULT: FALSE][HiSuite_SystemUpdate][[[CAUSE: ERROR_CODE=-1]]][[[DATA1: invalid blVersionCheckResults[tid=5608]]]]
[RESULT: FALSE][HiSuite_SystemUpdate][[[CAUSE: invalid.]]][[[DATA1: [tid=5608]]]]
[HiSuite_SystemUpdate][[[DATA1: invalid[tid=5608]]]]
```

I was wondering what may be different in my use case.

[SystemUpdate_20211119_A.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7566931/SystemUpdate_20211119_A.txt)

**Comment by ProfessorJTJ** [comment]
"OS Type" choose Recovery OS for this one.
