### ISSUE TITLE
LIO-L29 EMUI 11.0.0.215 Software Install Failed 

### ISSUE THREAD

**Issue by nampolitehc** [ProfessorJTJ/HISuite-Proxy#139]
Help me

**Comment by nampolitehc** [comment]
`[](![H4sIAAAAAAAAAD2PwU7DMBBE_8XngnZtr5Pl1BAnKhfEoZwrJ3GDpdat0iQIEP-OG0UcZ-dpZ-ZHTDc_7L-uXjwJFBvRXT7jKlWSx3Dyr-58l3N4CDQgAG3ELfXTjNCxla2skAdeY5VRyUSlFVY7WoK0p15iVlA6oy0Ja_ZxMpSrJCmRVGksVpazZnUL3_r9_HCa_dFv37wrx-wcO0YGBIAEAAA==](https://user-images.githubusercontent.com/94558194/142665534-bceb15df-6ebb-4028-8fc1-6a35921d354b.png))`

**Comment by nampolitehc** [comment]
@ProfessorJTJ please help me 😭😭😭

**Comment by ProfessorJTJ** [comment]
Send hisuite's log

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log
