### ISSUE TITLE
Huawei P40 lite can't reboot after downgrade

### ISSUE THREAD

**Issue by insxa** [ProfessorJTJ/HISuite-Proxy#140]
I have downgrade my huawei to 226 via hisuite proxy and hisuite HiSuite_10.1.0.550_OVE, i choosed based on my phone via link https://www.firmfinder.ml/ and everything seems right.
Just after it was done my phone was shutted down and cant start again.
What can i do now ?

**Comment by ProfessorJTJ** [comment]
Did you choose Os Type as Rollback os or you kept it on update?

Did you add base package only or base, cust and preload?

**Comment by insxa** [comment]
I have added Base, cust and preload all three. I dont know what to do, what have i did wrong or how to fix it. What is dead and why wont turn on?

**Comment by ProfessorJTJ** [comment]
I'm really not sure what could be the cause, try contacting this person, he might be able to give further information/help out

https://ministryofsolutions.com/

**Comment by ProfessorJTJ** [comment]
By the way if you didn't choose OS Type as Rollback os

You have to boot to erecovery and wipe cache & data from there, this fixes it ( assuming that your phone is still able to boot into there )

**Comment by insxa** [comment]
when i was installing i choosed on https://www.firmfinder.ml/ :

BASE: JNY-LGRP2-OVS 10.1.0.226

CUST: JNY-L21-CUST 10.0.1.2(C432)

PRELOAD: JNY-L21-PRELOAD 10.1.0.1(C432R6)

Checked: Roll-back OS

In section Packages all was checked:

Cust PKG
Prloaded PKG

Screenshot below:
![Snimka zaslona (2)](https://user-images.githubusercontent.com/19369515/143445766-444c01c8-8d26-444a-aa9f-6e9eddf820a0.png)

**Comment by absentgraph-ui** [comment]
Did you manage to fix it?I have the same issue...never trusting these methods again

**Comment by insxa** [comment]
> Did you manage to fix it?I have the same issue...never trusting these methods again

No, im not quilified for it to fix, i returned Phone to store where i buyed it

**Comment by absentgraph-ui** [comment]
> 

they gave you your money back?with no questions?

**Comment by absentgraph-ui** [comment]
ok..thank you
