### ISSUE TITLE
Huawei Nova 7 SE Downgrade

### ISSUE THREAD

**Issue by intfranknet** [ProfessorJTJ/HISuite-Proxy#141]
Hello. 

I have a Nova 7 SE (CDY-NX9B) C636 and i been wanting to downgrade to the first version available (10.1.1.131) June 2020 security patch Now i am in 10.1.1.275 (October 2021)  but when i start to downgrade i lose USB connection to the computer like other users with the same issue

Also i tried using dload and the same issue persists

I started to downgrade in increments one by one, does the usb disable function triggers on an specific version or only when i skip versions to downgrade? in theory If i want to reach to that version i will need to do the procedure 17 times. 

i do need to downgrade because one person is offering me the rebrand/change region service but he says i need to have an earlier version of EMUI 10.1.1. I need to change my device from C636 to C605

I tried to install the firmware via fastboot with the instructions provided in the guide but when the firmware is installing appears an error message in HiSuite

Thank you!

**Comment by ProfessorJTJ** [comment]
Hey, unfortunately any downgrades causes the USB functionality lose

However people who used USB type c to type c with USB 3.0 Port on pc reported that they got back the functionality
