### ISSUE TITLE
P30 ELE-l09 Hisuite recovery mode incompatible.

### ISSUE THREAD

**Issue by mission3r** [ProfessorJTJ/HISuite-Proxy#142]
good day sir

I have been searching for a long while to find a solution to recover my device, when I found your tool earlier today I thought I was saved. My problems started after a factory reset left me in FRP lock hell and the "normal" method of bypassing the eRecovery backup was not available to me. The phone would not enter the backup mode after the reboot, but rather would start up at the setup screen with FRP still intact.

After some tinkering and editing the .xml file as per the wiki, I have managed to get the HiSuite recovery mode to work. Hurray!
I then linked all the correct files and restarted the process. Download and decompress is successful and then either it jumps to "Your device is not compatible with recovery mode" or HiSuite simply stops and FC's.

Do you have any suggestions for a possible solution? I can try to log the app and post here if needed.

TIA

P.S. is it possible to force the device to accept different region firmware with HiSuite Proxy?

**Comment by ProfessorJTJ** [comment]
Hey, send fhe generated log file, you can find it at

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by mission3r** [comment]
please find attached log
[SystemUpdate_20211127_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7613766/SystemUpdate_20211127_00.log)
[SystemUpdate_20211128_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7613767/SystemUpdate_20211128_00.log)
s

**Comment by ProfessorJTJ** [comment]
Everything's correct, try changing your cable if it didn't help, this guy might be able to fix it

https://ministryofsolutions.com
