### ISSUE TITLE
problems downgrading my P40 lite

### ISSUE THREAD

**Issue by ghost** [ProfessorJTJ/HISuite-Proxy#143]
Hello, I'm having problems downgrading my P40 LITE, after Update instalation the phone shutdown and now is not possible to turn on using power botton.

**Comment by ProfessorJTJ** [comment]
Hey, unfortunately this issue started getting popular recently, see here
https://github.com/ProfessorJTJ/HISuite-Proxy/issues/140

Can you send the log file? It can be found at:
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by Cvetk0FF** [comment]
Hey! After the firmware, my phone turned off and no longer responds to the connection of the charger, or to the power button, or to other combinations of buttons. Help me please!
Systemupdate.log - https://disk.yandex.ru/d/APfkPfn4K2HDdw

> Привет, к сожалению, этот выпуск в последнее время стал популярным, см. Здесь [# 140](https://github.com/ProfessorJTJ/HISuite-Proxy/issues/140)
> 
> Вы можете отправить файл журнала? Его можно найти по адресу: C: / Users / Your user / App Data / Local / HiSuite / log / Systemupdate.log

Hey! After the firmware, my phone turned off and no longer responds to the connection of the charger, or to the power button, or to other combinations of buttons. Help me please!
Systemupdate.log - https://disk.yandex.ru/d/APfkPfn4K2HDdw
