### ISSUE TITLE
Can not to downgrade from EMUI 11 to EMUI 10.

### ISSUE THREAD

**Issue by kbakkbak** [ProfessorJTJ/HISuite-Proxy#144]
I just installed  HISuite-Proxy and want use it to downgrade my P40 Pro from EMUI 11 to EMUI 10. I run HiSuite Proxy and patched HiSuite 10.0.1.100. Then I connected P40 Pro to HiSuit and run Renew. But only see current version 11.0.0.201, which is up-to-date. And no Other Versions. Please support me!

**Comment by ProfessorJTJ** [comment]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip


Watch this video guide for exact instructions
https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by kbakkbak** [comment]
Now whan I dial this number *#*#2846579#*# the phone just do USSD request with answer "the service not available". Cant see the software version.

**Comment by ProfessorJTJ** [comment]
Add one more star at the end, don't dial, when you add the star it will automatically open the menu

**Comment by kbakkbak** [comment]
Dear, thank you very much, I made all this and GS was installed than I upgraded to EMUI 11 and it's still working good.  The only issue I have with Android Auto as it required Google service to update and if I do so - you know the result - my device became uncertified. May you guess some solution for that?
