### ISSUE TITLE
Your website appears to be hacked

### ISSUE THREAD

**Issue by clc0321** [ProfessorJTJ/HISuite-Proxy#146]
When I check the firmware, it keeps showing spam and fraud messages. Could you please fix it?

**Comment by ProfessorJTJ** [comment]
Running low oh donations we're forced to have that advertising system on the website, it's not supposed to have popups and redirects but they just add those in their codes, I tried to modify their codes, and I kinda succeed with blocking the redirects, I changed them into popups

Donate 4.99$ and I'll remove the advertising system for a month

**Comment by ProfessorJTJ** [comment]
https://professorjtj.github.io/
