### ISSUE TITLE
Will the update erase the phone data?

### ISSUE THREAD

**Issue by clc0321** [ProfessorJTJ/HISuite-Proxy#147]
I want to update to the new version of the system through this tool, and I am worried about my data. I would also like to ask you, can you skip the version upgrade?

**Comment by ProfessorJTJ** [comment]
If you're upgrading from for example 10.0 to 10.1

You can skip, you don't have to be on latest 10.0 version, but if you upgrade from 10.0 straight to 11 you might brick your phone.

You won't lose your data, everything stays intact. But it's recommended that you take a backup. ( even Huawei advises this )

**Comment by 604korupt** [comment]
> If you're upgrading from for example 10.0 to 10.1
> 
> You can skip, you don't have to be on latest 10.0 version, but if you upgrade from 10.0 straight to 11 you might brick your phone.
> 
> You won't lose your data, everything stays intact. But it's recommended that you take a backup. ( even Huawei advises this )

So I upgraded from emui 10.0 straight to 11 in July. Right now, I think everything is fine, could my phone be bricked?

**Comment by ProfessorJTJ** [comment]
> > If you're upgrading from for example 10.0 to 10.1
> > You can skip, you don't have to be on latest 10.0 version, but if you upgrade from 10.0 straight to 11 you might brick your phone.
> > You won't lose your data, everything stays intact. But it's recommended that you take a backup. ( even Huawei advises this )
> 
> So I upgraded from emui 10.0 straight to 11 in July 2021. Right now, I think everything is fine, could my phone be bricked?

If it has already passed the upgrade no it won't brick now you're good

**Comment by 604korupt** [comment]
> > > If you're upgrading from for example 10.0 to 10.1
> > > You can skip, you don't have to be on latest 10.0 version, but if you upgrade from 10.0 straight to 11 you might brick your phone.
> > > You won't lose your data, everything stays intact. But it's recommended that you take a backup. ( even Huawei advises this )
> > 
> > 
> > So I upgraded from emui 10.0 straight to 11 in July 2021. Right now, I think everything is fine, could my phone be bricked?
> 
> If it has already passed the upgrade no it won't brick now you're good

Okay, thank you! I appreciate your help!
