### ISSUE TITLE
p40-pro+ c185(R1) Downgrade Problem

### ISSUE THREAD

**Issue by genseric** [ProfessorJTJ/HISuite-Proxy#148]
Hello, 
I am using hisuite 10.1.0.550 with hi proxy(great work btw). Version info is : 
Base : ELS-LGRP6-OVS 11.0.0.198
Cust : ELS-N39-CUST 11.0.0.2(C185)
Preload : ELS-N39-PRELOAD 11.0.0.3 (C185R1)

i tried downgrading the phone to E10 using firmfinder.ml but failed with the problem during verification of the update, after the reboot to install. 
So i downgraded the phone to 11.0.0.189 just to downgrade to 11.0.0.153 to downgrade to Emui10 .But after the 11.0.0.153 downgrade usb connection failed. so i had to upgrade back to the initial version. it's the same for  11.0.0.177 , the usb connection fails so i can't push further for the next downgrade.
![image](https://user-images.githubusercontent.com/649577/145851482-16c3d8f1-be78-4a65-8cd5-42a8fcbf2966.png)

Is there anything you can suggest ?

**Comment by ProfessorJTJ** [comment]
Unfortunately Huawei blocks downgrade to old versions and doing any successful upgrade nowadays results in USB disfunction, however users reported that using HarmonyTP USB fixes the USB connection issue, you might want to try that.

https://gsmserver.com/harmony-tp-cable/

**Comment by badmania98** [comment]
Yesterday this P40 Pro+ (C185) and a Mate 30 Pro (C432) had this issue.  A P40 Pro (c432) with EMUI11.0.0.230 could downgrade to 10.1.0.121. 
Is this problem related to the last firmware version, to the phone model ?

**Comment by ProfessorJTJ** [comment]
> Yesterday this P40 Pro+ (C185) and a Mate 30 Pro (C432) had this issue. A P40 Pro (c432) with EMUI11.0.0.230 could downgrade to 10.1.0.121. Is this problem related to the last firmware version, to the phone model ?

Yes, apparently it's kind of a patch Huawei added in latest versions to prevent downgrading

**Comment by badmania98** [comment]
Have you heard other people complaining about that?

**Comment by ProfessorJTJ** [comment]
> Have you heard other people complaining about that?

Mostly mate 30 pro users, yes

**Comment by badmania98** [comment]
Hm. P40 Pro will receive 11.0.0.260 I think. Then it is possible to be blocked also on this model.

**Comment by helhaim** [comment]
Hi there, my mate 30 pro c432 is also blocked after i got latest upgrade. is there any possibility to overcome this? Need to downgrade to 10 :/

**Comment by badmania98** [comment]
Try to upgrade to EMUi12 beta and downgrade to EMUI10 with HiSuite proxy.
Source: https://www.youtube.com/watch?v=QUcL8ud-k7U&t=64s

**Comment by helhaim** [comment]
> Try to upgrade to EMUi12 beta and downgrade to EMUI10 with HiSuite proxy. Source: https://www.youtube.com/watch?v=QUcL8ud-k7U&t=64s

Unfortunately i can't join emui 12 beta anymore 😒

**Comment by ProfessorJTJ** [comment]
> Hi there, my mate 30 pro c432 is also blocked after i got latest upgrade. is there any possibility to overcome this? Need to downgrade to 10 :/

Recently a user succeeded the downgrade by using an official downgrade package from EMUI 11 to Emui 10.1

But those packages were for C636, I'll run a search for C432 and inform you of the results.

**Comment by ProfessorJTJ** [comment]
> Hi there, my mate 30 pro c432 is also blocked after i got latest upgrade. is there any possibility to overcome this? Need to downgrade to 10 :/

LIO-L29 C432

Base:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/a7/v3/c128b8e80dee4a0dbbbba267c882ac0b/full/filelist.xml

LIO-LGRP2-OVS 10.1.0.270

492348

CUST:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fc/v3/10fed6800c444f68bdcf44878a6b880d/full/filelist.xml

LIO-L29-CUST 10.0.0.6(C432)

492349

Preload:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/18/v3/1ec4064255af4364a1d34f3f9dfe7ce8/full/filelist.xml

LIO-L29-PRELOAD 10.0.0.1(C432R7)

492350



Fill these fields in HiSuite Proxy, copy paste the packages Url, Name and ID then tick the boxes "CUST PKG" and "Preload PKG" choose OS Type as Rollback OS and good luck.

**Comment by helhaim** [comment]
Thanks a lot, i'll do what you wrote when i get home from work and i'll let you know 🙂

**Comment by ProfessorJTJ** [comment]
@genseric 

ELS-N39 : C185

Try these packages ( add them manually, URL, Name, ID in HiSuite Proxy and then tick the boxes "CUST PKG" and "Prelaod PKG" and choose OS Type as "Rollback OS" )

Base:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/5/v3/6b1489f85d55449d8542bdd8af59300b/full/filelist.xml

ELS-LGRP6-OVS 10.1.0.178

493529

Preload:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/f5/v3/41a52fb9cdf44a41b2157871d41e35e0/full/filelist.xml

ELS-N39-PRELOAD 10.1.0.1(C185R2)

465873

CUST:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/9a/v3/77ae2a1b8a254de7b92162470efdc4d3/full/filelist.xml

ELS-N39-CUST 10.1.0.2(C185)

465871

**Comment by badmania98** [comment]
> 



> > Hi there, my mate 30 pro c432 is also blocked after i got latest upgrade. is there any possibility to overcome this? Need to downgrade to 10 :/
> 
> LIO-L29 C432
> 
> Base: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/a7/v3/c128b8e80dee4a0dbbbba267c882ac0b/full/filelist.xml
> 
> LIO-LGRP2-OVS 10.1.0.270
> 
> 492348
> 
> CUST: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fc/v3/10fed6800c444f68bdcf44878a6b880d/full/filelist.xml
> 
> LIO-L29-CUST 10.0.0.6(C432)
> 
> 492349
> 
> Preload: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/18/v3/1ec4064255af4364a1d34f3f9dfe7ce8/full/filelist.xml
> 
> LIO-L29-PRELOAD 10.0.0.1(C432R7)
> 
> 492350
> 
> Fill these fields in HiSuite Proxy, copy paste the packages Url, Name and ID then tick the boxes "CUST PKG" and "Preload PKG" choose OS Type as Rollback OS and good luck.

I see that the IDs are not present on the page (https://professorjtj.github.io/). The same Name files have other IDs. They are different files?

**Comment by ProfessorJTJ** [comment]
> > 
> 
> > > Hi there, my mate 30 pro c432 is also blocked after i got latest upgrade. is there any possibility to overcome this? Need to downgrade to 10 :/
> > 
> > 
> > LIO-L29 C432
> > Base: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/a7/v3/c128b8e80dee4a0dbbbba267c882ac0b/full/filelist.xml
> > LIO-LGRP2-OVS 10.1.0.270
> > 492348
> > CUST: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fc/v3/10fed6800c444f68bdcf44878a6b880d/full/filelist.xml
> > LIO-L29-CUST 10.0.0.6(C432)
> > 492349
> > Preload: http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/18/v3/1ec4064255af4364a1d34f3f9dfe7ce8/full/filelist.xml
> > LIO-L29-PRELOAD 10.0.0.1(C432R7)
> > 492350
> > Fill these fields in HiSuite Proxy, copy paste the packages Url, Name and ID then tick the boxes "CUST PKG" and "Preload PKG" choose OS Type as Rollback OS and good luck.
> 
> I see that the IDs are not present on the page (https://professorjtj.github.io/). The same Name files have other IDs. They are different files?

Yeah they are different, all the files on the website are updates but work as Rollback too, those files are specialised for downgrade

**Comment by badmania98** [comment]
Please post also for P40 Pro C432.  If there are different files for Preload also R4,R5 and R6. Thanks in advance.

**Comment by badmania98** [comment]
Also R8 for Mate 30 Pro C432. Thank you.

**Comment by ProfessorJTJ** [comment]
> Please post also for P40 Pro C432. If there are different files for Preload also R4,R5 and R6. Thanks in advance.

Tell the exact version

**Comment by badmania98** [comment]
> > Please post also for P40 Pro C432. If there are different files for Preload also R4,R5 and R6. Thanks in advance.
> 
> Tell the exact model

I have to gain 10.1.0.121 (C432E8R5P2) if it is possible for ELS-NX9 (it is 29).

**Comment by badmania98** [comment]
I appreciate your work: transaction ID: 20865760523710296

**Comment by ProfessorJTJ** [comment]
> Also R8 for Mate 30 Pro C432. Thank you.

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/6ec98ec4b15643c4968d994d1595394e/full/filelist.xml

LIO-L29-PRELOAD 10.0.0.1(C432R8)

492351

**Comment by ProfessorJTJ** [comment]
> ELS-

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/c7/v3/076648178c6c45f59631c4428e14c425/full/filelist.xml

ELS-LGRP4-OVS 10.1.0.176

489527

Preloads
R4:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/6e/v3/90a0970594374fb5bd5727573778a486/full/filelist.xml

ELS-N29-PRELOAD 10.1.0.1(C432R4)

464429

R5:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/83/v3/c355765b27aa443fb801d64f260f4af3/full/filelist.xml

ELS-N29-PRELOAD 10.1.0.2(C432R5)

464428

R6:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/ae/v3/44084c718460416e97af9e057640cb8e/full/filelist.xml

ELS-N29-PRELOAD 10.1.0.1(C432R6)

464427


CUST:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/0b/v3/bd4601c1a23d4298a10471fb2066034b/full/filelist.xml

ELS-N29-CUST 10.1.0.8(C432)

464426

**Comment by ProfessorJTJ** [comment]
> Dont you have 121 or 131?



> Dont you have 121 or 131?

Unfortunately the only version that is specialized for downgrade is 10.1.0.176

**Comment by ProfessorJTJ** [comment]
> I appreciate your work: transaction ID: 20865760523710296

Thank you for your generosity, I'm running a search for all available downgrade firmwares, will open a new section on the website just like 'Base Archive" but for downgrade packages

**Comment by badmania98** [comment]
That is a great idea.

**Comment by helhaim** [comment]
@ProfessorJTJ  same thing Unfortunately. 😒 Installation failed.

**Comment by ProfessorJTJ** [comment]
> @ProfessorJTJ same thing Unfortunately. 😒 Installation failed.

Can you share the log file?
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by helhaim** [comment]
> > @ProfessorJTJ same thing Unfortunately. 😒 Installation failed.
> 
> Can you share the log file? C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Should I post it here somehow or rather send you via e-mail?

**Comment by ProfessorJTJ** [comment]
> > > @ProfessorJTJ same thing Unfortunately. 😒 Installation failed.
> > 
> > 
> > Can you share the log file? C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log
> 
> Should I post it here somehow or rather send you via e-mail?

You can send it on email
fullclip39@gmail.com

**Comment by helhaim** [comment]
Ok i Just sent it to you.

**Comment by ProfessorJTJ** [comment]
> Ok i Just sent it to you.

I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange

**Comment by helhaim** [comment]
> > Ok i Just sent it to you.
> 
> I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange

Ok, thanks a lot for your effort, i'll be checking this topic for solution. 👍

**Comment by badmania98** [comment]
> > Ok i Just sent it to you.
> 
> I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange

The guy with Mate 30 pro C636 made first the upgrade to EMUI12 Beta, I think.  Then downgraded to 10.  Do you have other info?

**Comment by ProfessorJTJ** [comment]
> > > Ok i Just sent it to you.
> > 
> > 
> > I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange
> 
> The guy with Mate 30 pro C636 made first the upgrade to EMUI12 Beta, I think. Then downgraded to 10. Do you have other info?

I guess he was on 11, he's in the telegram group with the name Jacob
https://t.me/firmfinder

https://t.me/Junan1999

**Comment by badmania98** [comment]
> > > Ok i Just sent it to you.
> > 
> > 
> > I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange
> 
> Ok, thanks a lot for your effort, i'll be checking this topic for solution. 👍

Could you downgrade on version bellow the one that is on the phone? And after that to try use the ProfessorJTJ  files(links).

**Comment by badmania98** [comment]
> > > > Ok i Just sent it to you.
> > > 
> > > 
> > > I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange
> > 
> > 
> > The guy with Mate 30 pro C636 made first the upgrade to EMUI12 Beta, I think. Then downgraded to 10. Do you have other info?
> 
> I guess he was on 11, he's in the telegram group with the name Jacob https://t.me/firmfinder
> 
> https://t.me/Junan1999

I will joint the group.

**Comment by helhaim** [comment]
> > > > Ok i Just sent it to you.
> > > 
> > > 
> > > I've just checked it, everything is correct, must be Huawei even blocked that downgrade for your model but not for C636 :/ Huawei's strange
> > 
> > 
> > Ok, thanks a lot for your effort, i'll be checking this topic for solution. 👍
> 
> Could you downgrade on version bellow the one that is on the phone? And after that to try use the ProfessorJTJ files(links).

I could try but i've already tried downgrading couple times on different packages but no luck so far. Nevertheless i try tommorow or at the weekend and let you know.

**Comment by badmania98** [comment]
not ”One firmware bellow”. Right is ”ONE firmware bellow”.

**Comment by helhaim** [comment]
> not ”On firmware bellow”. Right is ”ONE firmware bellow”.

I figured that out 🙂 but i don't know if files are available for this type of rollback? 🤔

**Comment by badmania98** [comment]
> > not ”On firmware bellow”. Right is ”ONE firmware bellow”.
> 
> I figured that out 🙂 but i don't know if files are available for this type of rollback? 🤔

Try with HiSuite Proxy as usual.

**Comment by helhaim** [comment]
> > > not ”On firmware bellow”. Right is ”ONE firmware bellow”.
> > 
> > 
> > I figured that out 🙂 but i don't know if files are available for this type of rollback? 🤔
> 
> Try with HiSuite Proxy as usual.

ok, i tried to downgrade to .220 but same error "verification failed". I guess I have to stay on what i upgraded to :)

**Comment by badmania98** [comment]
> > Also R8 for Mate 30 Pro C432. Thank you.
> 
> http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/6ec98ec4b15643c4968d994d1595394e/full/filelist.xml
> 
> LIO-L29-PRELOAD 10.0.0.1(C432R8)
> 
> 492351

It worked . Then he used NM Card + dload firmware to downgrade to a firmware that accepted GMS Install.

**Comment by helhaim** [comment]
> > > Also R8 for Mate 30 Pro C432. Thank you.
> > 
> > 
> > http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/6ec98ec4b15643c4968d994d1595394e/full/filelist.xml
> > LIO-L29-PRELOAD 10.0.0.1(C432R8)
> > 492351
> 
> It worked . Then he used NM Card + dload firmware to downgrade to a firmware that accepted GMS Install.

What's the difference between r7 and r8 variant?

**Comment by badmania98** [comment]
> > > > Also R8 for Mate 30 Pro C432. Thank you.
> > > 
> > > 
> > > http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/6ec98ec4b15643c4968d994d1595394e/full/filelist.xml
> > > LIO-L29-PRELOAD 10.0.0.1(C432R8)
> > > 492351
> > 
> > 
> > It worked . Then he used NM Card + dload firmware to downgrade to a firmware that accepted GMS Install.
> 
> What's the difference between r7 and r8 variant?

That guy used the last HiSuite Proxy (2.4). See if you use the same. You can find it here.

**Comment by badmania98** [comment]
He said: ”Solution: from 11.0.0.208 by hiproxy special rollback image 10.1.0.270 and from this by dload to 10.0.0.193”, ”I have dload firmware 10.0.0.193 and after install gms just update by ota”, 
Regarding proxy I asked about version. His answer: ”You posted it on forum 2.4”.

**Comment by helhaim** [comment]
I tried with 2.4 hisuite proxy and links professorJTJ posted but same thing. Gonna try with different files. Luckily i have decent internet speed ;)

**Comment by ProfessorJTJ** [comment]
> > > > Also R8 for Mate 30 Pro C432. Thank you.
> > > 
> > > 
> > > http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/6ec98ec4b15643c4968d994d1595394e/full/filelist.xml
> > > LIO-L29-PRELOAD 10.0.0.1(C432R8)
> > > 492351
> > 
> > 
> > It worked . Then he used NM Card + dload firmware to downgrade to a firmware that accepted GMS Install.
> 
> What's the difference between r7 and r8 variant?

Read step 3 of the guide to find out what R version does your phone have 

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by badmania98** [comment]
I think he want to try R8.

**Comment by helhaim** [comment]
> I think he want to try R8.

exactly :) but i didn't cause i think it won't work.

**Comment by badmania98** [comment]
Who knows if you dont try it?

**Comment by helhaim** [comment]
i would but i'm afraid to brick my phone ;) who knows what happens?

**Comment by ProfessorJTJ** [comment]
> i would but i'm afraid to brick my phone ;) who knows what happens?

Yeah, I still get anxiety when I remember the times when I used to test hisuite proxy on my mate 10 pro 😂

**Comment by badmania98** [comment]
> i would but i'm afraid to brick my phone ;) who knows what happens?

Yow will not use the phone anymore. As now.

**Comment by helhaim** [comment]
Ok, I tried every single firmware available on hi suite proxy and nothing changed. I didn't test only r8 variant. I wonder why Huawei blocked every downgrade, even to previous version of 11? Its kind of forcing us to use what they want, and that's a con in my opinion. As far as I like this company I can't agree with steps they've taken. I think it's against users. 🤷‍♂️

**Comment by badmania98** [comment]
Could you try to rest to factory settings and after that to try all this variants?

**Comment by helhaim** [comment]
> Could you try to rest to factory settings and after that to try all this variants?

I can try if I have enough time 🙂 I'll probably do it and post the result. P. S. also tried r8 variant yesterday but no luck 😒

**Comment by badmania98** [comment]
> > Could you try to rest to factory settings and after that to try all this variants?
> 
> I can try if I have enough time 🙂 I'll probably do it and post the result. P. S. also tried r8 variant yesterday but no luck 😒

Or using a NM card and downgrade step by step from higher to lower.

**Comment by helhaim** [comment]
> > > Could you try to rest to factory settings and after that to try all this variants?
> > 
> > 
> > I can try if I have enough time 🙂 I'll probably do it and post the result. P. S. also tried r8 variant yesterday but no luck 😒
> 
> Or using a NM card and downgrade step by step from higher to lower. Dload firmware

I think if downgrade two steps down i'll be able to downgrade further with previous method with hisuite proxy. Unfortunately i don't have nm card, but as far as I remember I can also use otg?

**Comment by badmania98** [comment]
> > > > Could you try to rest to factory settings and after that to try all this variants?
> > > 
> > > 
> > > I can try if I have enough time 🙂 I'll probably do it and post the result. P. S. also tried r8 variant yesterday but no luck 😒
> > 
> > 
> > Or using a NM card and downgrade step by step from higher to lower. Dload firmware
> 
> I think if downgrade two steps down i'll be able to downgrade further with previous method with hisuite proxy. Unfortunately i don't have nm card, but as far as I remember I can also use otg?
> 
> @ProfessorJTJ could you provide some tutorial ho to use dload? I've never used this method. And do you think it's possible to downgrade using this method?

I have to think to all possibilities. NM Card is a must have. Sometimes OTG can not work.

**Comment by badmania98** [comment]
I can provide the tutorials. 
For better and fast response contact me on Telegram: https://t.me/badmania98

**Comment by helhaim** [comment]
[Concerning mate 30 pro c432] Ok, so with a little help of @badmania98 I was finally able to downgrade from latest. 230 update to emui 10, and after that successfully install gms. I used dload method first, and downgrade to. 220 using dload files (previous update, one step lower). Then, as my USB connection was fine I used hi suite proxy to downgrade straight to emui 10. No installation fault at this time. I want to say thanks to @badmania98 nad @ProfessorJTJ for their help and effort.

**Comment by badmania98** [comment]
You are welcome!

**Comment by genseric** [comment]
Hey. Can you share all the steps so we can avoid mistakes? Sent from my Huawei phone-------- Original message --------From: helhaim ***@***.***>Date: Thu, 23 Dec 2021, 12:33To: ProfessorJTJ/HISuite-Proxy ***@***.***>Cc: ozgur ***@***.***>, Mention ***@***.***>Subject: Re: [ProfessorJTJ/HISuite-Proxy] p40-pro+ c185(R1) Downgrade Problem (Issue #148)
[Concerning mate 30 pro c432] Ok, so with a little help of @badmania98 I was finally able to downgrade from latest. 230 update to emui 10, and after that successfully install gms. I used dload method first, and downgrade to. 220 using dload files (previous update, one step lower). Then, as my USB connection was fine I used hi suite proxy to downgrade straight to emui 10. No installation fault at this time. I want to say thanks to @badmania98 nad @ProfessorJTJ for their help and effort.

**Comment by helhaim** [comment]
Hi, sure I can.
1. I downloaded dload files and extracted it. I searched for "Huawei Mate 30 Pro Lion-L29 hw eu LIO-L29 11.0.0.220(C432E7R8P4)_Firmware_EMUI11.0.0_05016HEY.zip"
2. After I downloaded it I extracted and copied directory dload to the root of my USB otg (this dir contains 3 zip files). I must inform that I have r7 version of my Huawei mate 30 pro c432, but I used dload files for r8 variant and everything worked OK. 
3. I switched off my phone and turned it on,(not restart), after vibration when Huawei logo is displayed I pressed power button 3 times, then phone entered recovery mode.
4. Then I chose upgrade from usb/otg and upgrade started.
5. After upgrade (downgrade) I used @ProfessorJTJ's hi suite proxy to downgrade straight to emui 10.0.... I chose the oldest version of emui 10 avaliable on firmfind  site and preload r8 variant.
6. After this downgrade I used googlefier to install gms. And that's all.
Without @badmania98 and @ProfessorJTJ help I wouldn't be able to to this because I've never used dload before.

**Comment by badmania98** [comment]
It works on P40 Pro with the same procedure but device specific firmware.

**Comment by helhaim** [comment]
As I changed my 'r' variant from 7 to 8, my updates by ota have changed. On r7 variant I had 11.0.0.230 and now I have 11.0.0.196. I think I went to far with ota updates 😂

**Comment by badmania98** [comment]
Better disable your EMUI upgrades:
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/post-86030039

**Comment by wasabio** [comment]
> Also, It works on P40 Pro with the same procedure but device specific firmware.
> 
> For C432 download from 11.0.0.260 to 11.0.0.230 using DLOAD, and from 11.0.0.230 to 10.1.0.121 using HiSuite Proxy. DLOAD firmware: https://androidhost.ru/Z6c

Hi !
I have a similar issue when trying to downgrade from 11.0.0.260 on P40 pro (ESL-N29 C342).
With both HiSuite and Dload method, I am always getting the "Software install failed" screen after the reboot (it verifies update until around 4% then I have this screen).

@badmania98 I tried the Dload method with a different firmware  from the one you provide because my Base version is LGRP4 instead of 5. I used this one: http://huawei-firmware.com/rom/huawei-p40-pro+/els-n29/50251

But even with this version I still get same result.

Does someone have any idea why it does not work ?

**Comment by badmania98** [comment]
> > Also, It works on P40 Pro with the same procedure but device specific firmware.
> > For C432 download from 11.0.0.260 to 11.0.0.230 using DLOAD, and from 11.0.0.230 to 10.1.0.121 using HiSuite Proxy. DLOAD firmware: https://androidhost.ru/Z6c
> 
> Hi ! I have a similar issue when trying to downgrade from 11.0.0.260 on P40 pro (ESL-N29 C342). With both HiSuite and Dload method, I am always getting the "Software install failed" screen after the reboot (it verifies update until around 4% then I have this screen) but I do not have other error messages.
> 
> @badmania98 I tried the Dload method with a different firmware from the one you provide because my preload version is c432R5 instead of 6. I used this one: http://huawei-firmware.com/rom/huawei-p40-pro+/els-n29/50251
> 
> But even with this version I still get same result.
> 
> Does someone have any idea why it does not work ? ![Screenshot_20211225_093613_com huawei android projectmenu](https://user-images.githubusercontent.com/18229854/147383985-2f83bb6d-5248-458c-8e1a-2a063e1850c6.jpg)

Have you tried the version from me?

**Comment by wasabio** [comment]
I just tried your version and it worked !
I will go on and use HiSuite as you suggested to downgrade from 11.0.0.230 to 10.1.0.121 and install GMS.

What is different with your version and where did you got it ? 
That's so cool, thanks a lot !

**Comment by badmania98** [comment]
> I just tried your version and it worked ! I will go on and use HiSuite as you suggested to downgrade from 11.0.0.230 to 10.1.0.121 and install GMS.
> 
> What is different with your version and where did you got it ? That's so cool, thanks a lot !

For better and fast response contact me on Telegram: https://t.me/badmania98

**Comment by gregsifr** [comment]
Is anyone having trouble downloading the files located here?: https://androidhost.ru/Z6c 

The download fails for me and I've tried using different devices, networks (mobile/cable) and VPN (on/off) and it still fails. Seems to fail at <50mb, seeing if anyone had similar experiences and/or if the files are also hosted elsewhere?
