### ISSUE TITLE
Can someone help me to downgrade from EMUI 11 to EMUI 10

### ISSUE THREAD

**Issue by JuanF007** [ProfessorJTJ/HISuite-Proxy#149]
I am trying to downgrade the Firmware version of my Huawei MatePad Pro 10.8 (WiFi version)
I am currently on the EMUI 11 version **11.0.0215 (C605E3R1P6)**
and I would like to downgrade to **EMUI 10.1 (10.1.0.151)** **(Image 1)**
but I don't know exactly which is the correct PRELOAD and CUSTOM **(Image 2)**
Can someone help me which one to download according to the information of my device Please **(Image 3)**

**(Image 1)**
![1](https://user-images.githubusercontent.com/43446222/145848303-cb114d53-377b-4d76-932e-6f9603192c16.jpg)
**(Image 2)**
![image](https://user-images.githubusercontent.com/43446222/145848526-d67966f5-3322-478c-a908-d876159ac3f1.png)
**(image 3)**
![3](https://user-images.githubusercontent.com/43446222/145849626-5d8b75d9-661a-4553-81c8-2d97be4936c1.jpg)

**Comment by JuanF007** [comment]
> Hi, any 10.1.0 version is fine.


I am downloading using **MRX-W09-PRELOAD 10.0.1.3 (C605R1) - MRX-W09-CUST 10.0.1.3 (C605)** (Image 1)
but I get the following error:  GROUP VERSION NOT MATCH **(Image 2)**

![4444](https://user-images.githubusercontent.com/43446222/145854266-41feb16c-1cd9-4f3d-bd68-0c54ecc95bcf.jpg)
![image](https://user-images.githubusercontent.com/43446222/145854024-c1f2fce1-36f1-416d-8f4c-e3438d0d4165.png)

**Comment by JuanF007** [comment]
> Hi, any 10.1.0 version is fine.

Thanks

**Comment by genseric** [comment]
[https://github.com/ProfessorJTJ/HISuite-Proxy/issues/148](url) can i use the r2 instead of r1 as well?

**Comment by ProfessorJTJ** [comment]
> [https://github.com/ProfessorJTJ/HISuite-Proxy/issues/148](url) can i use the r2 instead of r1 as well?
Yes it's fine as long as it's for your region.
