### ISSUE TITLE
I need help, i have problem with Hisuite system recovery, i have P40pro+ brick..

### ISSUE THREAD

**Issue by badbadnotgoood** [ProfessorJTJ/HISuite-Proxy#15]
I don't understand how to support my phone in Hisuite and i don't understand where i can find CUST firm + Pre-loaded applications firm. PLS HELP ME, i can't use my bricked phone...

**Comment by ProfessorJTJ** [comment]
> I don't understand how to support my phone in Hisuite and i don't understand where i can find CUST firm + Pre-loaded applications firm. PLS HELP ME, i can't use my bricked phone...

It's really hard to find firmwares because huawei doesn't give any official way for that and the third party way is not efficient at all

https://pro-teammt.ru/en/online-firmware-database/
