### ISSUE TITLE
About the 'Complete Guide Wiki'

### ISSUE THREAD

**Issue by ghost** [ProfessorJTJ/HISuite-Proxy#150]

**Comment by 604korupt** [comment]
Here's a screenshot for more info
![image](https://user-images.githubusercontent.com/95392953/145949968-efe4e781-da61-46f9-83ac-f0f55b5708ca.png)

**Comment by ProfessorJTJ** [comment]
> Here's a screenshot for more info ![image](https://user-images.githubusercontent.com/95392953/145949968-efe4e781-da61-46f9-83ac-f0f55b5708ca.png)

I don't exactly know but you don't need to consider them for an update. According to the analytics we've done on hisuite, only base, cust and preload are required to perform an update or downgrade
