### ISSUE TITLE
Recovery on Mate Xs Unknown CUST and BOOTLADER

### ISSUE THREAD

**Issue by UMB8998** [ProfessorJTJ/HISuite-Proxy#152]
Hello, I'm trying to update the firmware on my Mate Xs, for some weird reason when I enter the numbers to see the region Info the number shows as 0001 and not the regular region, after looking in the phone I found on the about section that my region is C605, I downloaded all the complete package but the phone doesn't pass from 0% it says that I have to recover.
I tried putting the phone on fastboot and recovery mode, updated the HiSuite XML for my phone model, but the system shows that I have no packages available for this phone.
Attached is the SystemUpdate log, the weird thing is that it shows the CUST and PRELOAD as unknown
Thank Yo
[SystemUpdate_20211219_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7741322/SystemUpdate_20211219_00.log)
u

**Comment by ProfessorJTJ** [comment]
Your phone doesn't turn on?

Tick the box "Debug Logging" in hisuite proxy and try again, then send the generated logs.txt file, you can find it beside hisuite proxy.exe

**Comment by UMB8998** [comment]
Thank you, the phone did turn on, and work normally, my mistake was that I had to put the update mode in recovery for the soft brick update to function, after that it worked perfect.
Thank you very much for the program, it's amazing!
P.S. I recomend you to update the instruction for soft brick to say that the software has to be on recovery mode for it to work
