### ISSUE TITLE
HiSuite.Proxy not working with EMUI 11 11.0.0.230 C432

### ISSUE THREAD

**Issue by pixi86** [ProfessorJTJ/HISuite-Proxy#153]
I have P40 pro with 11.0.0.230 C432 SW version.
Recently I was part of ther EMUI 12 BETA, finished it, and rolled back to 11.0.0.230 using the HiSuite 11.0.0.580_OVE. -
I have to install GMS again and I need to roll back to 10.0.0.121.

Downloaded the latest HiSuite.Proxy and compatible HiSuite 11.0.0.530_OVE.
HiSuite is able to connect, sideload client app and show the code and then connect - so all is fine.
But Patched version of HiSuite.Proxy is not invoking the code generation and i am not able to connect to my phone?

Do you have any ideas why?

**Comment by ProfessorJTJ** [comment]
If you mean red icon hisuite can't recognise your phone, enable USB Debugging from settings

**Comment by pixi86** [comment]
"HiSuite is able to connect, sideload client app and show the code and then connect - so all is fine."
USB debugging enabled, HDB enabled
Yes, the RED one does not invoke code routine

**Comment by ProfessorJTJ** [comment]
> "HiSuite is able to connect, sideload client app and show the code and then connect - so all is fine." USB debugging enabled, HDB enabled Yes, the RED one does not invoke code routine

Take a screenshot from Hisuite proxy I honestly don't understand your English

**Comment by helhaim** [comment]
> "HiSuite is able to connect, sideload client app and show the code and then connect - so all is fine." USB debugging enabled, HDB enabled Yes, the RED one does not invoke code routine

You mean there is no code on your phone screen to type into hisuite to connect phone?

**Comment by badmania98** [comment]
What I undersand: When he use HiSuite 11.0.0.530_OVE the window to insert the code is available. When he use RED one, this window to insert the code from the phone is not available.
