### ISSUE TITLE
Emui 12 beta problem- p40 pro+ els n39 c432

### ISSUE THREAD

**Issue by Ruwen97** [ProfessorJTJ/HISuite-Proxy#154]
Why does it show that there are no events available for participation?  I want to sign up for emui 12 beta.  The model is p40 pro+ els n39 c432

> ##https://user-images.githubusercontent.com/96522573/147070448-5a168593-4d63-44ed-b9b4-80907fa933a7.mp4

#

**Comment by ProfessorJTJ** [comment]
Probably the number of users needed is already filled, contact Huawei's support?
