### ISSUE TITLE
P40 PRO EU rollback problem 

### ISSUE THREAD

**Issue by spirospipis** [ProfessorJTJ/HISuite-Proxy#155]
hi im with EMUI 12 beta and i want to rollback to emui 11 i try to use proxy method but failed
![PATCH](https://user-images.githubusercontent.com/96701583/147419599-b401db4b-1974-43cb-8cb7-1fcfaf2428c1.jpg)

**Comment by ProfessorJTJ** [comment]
Use hisuite 11.0.0.510

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3/HiSuite_11.0.0.510_OVE.rar

Or hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3/HiSuite_11.0.0.510_OVE.rar

**Comment by spirospipis** [comment]
i get a message from hisuite when i try to update there is no internet connection and cant continue

**Comment by ProfessorJTJ** [comment]
> i get a message from hisuite when i try to update there is no internet connection and cant continue

If you used hisuite 11 open the hisuite with red icon on desktop

https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by EWB212** [comment]
I have same problem, already download and install using hisuite 10.1 but after finish download there is a installation failed notification on P40 pro emui 12 (not beta anymore... How to downgrade emui 12 to 11??

**Comment by EWB212** [comment]
![IMG_20220116_011035](https://user-images.githubusercontent.com/97802356/149633488-1af140e8-6bea-4e0a-a71e-1665dae2c17f.jpg)
After download and install.. My p4 pro with emui 12 stable, was not able to install the New emui 10 to the phone

**Comment by spirospipis** [comment]
you must do these steps https://github.com/ProfessorJTJ/HISuite-Proxy/issues/155#issuecomment-1001345782

**Comment by spirospipis** [comment]
im fine now thnx ProfessorJTJ

**Comment by odzoski88** [comment]
Is there already a way to downgrade from 11.0.0.260

**Comment by Allesanddro** [comment]
https://github.com/ProfessorJTJ/HISuite-Proxy/issues/200#issuecomment-1104191292

**Comment by Allesanddro** [comment]
> Is there already a way to downgrade from 11.0.0.260, no matter what I try it says software failed

https://github.com/ProfessorJTJ/HISuite-Proxy/issues/200#issuecomment-1104191292
