### ISSUE TITLE
P40 Lite (JNY-LX1) 

### ISSUE THREAD

**Issue by t0ry003** [ProfessorJTJ/HISuite-Proxy#156]
I cannot find any firmware on your website that can help me downgrade my phone. After checking the opened issues out here i found that some guys got some sort of firmware for this model. Maybe they got it from somewhere else?

**Comment by ProfessorJTJ** [comment]
JNY-LX1
Is not a model.
https://www.youtube.com/watch?v=CdYpZlXlgOQ

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by t0ry003** [comment]
Thank you for the fast reply. I found my mistake (i was very tired yesterday). Good job on the guides!
