### ISSUE TITLE
Can't upgrade/downgrade P30 Pro, Stuck on erecovery

### ISSUE THREAD

**Issue by supowah** [ProfessorJTJ/HISuite-Proxy#157]
Hi All,

My friends phone is stuck with the eRecovery screen. I have try to upgrade/downgrade without any luck.
Downgrading is totally not working and with upgrading using the system recovery method the following happens.

download and unpack are 100% but at recovery install (the thirth round bullet) i got the error saying  "my device is not supported for system recovery". Does anyone have a tip of suggestion what i could do. I'm using Hisuite 10.1.0.550.

I Used the Recovery OS option in HiSuite Proxy as, Normal and Rollback OS is not working. I did not tried the Developer option.

ps: in the past we also went to a Huawei service center but they could not revive the phone

any help is appreciated.

with kind regards,

[SystemUpdate_20211229_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7791205/SystemUpdate_20211229_00.log)

**Comment by ProfessorJTJ** [comment]
Hi, uninstall hisuite, install latest hisuite 11, then try recovery after modifying the supported devices' file.

**Comment by supowah** [comment]
Hi, thx for response ok i will try with latest version 11

**Comment by supowah** [comment]
Hi, I tried the latest Hisuite version but HiSuite proxy showed and error while loading.
I tried the HiSuite_11.0.0.510_OVE version and it said on the phone installing update, but it stucked at 2% and after
that it said update failed. I think recovery option does not work is because i'm trying to recover base version 11.0.0.153 with 11.0.0.174. Unfortunately there's no 11.0.0.153 on firmfinder.

Also when i choose normal OS option, instantly the error "there is no recovery package for your phone model" comes.

do you have any other ideas?

**Comment by ProfessorJTJ** [comment]
I don't think you need to use hisuite proxy, disable the proxy from hisuite's settings and use the green icon hisuite, try again with Hisuite proxy, see if it will be able to recover

**Comment by supowah** [comment]
Same result, recovery failed error. The only difference was that i was able to choose the normal OS option without the former instantly error i mention before. The Recovery option also displays, recovery failed and update stuck at 2%.

Do you maybe have the base, cust, and preload for my phone so that i maybe can try it through otg cable and dload method
