### ISSUE TITLE
Huawei mate 30 pro downgrade not working.

### ISSUE THREAD

**Issue by cirakas116** [ProfessorJTJ/HISuite-Proxy#159]
Hi all, I am new to firmware upgrade and downgrade. Just received a new phone Huawei mate 30 pro from my cousin with an updated version of 11.0.0.236. Tried all the ways to downgrade to version 10.1 using Hisuit and Hisuit proxy. The firmware is getting downloaded and moved to the phone as expected. But after restarting and proceeding about 4%, it gets stopped with the message "Installation Failed".  Any help would be appreciated. Thank you.

Model: Huawei mate 30 pro
Region: C636 
Build number: 11.0.0.236 (C636E6R7P5)

**Comment by ProfessorJTJ** [comment]
Hi, have you tried choosing firmwares from the "Downgrade" section?

https://professorjtj.github.io/Downgrade

**Comment by cirakas116** [comment]
Hi ProfessorJTJ,

Thank you for your reply

Yes, I tried choosing the firmware from the "Downgrade" section. The same ended with "Installation Failed".

Regards,

**Comment by dongxin123** [comment]
Hi, I also face same problem
show "Software install failed" get help from http://www.emui.com/emotiondownload.php?mod=restore

**Comment by ProfessorJTJ** [comment]
Huawei blocks downgrade from emui 11
Though people managed to rollback by downgrading using a dload package to earlier version of emui 11 and then using hisuite proxy to downgrade to emui 10.1

Others succeeding by downgrading to 10.0 instead of 10.1

**Comment by dongxin123** [comment]
I have tried downgrade to 10.0.0.217 but still show this issue
I will try more ways to test

**Comment by dongxin123** [comment]
> Huawei blocks downgrade from emui 11 Though people managed to rollback by downgrading using a dload package to earlier version of emui 11 and then using hisuite proxy to downgrade to emui 10.1
> 
> Others succeeding by downgrading to 10.0 instead of 10.1

I have tried downgrade to 10.0.0.217 but still show this issue
I will try more ways to test

**Comment by cirakas116** [comment]
> Huawei blocks downgrade from emui 11 Though people managed to rollback by downgrading using a dload package to earlier version of emui 11 and then using hisuite proxy to downgrade to emui 10.1
> 
> Others succeeding by downgrading to 10.0 instead of 10.1

Few queries/doubts before playing around with downgrading ...

1. To install gms, is it required to downgrade to 10.0? or is it possible to install gms on 10.1?
2. If somehow succeeds to downgrade 11 > 10.1 > 10, will it allow to connect OTG to proceed with gms installation?

Regards,

**Comment by ProfessorJTJ** [comment]
> > Huawei blocks downgrade from emui 11 Though people managed to rollback by downgrading using a dload package to earlier version of emui 11 and then using hisuite proxy to downgrade to emui 10.1
> > Others succeeding by downgrading to 10.0 instead of 10.1
> 
> Few queries/doubts before playing around with downgrading ...
> 
> 1. To install gms, is it required to downgrade to 10.0? or is it possible to install gms on 10.1?
> 2. If somehow succeeded to downgrade 11 > 10.1 > 10, will it allow to connect OTG to proceed with gms installation?
> 3. If somehow succeeded to downgrade from 11 to  11 using **dload**, and then to 10.1 using hisuite proxy, will it possible to downgrade again to 10.0 using hisuite proxy or will get stuck in 10.1?
> 
> Regards,

1. Possible with old emui 10.1 ( the few early releases )
2. Once you downgrade from emui 11 to any version, you lose usb connectivity, using Harmony TP cable fixes this, but OTG is not connectable through that, you need OTG to install GMS?
3. You will most likely lose usb connection, but using HarmonyTP cable fixes it, and then you can use hisuite proxy to downgrade further
4.
https://gsmserver.com/harmony-tp-cable/
