### ISSUE TITLE
Huawei P40 Pro+ Stuck in Boot Loop

### ISSUE THREAD

**Issue by nazmul-ahasan** [ProfessorJTJ/HISuite-Proxy#16]
I have recently attempted to downgrade my newly bought P40 Pro+ (ELS-N39). Since it was running EMUI 10.1.0.156, the only way for me to sideload Google Mobile Services (GMS) was to downgrade my firmware. I've followed a YouTube video, which claimed to have successfully downgraded the firmware using a method involving Firmware Finder, HiSuite, and HiSuite Proxy. (The entire process can be found here: _https://www.android-hilfe.de/forum/huawei-p40-pro.3659/downgrade-der-huawei-firmware-von-147-auf-131.955414.html_ (the text is in German, but the Google Translate works fine).

I am sure I have followed the instructions correctly, but in the end, something went wrong, and the phone is now stuck in a never-ending boot loop. Is it possible for you to be able to help me recover the former firmware or make the current one work?

I have seen a doc about "System Recovery" here: https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/System-Recovery-Rom-Instruction-(-Soft-Bricked-). It asks to "Add your phone model" below `<REGION name="Default">`  and `<REGION name="China">` by modifying `HiSuiteConfig.xml`.

As per the rule shown in the example of a modified file, I have added my model: `<rule type="ELS-N39" cnName="ELS-N39" enName="ELS-N39" option="" ></rule>`

And, obviously, it didn't work.

Firstly, I'm not sure if ELS-N39 is the `rule type`, or `cnName` or `enName`. Do you have the exact and correct names or terms for P40 Pro+? Secondly, is there any chance that by correctly adding the model name, my phone will be fixed at all? Or do you have any other ideas that I can try?

**Comment by sonybes** [comment]
Hi Nazmul! 
Do you have any update or soliution for your issue? I have the same situation and I dont know what to do.

Best

**Comment by ProfessorJTJ** [comment]
:/ You had to wipe data and cache, when you rollback you need to choose OS Type as Rollback OS.

People use update to rollback and so their partition gets corrupted....
