### ISSUE TITLE
Failed to install on BZT3-W09

### ISSUE THREAD

**Issue by Walton-G** [ProfessorJTJ/HISuite-Proxy#160]
我尝试将我的华为平板C5(BZT3-W09)按照指南从'C983'的版本更新到'C00'的版本，但是在计算机显示升级完成后，平板在重启后的校验升级包阶段停止并显示'升级失败！'，我该如何解决这个问题？

**Comment by SkipM4** [comment]
跨版本固件请尝试在USB1.0模式下刷入
