### ISSUE TITLE
how update mate 8 nxt-l29c185b321

### ISSUE THREAD

**Issue by majdarnous** [ProfessorJTJ/HISuite-Proxy#161]
please help me how can update my phone mate 8 nxt-l29c185b321 by hisuite-proxy in firm-finder the rom is  NXT-L29 - C185 | NXT-L29C185B587 | NULL  /and the rom has three files i use hisuite proxy and old firmware the hisuite download only two files the phone restart verifying the package the the software canot install 
![Capture](https://user-images.githubusercontent.com/97966815/149960245-f312f8be-eb84-44b8-954c-2df968f67c7a.PNG)

![Capture2](https://user-images.githubusercontent.com/97966815/149960567-ced4e0ab-fbf8-4301-9b37-65dd5f365998.PNG)

**Comment by majdarnous** [comment]
![Capture3](https://user-images.githubusercontent.com/97966815/149961725-0b79def1-6eb2-487b-8c33-0173e2d6e82e.PNG)

**Comment by ProfessorJTJ** [comment]
Hi, what version is installed on your phone currently?

**Comment by majdarnous** [comment]
c185b321 on my mate 8

**Comment by ProfessorJTJ** [comment]
B587 is a too high version for B321, but B560 might be installable, I've found dload of B560 for free ( slow download link ), but I found B520 too but it's not free ( costs like 2$ ), I'll download the B560 on a virtual server and send you its google drive link to try out. it will take like 8 - 9 hours

**Comment by ProfessorJTJ** [comment]
B560 - ( dload package ) https://drive.google.com/file/d/1MG1EA-2BLjSeYNpZBGDn_EcLoctQDD2g/view?usp=sharing

**Comment by majdarnous** [comment]
i download b560 i have .zip file i unzip the file i have SDupdate_Package.tar i use .7zip i have dload file that contain 2 files hw+update.app how can dload that!!

**Comment by majdarnous** [comment]
![Capture1](https://user-images.githubusercontent.com/97966815/150465321-77601c33-3663-4ea9-9870-aa28553c87c3.PNG)
![Capture2](https://user-images.githubusercontent.com/97966815/150465420-749969c5-1736-4da8-b7b5-e3833cf764ea.PNG)
