### ISSUE TITLE
matte 30 pro emui12 stable downgrade to 10.0.204 for gms

### ISSUE THREAD

**Issue by twinarta81** [ProfessorJTJ/HISuite-Proxy#162]
hello , my matte30pro now emui12 stable version is going to emui10.0.204 for GMS what are the steps? Is it possible to go straight to 12 to 10 ?? i try so many using hisuite proxy , hisuite 10.1.550 after downloading 10.204 finish to 100% then restart to install on the phone but always software failed update. tq before
![Screenshot 2022-01-19 151705](https://user-images.githubusercontent.com/98014648/150090977-9a19d4f4-e11e-4dbe-9fe8-91a5a8f1082c.png)

**Comment by ProfessorJTJ** [comment]
Huawei blocks downgrades except for some specific versions, have you tried version 10.1.0.268?
https://professorjtj.github.io/Downgrade/

**Comment by twinarta81** [comment]
> Huawei blocks downgrades except for some specific versions, have you tried version 10.1.0.268?
> https://professorjtj.github.io/Downgrade/

I Haven't tried it. Can emui10.1.268 possible to sideload Gms?? Can you tell me the steps to get to gms from 10.1.268 to 10.0 maybe.. Thx a lot before.

**Comment by ProfessorJTJ** [comment]
> > Huawei blocks downgrades except for some specific versions, have you tried version 10.1.0.268?
> > https://professorjtj.github.io/Downgrade/
> 
> I Haven't tried it. Can emui10.1.268 possible to sideload Gms?? Can you tell me the steps to get to gms from 10.1.268 to 10.0 maybe.. Thx a lot before.

You just have to place a base, cust and preload packages and choose OS Type as Rollback, no special steps are required. however it is recommended that you use the most recent major OS than the one you have currently.

For example if you're on 12.0 it's recommended you downgrade to 11, after that 11 to 10.1 and then to 10.0

if you downgrade to EMUI 11 from 12 you might lose your USB connection, in that case you have to use HarmonyTP cable to fix that issue and downgrade further.

https://gsmserver.com/harmony-tp-cable/
