### ISSUE TITLE
Huawei Mate 20 Pro (LYA-L29) system recovery issu

### ISSUE THREAD

**Issue by sudani-Meskeen** [ProfessorJTJ/HISuite-Proxy#163]
Hello
My brick phone and I don't understand your tutorial to get out of it. Please Help Me

when try to update it say
your device is not supported for system recovery

your device is not supported for system recovery

**Comment by ProfessorJTJ** [comment]
Share the log file at

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

How to recover:

1. You need to modify a file.
C://Users/Your System username/App data/Local/HiSuite/userdata/UpdateDogDev/HiSuiteConfig.xml"

Add your phone model inside that file, under <REGION name="Default"

2. Boot into fastboot and connect your phone to pc

3. Click on recovery in hisuite

4. Redo step 1

5. Read the log file
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Find what Base, cust and preload packages are installed. 

6. Find the 3 packages (base, cust and preload) in firmfinder

https://professorjtj.github.io

7. Add the packages to HiSuite proxy ( OR SEND THEM HERE FOR ME TO REVIEW ) 

8. Choose OS Type as "Recovery OS" in HiSuite proxy.

9. Click on "recover" in HiSuite.

10. Good luck.

**Comment by neoexploda** [comment]
@ProfessorJTJ 
Thank you in adv for the reply.

my mate 20 pro also encountered the same error as @sudani-Meskeen 

I followed your steps and found the following information:

BASE_VERSION: LYA-LGRP2-OVS 11.0.0.16
CUSTOM_VERSION: LYA-L29-CUST 11.0.0.7(C636)
PRELOAD_VERSION: LYA-L29-PRELOAD 11.0.0.4(C636R1)

But I can't find this firmware from https://professorjtj.github.io thus unable to proceed from step 7 onward.

Please advise where I can get the about firmware.

Regards,
