### ISSUE TITLE
P30 ELE-L29 9.1.0.260(C636E4)

### ISSUE THREAD

**Issue by p30-ELE-L29** [ProfessorJTJ/HISuite-Proxy#164]
Hello!
I have a Huawei device "p30 6-128 au version" and I want to upgrade the system
I downloaded "HiSuite, HiSuite Proxy, FirmwareFinder program" and followed the steps, but there is a problem with the "pro-teammt" website and program "I can't get the package link" I tried a lot but couldn't find the link and an error message appears telling me to contact the developer
please help me

**Comment by ProfessorJTJ** [comment]
https://professorjtj.github.io/

**Comment by p30-ELE-L29** [comment]
thank you very much
But which one is suitable for my device?

9.1.0.260(C636E4) GPU Turbo 
**Australia version**
Base Software Version: ELE-LGRP2-OVS 9.1.0.260
Cust Software Version: ELE-L29-CUST 9.1.0.4(C636)

Sorry I'm a beginner & need emui 10

**Comment by ProfessorJTJ** [comment]
ELE-LGRP2-OVS 10.0.0.178 - https://professorjtj.github.io/350388
ELE-L29-CUST 10.0.0.4(C636) - https://professorjtj.github.io/350389
ELE-L29-PRELOAD 10.0.0.4(C636R3) - https://professorjtj.github.io/350390

**Comment by p30-ELE-L29** [comment]
![IMG_20220122_081105_012](https://user-images.githubusercontent.com/98195535/150627399-7297dcaf-f9ca-4bd4-b80f-366417679569.jpg)

not working

**Comment by ProfessorJTJ** [comment]
If you don't read the guides, you will just end up bricking your phone. so be careful. Use HiSuite 10.1:

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by p30-ELE-L29** [comment]
Can you send the link? (the guide)
and Thank you for all you have given

**Comment by ProfessorJTJ** [comment]
> Can you send the link? (the guide) and Thank you for all you have given

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by p30-ELE-L29** [comment]
Apparently your phone is soft re-branded so normal authentication is going to fail!

Do you want to use authentication bridge?

This appeared to me, what should I do?

**Comment by ProfessorJTJ** [comment]
> Apparently your phone is soft re-branded so normal authentication is going to fail!
> 
> Do you want to use authentication bridge?
> 
> This appeared to me, what should I do?

Send hisuite's log file

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by p30-ELE-L29** [comment]
Excuse me, how?

**Comment by ProfessorJTJ** [comment]
> Excuse me, how?

Find it in this folder:
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Then drag and drop it in here or upload it on any website and send the link to me or send on telegram to me
https://t.me/lurexdj
