### ISSUE TITLE
Huawei P10 VTR-L29 System restore

### ISSUE THREAD

**Issue by Lorramaeloveharry** [ProfessorJTJ/HISuite-Proxy#167]
Im unable to restore my Vtr-l29 Emui 8.0.0.360
I cant find cust and preload of emui 8 and i instead use emui 9 that has cust and preload available on
Firm finder. After i click restore and when it reach to recovery install it just reboot my device away from fastboot
And hisuite just pop up failed to restore.

**Comment by ProfessorJTJ** [comment]
Use emui 8 as base file and tick the box "Old firmware"

Set os type as recovery and try again

**Comment by Lorramaeloveharry** [comment]
> 

do i need cust and preload for emui 8?

**Comment by Lorramaeloveharry** [comment]
im doing it now
![image](https://user-images.githubusercontent.com/95977150/151224413-700b6bb3-3ee2-4d5a-84a0-4c65834b95fd.png)

**Comment by Lorramaeloveharry** [comment]
![image](https://user-images.githubusercontent.com/95977150/151225516-25f0c671-3f73-4ea1-a92b-8d01a2221848.png)

**Comment by Lorramaeloveharry** [comment]
![image](https://user-images.githubusercontent.com/95977150/151225775-b0c8ac2d-2f86-4322-a43e-e7ef38d8125e.png)
it kicks me out from fastboot and then the intsallation of recovery starts

**Comment by Lorramaeloveharry** [comment]
![image](https://user-images.githubusercontent.com/95977150/151226305-8701cdd4-c48d-4da4-b6e6-b22c26429b78.png)
and then it failed

**Comment by Lorramaeloveharry** [comment]
its still the same problem
i cant access erecovery
only fastboot working

**Comment by ProfessorJTJ** [comment]
Try with hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Lorramaeloveharry** [comment]
I already tried it both 10 and 11 still the same

**Comment by Lorramaeloveharry** [comment]
Any idea? For this issue 
I still have fastboot working?
But how can i recover my hardbrick vtr-l29?

**Comment by ProfessorJTJ** [comment]
Share your hisuite log

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by ProfessorJTJ** [comment]
> I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings

Most probably you can just be sure to use the correct package and tick the box "Old firmware"

**Comment by Lorramaeloveharry** [comment]
> > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> 
> Most probably you can just be sure to use the correct package and tick the box "Old firmware"

Should i use Softbrick flash method via Hisuite proxy
Or just use the standard update

**Comment by ProfessorJTJ** [comment]
> > > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> > 
> > 
> > Most probably you can just be sure to use the correct package and tick the box "Old firmware"
> 
> Should i use Softbrick flash method via Hisuite proxy Or just use the standard update

Use standard update, use firmwares with region "NULL" but be sure that their C matches your current C, like C432 or C636
Example:
VTR-L29 9.0.1.183(C636E2R1P9)

And then tick the box "Old firmware"

**Comment by Lorramaeloveharry** [comment]
> > > > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> > > 
> > > 
> > > Most probably you can just be sure to use the correct package and tick the box "Old firmware"
> > 
> > 
> > Should i use Softbrick flash method via Hisuite proxy Or just use the standard update
> 
> Use standard update, use firmwares with region "NULL" but be sure that their C matches your current C, like C432 or C636 Example: VTR-L29 9.0.1.183(C636E2R1P9)
> 
> And then tick the box "Old firmware"

Thank you. ;D
Il try it later

**Comment by Lorramaeloveharry** [comment]
> > > > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> > > 
> > > 
> > > Most probably you can just be sure to use the correct package and tick the box "Old firmware"
> > 
> > 
> > Should i use Softbrick flash method via Hisuite proxy Or just use the standard update
> 
> Use standard update, use firmwares with region "NULL" but be sure that their C matches your current C, like C432 or C636 Example: VTR-L29 9.0.1.183(C636E2R1P9)
> 
> And then tick the box "Old firmware"

do i need cust and preload

**Comment by ProfessorJTJ** [comment]
> > > > > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> > > > 
> > > > 
> > > > Most probably you can just be sure to use the correct package and tick the box "Old firmware"
> > > 
> > > 
> > > Should i use Softbrick flash method via Hisuite proxy Or just use the standard update
> > 
> > 
> > Use standard update, use firmwares with region "NULL" but be sure that their C matches your current C, like C432 or C636 Example: VTR-L29 9.0.1.183(C636E2R1P9)
> > And then tick the box "Old firmware"
> 
> do i need cust and preload

No, for old firmwares you don't need those.

**Comment by Lorramaeloveharry** [comment]
> > > > > > I already fix my worse issue by flash fimware with testpoint But im facing on emui 8 issue the wallpaper is stock android and i cant update to emui 9 via settings no Update available. I wonder if i could use hisuite proxy to update to emui 9 even their is no update available in emui 8 settings
> > > > > 
> > > > > 
> > > > > Most probably you can just be sure to use the correct package and tick the box "Old firmware"
> > > > 
> > > > 
> > > > Should i use Softbrick flash method via Hisuite proxy Or just use the standard update
> > > 
> > > 
> > > Use standard update, use firmwares with region "NULL" but be sure that their C matches your current C, like C432 or C636 Example: VTR-L29 9.0.1.183(C636E2R1P9)
> > > And then tick the box "Old firmware"
> > 
> > 
> > do i need cust and preload
> 
> No, for old firmwares you don't need those.

its already installing how can i cancel it

**Comment by Lorramaeloveharry** [comment]
ok i try again

**Comment by Lorramaeloveharry** [comment]
it booted to twrp i accidentally forgot i have twrp install
i booted into fastboot and flash stock and boot to android
is it okay to update it again without deleting system update log

**Comment by ProfessorJTJ** [comment]
> it booted to twrp i accidentally forgot i have twrp install i booted into fastboot and flash stock and boot to android is it okay to update it again without deleting system update log

Yup it should be fine

**Comment by Lorramaeloveharry** [comment]
> 

thank you so much. i really appreciate your work 
your my savior ;D
