### ISSUE TITLE
Downgrade problem

### ISSUE THREAD

**Issue by adelughh** [ProfessorJTJ/HISuite-Proxy#168]
I need to downgrade from emui 10.1.1.292 to 10.1.1.280 , any version of HiSuite Proxy and HiSuite i shoud use ? or i wait to get HarmonyOs to Downgrade ?
My Phone is Nova 7 SE 😔

**Comment by ProfessorJTJ** [comment]
Latest version of hisuite proxy and hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

You don't need harmonyos, it's supposed to work

**Comment by adelughh** [comment]
I will try it

**Comment by adelughh** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/98486725/151249163-2d32c9d8-4c54-4003-acd8-344066594e99.png)
anything wrong ?

**Comment by ProfessorJTJ** [comment]
Try with hisuite 10.1
If there's an error, it will show to you

**Comment by adelughh** [comment]
Am using 10.1 Already

**Comment by ProfessorJTJ** [comment]
> Am using 10.1 Already

Then I guess you didn't click on "setup" in hisuite proxy.

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by adelughh** [comment]
I did 😥
