### ISSUE TITLE
Firmfinder quastion

### ISSUE THREAD

**Issue by Ruwen97** [ProfessorJTJ/HISuite-Proxy#169]
Dear sir!
I saw Harmony OS with P40 Pro Plus yesterday in Firmfinder, are you sure this is Harmony OS? I guess it should be Emui 12.0.0.218 not 102.0.0.218
![Screenshot_20220128_100055_org mozilla firefox](https://user-images.githubusercontent.com/96522573/151669155-00b3768f-a7a2-4985-a5ed-3729ddad08f0.jpg)

**Comment by ProfessorJTJ** [comment]
> Dear sir! I saw Harmony OS with P40 Pro Plus yesterday in Firmfinder, are you sure this is Harmony OS? I guess it should be Emui 12.0.0.218 not 102.0.0.218 ![Screenshot_20220128_100055_org mozilla firefox](https://user-images.githubusercontent.com/96522573/151669155-00b3768f-a7a2-4985-a5ed-3729ddad08f0.jpg)

I think the same but to my surprise Huawei names emui 12 as 102!
And our script thinks every 102 is harmonyos...

**Comment by Ruwen97** [comment]
Dear sir! 
My Mate40 Pro (C432R6) Emui12.0.218 I use the latest firmfinder 2.0 and hissuite610 ove. However, the upgrade failed when installing the system in recovery.  what do I do?  Is it not supported to fall back to emui11?
Thank you
