### ISSUE TITLE
Support for HiSuite 11

### ISSUE THREAD

**Issue by alexmbaker** [ProfessorJTJ/HISuite-Proxy#17]
The patching process for httpcomponent.dll does not appear to be working with HiSuite 11.0.0.360.  I am not quite sure how the patching code works here, my guess is that you are replacing some certificate thumbprints?  Whatever it is, I am not sure I would know how to start investigating the issue

I have found that version 10 can still be downloaded from [HUAWEI](https://consumer.huawei.com/au/support/hisuite/) by hovering the mouse over the "System Requirements" link and selecting the link for XP/Vista users

**Comment by ProfessorJTJ** [comment]
> I am not quite sure how the patching code works here, my guess is that you are replacing some certificate thumbprints? 
> 

It's an easy process of replacing values of 1 to 0 in a function which checks for the validity of certificate.
The problem is I don't even have a Huawei phone anymore to test this thingy :/

**Comment by michael1900** [comment]
This is a real problem for us NOW. We need a wai to downgrade directly with hisuite 11. **It's really important.**

**Comment by michael1900** [comment]
> > I am not quite sure how the patching code works here, my guess is that you are replacing some certificate thumbprints?
> 
> It's an easy process of replacing values of 1 to 0 in a function which checks for the validity of certificate.
> The problem is I don't even have a Huawei phone anymore to test this thingy :/

can you make a guide so we can try to do it for you?
