### ISSUE TITLE
ELS-NX9 step 1 googlefier does nothing

### ISSUE THREAD

**Issue by anthonycouzens** [ProfessorJTJ/HISuite-Proxy#171]
Hi, I've downgraded my P40 Pro ELS-NX9 to every C432 10.1.0.X O/S using hiproxy and after restoring lzplay from backup and changing clock back to auto the step 1 button just does nothing.

Over the last week I've tried 
10.1.0.109 (384704)
10.1.0.114 (382939)
10.1.0.121 (392311)
10.1.0.131 (392311)
10.1.0.147 (434379)
10.1.0.154 (446801)

I can't find anyone with the same issue on any forum, every video shows the button going to adding the google account. Can you help at all?

Thanks! 

![Screenshot_20220205_175126](https://user-images.githubusercontent.com/37145570/152653276-5b171a00-339f-4a48-b69b-7b4bd2ff822b.jpg)
![IMG_20220205_174552](https://user-images.githubusercontent.com/37145570/152653287-fd638ee9-f282-405f-a560-e28d7094ce22.jpg)
![IMG_20220205_174712](https://user-images.githubusercontent.com/37145570/152653288-f633aa90-0d33-4a60-874b-059210e5ca65.jpg)

**Comment by madrugapt** [comment]
I'm facing same issue right now.... did you solved this issue already?

**Comment by badmania98** [comment]
No 3 here:
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/post-85769693
