### ISSUE TITLE
Mate 20 PRO (LYA-L29) can't install 

### ISSUE THREAD

**Issue by nil-malh** [ProfessorJTJ/HISuite-Proxy#173]
Hello everyone,

I got a Mate 20 pro ( LYA-L29) currently on FirmWare_Base:LYA-LGRP2-OVS 11.0.0.200 and i can't downgrade it to EMUI 9 i tried many base cust etc but it doesn't work, after decompressing, it's fails. it you need to see my logs : https://pastebin.com/x0N4B182.

Any help/enlightenment is welcome thanks in advance.

**Comment by ProfessorJTJ** [comment]
Huawei blocks downgrades, but apparently you're using an old version of hisuite, which doesn't support phones on emui 11.

Try hisuite 10. 1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

Be careful though, downgrades might just fail or result in a bricked phone. And good luck.

**Comment by nil-malh** [comment]
Hello again,

Weird enough, I have the version that you specified already installed and its the one that I use, the phone it self is already bricked and so locked and i tried to do it manually via fastboot but i don't have the permission any idea on how to do ? 

Thanks in advance 
Nil.

**Comment by ProfessorJTJ** [comment]
You cannot downgrade using fastboot,
You need firmware same as or newer than your current firmwares, you currently got

FirmWare_Base: LYA-LGRP2-OVS 11.0.0.200
FirmWare_Cust: LYA-L29-CUST 11.0.0.4(C432)
FirmWare_Preload: LYA-L29-PRELOAD 11.0.0.4(C432R1)

11.0.0.200, isn't on the website, I'll run a manual update later for you, hopefully will be able to retrieve it.


Also try using hisuite without hisuite proxy, open hisuite settings and choose no proxy from there, see if it would find recovery packages.

**Comment by nil-malh** [comment]
HiSuite can't find anything without proxy, does that mean I cannot downgrade at all to emui 9 ?

**Comment by ProfessorJTJ** [comment]
> HiSuite can't find anything without proxy, does that mean I cannot downgrade at all to emui 9 ?

Fastboot / rescue mode cannot perform downgrades

But if your phone is working, you might be able to downgrade

**Comment by nil-malh** [comment]
Is there anything on how to communicate via testpoint like documentation or open-sourced project that use testpoint I could come with something but impossible for me to find anything of use. I don't trust those site enough to put my payment info in it

**Comment by ProfessorJTJ** [comment]
> Is there anything on how to communicate via testpoint like documentation or open-sourced project that use testpoint I could come with something but impossible for me to find anything of use. I don't trust those site enough to put my payment info in it

I'm honestly not up to date with test pont and such methods, but there's a legit guy who does such services in case you can afford his services, you can contact him and know further about the requirements from him.

https://ministryofsolutions.com/
