### ISSUE TITLE
Huawei P40lite can't downgrade - Failed to update

### ISSUE THREAD

**Issue by ShutoKasigari** [ProfessorJTJ/HISuite-Proxy#174]
Hi , I'm trying to downgrade my P40 lite 10.1.0.388 to 10.1.0.226 following the SytemHacks guide down here https://www.youtube.com/watch?v=CdYpZlXlgOQ&list=PLpHwF30JcVZAIwFblXe3UauMCFiEbh6uS&index=1&t=0s

I checked the veneer info and I need to get JNY-L21 base , C432 cust and  C432R6 preload . 
so I got those PKG 
![image](https://user-images.githubusercontent.com/61805486/152695520-043cc105-9c20-4bec-8089-3271f7f61b46.png)

I did it with Rollback OS --> setup --> HiSuite11 --> and then when the phone restart at 0% it stop and says it failed. ( I can do it again and get a pic if needed but I saw other people with the same one.)

Also did it with normal OS and still failed , did it with force auth bridge ( for both rollback and normal OS ) like suggested in another thread but it's still failing.

I already did this process back in may without a problem to install google services on the same device. I had to to format my phone and need to do it all over again so that's why I'm back to that vid and doing it again.

I can still turn on my phone tho , not having the same issue as other people , what can I do to fix this ? Am I missing something or should I just use another method to install GPS with my current version. Doing all this rn to follow SystemHacks guide cause his backup apk doesn't work with my current build and so far he's the only one with a method that doesn't expire after 2 month.

**Comment by ProfessorJTJ** [comment]
Hey, Huawei started blocking the downgrades with the newer versions.
Unfortunately we haven't discovered a way to bypass that but, sometimes messing around, trying different older firmwares or Dload packages work.

I can't suggest a specific version because I'm unaware of specifically working one. And keep in mind you might brick your phone during such trial and error processes, so be careful

**Comment by ShutoKasigari** [comment]
Oh thx a lot , not gonna bother with it if I'm risking briking my phone , btw do you have any specific guide/method to recommend for my current build or should I just go with the most recent/popular one rn.
