### ISSUE TITLE
Downgrade Huawei MatePad T 10s from 10.1.0.217 (Latest) to 10.1.0.131

### ISSUE THREAD

**Issue by zProGaming** [ProfessorJTJ/HISuite-Proxy#178]
Good day!

I tried downgrading via HiSuite Proxy (Latest) without using CUST / Preload. But after the downgrade, the tablet restarts and installs the update. After that, just black screen. No response from the power button or anything. But the recovery mode via HiSuite (Official) works, and I can restore the original firmware (.217).

**Comment by ProfessorJTJ** [comment]
Hi, try updating from erecovery. ( power up + boot buttons ). It probably happened because you didn't add cust and preload packages.

**Comment by zProGaming** [comment]
> Hi, try updating from erecovery. ( power up + boot buttons ). It probably happened because you didn't add cust and preload packages.

Hello sir. 

Memory Card/OTG update mode / USB update mode / eRecovery mode

Should I choose the eRecovery mode sir? And try HiSuite again?

**Comment by zProGaming** [comment]
I successfully downgraded to .143, unfortunately, LZPlay still not working, even Googlefier or the Backup App, can't be installed.

**Comment by zProGaming** [comment]
I tried the .131 version, the device turns on, with sounds, loading, but no display.
