### ISSUE TITLE
Patch failed, Aborting process in HiSuite Proxy

### ISSUE THREAD

**Issue by Eaglesimon02** [ProfessorJTJ/HISuite-Proxy#179]
i need selocion for HiSuite proxy cant not patch in start 
Patch failed, Aborting process in HiSuite Prox
![Screenshot (8)](https://user-images.githubusercontent.com/97362681/154996293-7a412a38-d2f9-45bd-987a-6ee98ca99ee9.png)
y

**Comment by ProfessorJTJ** [comment]
Use hisuite 11.0.0.510 or 530 or hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

https://www.youtube.com/watch?v=CdYpZlXlgOQ
