### ISSUE TITLE
local pkg

### ISSUE THREAD

**Issue by Kyle0923** [ProfessorJTJ/HISuite-Proxy#18]
Hi,
I downloaded the stock firmware. Is there any way for HISuite-Proxy to work with local pkg?

**Comment by ProfessorJTJ** [comment]
check "Advanced" Section.

**Comment by Kyle0923** [comment]
Thanks for the reply.
I tried "Advanced" setting, but I am not sure what to put in the URLs parts. I tried using the local path e.g. `C:/update_sd_base.zip; C://update_sd_base.zip; C:\update_sd_base.zip` none of them are working

**Comment by Kyle0923** [comment]
I mean these 6 boxes
![image](https://user-images.githubusercontent.com/29618161/97521603-4a658500-1974-11eb-96d5-2c6e148a78ea.png)
