### ISSUE TITLE
Recovery on Huawei MatePad T 10s - No Display with Sound / Turning On

### ISSUE THREAD

**Issue by zProGaming** [ProfessorJTJ/HISuite-Proxy#184]
Good day!

Is it possible for HiSuite Proxy to configure HiSuite on recovery OS when the tablet is in fastboot / rescue mode (Power + Vol Down)? USB not detected, only this mode is available.

**Comment by ProfessorJTJ** [comment]
Hi,
Recovery's process a long procedure, bare with me. 

1. You need to modify a file.
C://Users/Your System username/App data/Local/HiSuite/userdata/UpdateDogDev/HiSuiteConfig.xml"

Add your phone model inside that file, under <REGION name="Default"

2. Boot into fastboot and connect your phone to pc

3. Click on recovery in hisuite

4. Redo step 1

5. Read the log file
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Find what Base, cust and preload packages are installed. 

6. Find the 3 packages (base, cust and preload) in firmfinder

https://professorjtj.github.io

7. Add the packages to HiSuite proxy ( OR SEND THEM HERE FOR ME TO REVIEW ) 

8. Choose OS Type as "Recovery OS" in HiSuite proxy.

9. Click on "recover" in HiSuite.

10. Good luck.
