### ISSUE TITLE
HONOR 9X(HLK-AL00) the baseband and IMEI are lost。Device always restarts

### ISSUE THREAD

**Issue by KajiRyouji** [ProfessorJTJ/HISuite-Proxy#187]
My device has been upgraded to HarmonyOS, and I used the official HISuite to downgrade to emui10.

Then use HISuite-Proxy to downgrade emui9. But after using HISuite to downgrade, I was prompted that the data was damaged in recovery and asked me to format.

After the device restarts, the system is downgraded to emui9, but the baseband and IMEI are lost, and the device restarts every minute. HISuite-Proxy has added the three installation packages in the picture to downgrade.
![屏幕截图 2022-03-05 164815](https://user-images.githubusercontent.com/91704814/156877037-fbb04aad-8a07-43ce-93c5-731facd2ae72.png)
![屏幕截图 2022-03-05 165003](https://user-images.githubusercontent.com/91704814/156877041-8bd62bcc-e579-407e-b38b-c9a490ab67f5.png)
![Screenshot_20220301_110441_com android settings](https://user-images.githubusercontent.com/91704814/156877049-4f065160-4f63-47a2-99c5-76b1ba943ad0.jpg)

I tried using a system update to restore USB functionality, but the update is not detected.
When Erecovery is connected to WIFI, it prompts that the installation package information cannot be obtained.
Updates are also not detected in the service center app.

Is there any way to make the device detect the update? Anyone who can answer my doubts would be greatly appreciated!

**Comment by ProfessorJTJ** [comment]
Hi, apparently you've used wrong phone model for your phone. You've installed LGRP3 ( Pro ) on LGRP1 ( normal ) on your phone or vice versa.

Share your hisuite log to tell you exactly what's wrong
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

HiSuite proxy / HiSuite cannot fix your phone now.

You need to use paid services.

**Comment by KajiRyouji** [comment]
> 您好，显然您的手机使用了错误的手机型号。您已在手机上的 LGRP1（正常）上安装了 LGRP3（Pro），反之亦然。
> 
> 分享您的 hissuite 日志以准确告诉您出了什么问题 C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log
> 
> HiSuite 代理/HiSuite 现在无法修复您的手机。
> 
> 您需要使用付费服务。
HISuite has been uninstalled, I can't be sure to keep the logs at that time, I send the existing logs, thank you for your reply.
[SystemUpdate_20220301_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190412/SystemUpdate_20220301_00.log)
[SystemUpdate_20220302_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190413/SystemUpdate_20220302_00.log)
![屏幕截图 2022-03-05 175736](https://user-images.githubusercontent.com/91704814/156878447-013b4bc9-3b97-4de4-9e58-4f33535d5977.png)

**Comment by ProfessorJTJ** [comment]
> HISuite has been uninstalled, I can't be sure to keep the logs at that time, I send the existing logs, thank you for your reply. [SystemUpdate_20220301_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190412/SystemUpdate_20220301_00.log) [SystemUpdate_20220302_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190413/SystemUpdate_20220302_00.log) ![屏幕截图 2022-03-05 175736](https://user-images.githubusercontent.com/91704814/156878447-013b4bc9-3b97-4de4-9e58-4f33535d5977.png)

Not useful... It's empty.

**Comment by LorainLacosta** [comment]
> > HISuite has been uninstalled, I can't be sure to keep the logs at that time, I send the existing logs, thank you for your reply. [SystemUpdate_20220301_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190412/SystemUpdate_20220301_00.log) [SystemUpdate_20220302_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190413/SystemUpdate_20220302_00.log) ![屏幕截图 2022-03-05 175736](https://user-images.githubusercontent.com/91704814/156878447-013b4bc9-3b97-4de4-9e58-4f33535d5977.png)
> 
> Not useful... It's empty.

Can I ask can I use hisuite proxy to debrand my p20?

**Comment by ProfessorJTJ** [comment]
> > > HISuite has been uninstalled, I can't be sure to keep the logs at that time, I send the existing logs, thank you for your reply. [SystemUpdate_20220301_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190412/SystemUpdate_20220301_00.log) [SystemUpdate_20220302_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8190413/SystemUpdate_20220302_00.log) ![屏幕截图 2022-03-05 175736](https://user-images.githubusercontent.com/91704814/156878447-013b4bc9-3b97-4de4-9e58-4f33535d5977.png)
> > 
> > 
> > Not useful... It's empty.
> 
> Can I ask can I use hisuite proxy to debrand my p20?

To another global region? Or to Chinese model?

From global to global for example C636 ( Asia ) to C432 (" Europe ) works, but from Chinese to global or from global to Chinese doesn't work. 

Besides that, if you re-brand to another region, your phone will not be verified, meaning you will not be able to use bank apps, and you will not receive OTA updates inside your phone unless you use hisuite proxy.
