### ISSUE TITLE
Download Local Firmwares

### ISSUE THREAD

**Issue by Scampt** [ProfessorJTJ/HISuite-Proxy#188]
Hi, is there anyway to download de firmware from firm finder to my PC then move to my USB and Plug in my phone to Update?
I can't access to my phone (P40 Pro ELS-N04).its bricked, USB PC only charge, i think i fucked up. I need some HELP!
 Just like this video, or something like that? Can u help me!!!

**Comment by Scampt** [comment]
> Hi, is there anyway to download de firmware from firm finder to my PC then move to my USB and Plug in my phone to Update? I can't access to my phone (P40 Pro ELS-N04).its bricked, USB PC only charge, i think i fucked up. I need some HELP! Just like this video, or something like that? Can u help me!!!

Like this video https://www.youtube.com/watch?v=yFNUbjhaL1k or similar like that

**Comment by Scampt** [comment]
![image](https://user-images.githubusercontent.com/53961709/156964388-b2869740-70d1-4815-b666-21167abbb95f.png)

I need this firmware local, can u help me? I dont find in google, only in your page, but i dont know if i can downloaded

**Comment by Allesanddro** [comment]
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/System-Recovery-Rom-Instruction-(-Soft-Bricked-)
