### ISSUE TITLE
HiSuite 11 Support

### ISSUE THREAD

**Issue by tunasahinn** [ProfessorJTJ/HISuite-Proxy#19]
With new HiSuite, Proxy's settings isn't work anymore. Says ''check your internet connection''. Can you fix?

**Comment by ProfessorJTJ** [comment]
> With new HiSuite, Proxy's settings isn't work anymore. Says ''check your internet connection''. Can you fix?

I don't even have a Huawei phone anymore to be able to keep the support of the app, send me a Huawei phone and I promise to fix it for you in like couple of hours after the phone's arrival lol.

**Comment by tunasahinn** [comment]
> > With new HiSuite, Proxy's settings isn't work anymore. Says ''check your internet connection''. Can you fix?
> 
> I don't even have a Huawei phone anymore to be able to keep the support of the app, send me a Huawei phone and I promise to fix it for you in like couple of hours after the phone's arrival lol.

Ah, so sad. It was nice to use this software
