### ISSUE TITLE
Can't donwgrade p40 pro! 

### ISSUE THREAD

**Issue by ckarmy** [ProfessorJTJ/HISuite-Proxy#190]
Hi! I try several times with many versions of HiSuite 11 (Red icon) but when the download reach 99% I get a message can't update....
Like this:
![IMG_20220314_122327](https://user-images.githubusercontent.com/10090783/158206599-bc9a0276-257d-4caa-8228-17ea4326c7ec.jpg)

The log file:
[SystemUpdate_20220314_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8246280/SystemUpdate_20220314_00.log)

Please, any idea :(

**Comment by ProfessorJTJ** [comment]
Hi, somehow Huawei managed to block downgrades on hisuite 11

Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by ckarmy** [comment]
Work!!!! thanks!
