### ISSUE TITLE
can´t downgrade emui 12 to emui 11 

### ISSUE THREAD

**Issue by ferralg56** [ProfessorJTJ/HISuite-Proxy#191]
i've been trying to downgrade an P40 PRO and an mate 30 pro from emui 12 to emui 11 without success, always show error red icon. last week i could doit without problems but until fryday i had this problem

someone knows how to do it?

**Comment by ProfessorJTJ** [comment]
> i've been trying to downgrade an P40 PRO and an mate 30 pro from emui 12 to emui 11 without success, always show error red icon. last week i could doit without problems but until fryday i had this problem
> 
> someone knows how to do it?

Hi, somehow Huawei has released a hidden patch or a command to all hisuite 11 applications and they no longer approve the installation of old firmwares.

Though hisuite 10.1 still works.


There's also a possibility that the error is on hisuite proxy's side, I'll look further into this in the future.

**Comment by ferralg56** [comment]
> > i've been trying to downgrade an P40 PRO and an mate 30 pro from emui 12 to emui 11 without success, always show error red icon. last week i could doit without problems but until fryday i had this problem
> > someone knows how to do it?
> 
> Hi, somehow Huawei has released a hidden patch or a command to all hisuite 11 applications and they no longer approve the installation of old firmwares.
> 
> Though hisuite 10.1 still works.
> 
> There's also a possibility that the error is on hisuite proxy's side, I'll look further into this in the future.

I finaly could downgrade emui 11 to emui 12 using the new hisuite version
