### ISSUE TITLE
Matepad 10.4 firmware 

### ISSUE THREAD

**Issue by Ruwen97** [ProfessorJTJ/HISuite-Proxy#195]
Dear sir
My device is Matepad 10.4 BAH3-L09 C432R1P3. I see only European version without emui12.  And other regions such as Russia and Asia have.  Can I update to the system shown in the picture through hisuite proxy?
T
![Screenshot_20220415_180747_org mozilla firefox](https://user-images.githubusercontent.com/96522573/163594675-9cf4fc05-3eac-4f57-a703-76813b89bff3.jpg)
hank you

**Comment by ProfessorJTJ** [comment]
Hi, yes you can, another user tested this and it worked.

**Comment by Ruwen97** [comment]
Thank You! In the options, should I choose Normal OS or Roll Back? :)

**Comment by ProfessorJTJ** [comment]
> Thank You! In the options, should I choose Normal OS or Roll Back? :)

Rollback is for downgrade, keep it on normal os
