### ISSUE TITLE
你好，我点击这个下载链接，下载速度只有几KB,而且下到一半就自己断了，显示无法下载，网络问题，再次点击恢复就是无法下载，需要授权！！ 能麻烦解答一下么？Use hisuite 10.1

### ISSUE THREAD

**Issue by yuanzhongP10** [ProfessorJTJ/HISuite-Proxy#196]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

_Originally posted by @ProfessorJTJ in https://github.com/ProfessorJTJ/HISuite-Proxy/issues/137#issuecomment-969972428_

**Comment by Ruwen97** [comment]
你需要下载最新的11.0.0.610ove版配合proxy3.01使用 就不会提示这个错误。https://github.com/ProfessorJTJ/HISuite-Proxy

**Comment by yuanzhongP10** [comment]
我试一下，感谢解惑
