### ISSUE TITLE
huawei p30 update to emui 12 group version does not match

### ISSUE THREAD

**Issue by justinh998** [ProfessorJTJ/HISuite-Proxy#197]
hi i  try to update my huawei p30 (ele-l29) to emui 12 , i use the huawei firm finder v2 with hsiuite proxy v3. I used the emui 12 firmware for the ele-l29 cust c431. My phone is now on 11.0.0.190 with cust 431. But everytime I try to update with hisuite+firmware finder I get the error :group version . Can someone help me please
Hisuity proxy said it is the right firmware
![2022-04-17](https://user-images.githubusercontent.com/102914108/163716408-9b2bfc96-0a1c-4940-8697-a3f2f6516e9d.png)
?

**Comment by ProfessorJTJ** [comment]
Hey, don't do the update please

I will double check the issue

**Comment by justinh998** [comment]
> Hey, don't do the update please
> 
> I will double check the issue

why do you double ceck it? do you know this issue?
okay i dont will update

**Comment by ProfessorJTJ** [comment]
> > Hey, don't do the update please
> > I will double check the issue
> 
> why do you double ceck it? do you know this issue? okay i dont will update

I don't know this issue, I will try to replicate it on my pc and see what happens

**Comment by ProfessorJTJ** [comment]
Exit from the update, and click on update again, do you see the error again?

**Comment by justinh998** [comment]
> > > Hey, don't do the update please
> > > I will double check the issue
> > 
> > 
> > why do you double ceck it? do you know this issue? okay i dont will update
> 
> I don't know this issue, I will try to replicate it on my pc and see what happens

but I don't know if its also an issue with other devices or do you have a p30(ele-l29) with cust c431?

**Comment by ProfessorJTJ** [comment]
Please copy the text of this box and send here.

![Screenshot 2022-04-15 132440](https://user-images.githubusercontent.com/49002275/163717519-7952ef55-d95f-4f63-819e-32430ce281ce.png)

also close hisuite, open it, click update again, do you see the error?

**Comment by justinh998** [comment]
okay here:HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/changelog_preload_hw_eea_R2.xml
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action
HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize
HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/96/v3/gQA6mqB2SJuqjcQalgF5Zw/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/5b/v3/7k8i1eD7R8u_pu1hSiZwqA/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/changelog.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/notify_custom_001.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip

> Please copy the text of this box and send here.
> 
> ![Screenshot 2022-04-15 132440](https://user-images.githubusercontent.com/49002275/163717519-7952ef55-d95f-4f63-819e-32430ce281ce.png)
> 
> also close hisuite, open it, click update again, do you see the error?

**Comment by ProfessorJTJ** [comment]
> okay here:[HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/changelog_preload_hw_eea_R2.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/fd/v3/0efd81afd72b42b0b9f7d543abc673a6/full/changelog_preload_hw_eea_R2.xml) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action) [HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize](HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize) [HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize](HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/96/v3/gQA6mqB2SJuqjcQalgF5Zw/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/96/v3/gQA6mqB2SJuqjcQalgF5Zw/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/5b/v3/7k8i1eD7R8u_pu1hSiZwqA/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/5b/v3/7k8i1eD7R8u_pu1hSiZwqA/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/changelog.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/changelog.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/notify_custom_001.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/65/v3/6ATW0UEcT6mmGqPxsQsWYw/notify_custom_001.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/fc/v3/PIv03g7NScuvUVpVTjV4oA/full/update_full_base.zip)
> 
> > Please copy the text of this box and send here.
> > ![Screenshot 2022-04-15 132440](https://user-images.githubusercontent.com/49002275/163717519-7952ef55-d95f-4f63-819e-32430ce281ce.png)
> > also close hisuite, open it, click update again, do you see the error?

The error is not related to new rom, you can proceed with the installation

**Comment by ProfessorJTJ** [comment]
Do you have telegram?

if you have, please contact me
https://t.me/lurexdj

**Comment by justinh998** [comment]
What does the error stand for then? I tried it downloads but always stops at 79% and hangs and Hisuite 10.0.0.530 does not find the update even it says current version I pressed the patch button.yeah I have telegram and we know us on telegram I think

**Comment by vanvye** [comment]
I also get this error when trying to update my HMA-L29 device:

![image](https://user-images.githubusercontent.com/103981887/163921058-ce97a47b-7cc4-4471-ba67-4e0a51382d44.png)

Below is text when running update with HiSuite Proxy:

HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/changelog_preload_hw_ru_R2.xml
HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action
HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize
HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize

**Comment by ProfessorJTJ** [comment]
> I also get this error when trying to update my HMA-L29 device:
> 
> ![image](https://user-images.githubusercontent.com/103981887/163921058-ce97a47b-7cc4-4471-ba67-4e0a51382d44.png)
> 
> Below is text when running update with HiSuite Proxy:
> 
> [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog/changelog_base_hw_ru.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/changelog_base.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/49/v3/c8GvOcH_QKSZy052I_DcqA/full/notify_custom_001.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hota_900_9/17/v3/8F51OW47Ssa8cknQunNpbg/full/changelog_cust_hw_ru.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/41/v3/327bb00d78db4f3aa1662d658d74900e/full/changelog_preload_hw_ru_R2.xml) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CheckAndAuthorize.action?latest=true&verType=true) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/filelist.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/filelist.xml) [HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/changelog_preload_hw_ru_R2.xml](HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/67/v3/4280705cc0d443a295ba147eb83ff174/full/changelog_preload_hw_ru_R2.xml) [HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action](HTTPS://query.hicloud.com:443/sp_ard_common/v2/CouplingReport.action) [HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize](HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize) [HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize](HTTPS://query.hicloud.com:443/BL/v1/CheckAndAuthorize)

Your device is already on version 11.0.0.160 what are you updating it to? 👀

**Comment by vanvye** [comment]
I want to update to EMUI 12.

**Comment by ProfessorJTJ** [comment]
> I want to update to EMUI 12. I also got this error when try to update without the PKG information.

There is not any EMUI 12 for your device and region for now, you're adding EMUI 11, and because you already have the latest of that installed, it doesn't show the update for you.

**Comment by vanvye** [comment]
Thanks, I understood that no EMUI 12 yet for my device, however what I meaned is why I am getting "Group version not match" error.

**Comment by ProfessorJTJ** [comment]
> Thanks, I understood that no EMUI 12 yet for my device, however what I meaned is why I am getting "Group version not match" error.

Huawei's fault, apparently, in their downgrade system they disabled Base and CUST rollbacks but left the preload

When your device requests a downgrade, it gets preload package only, and because it cannot downgrade using that only, an error is sent to Huawei's servers ( HiSuite Proxy catches the error and shows you its description )

**Comment by vanvye** [comment]
But why I still got this error when do not select any target packages?

**Comment by ProfessorJTJ** [comment]
> But why I still got this error when do not select any target packages?

Because it's no related to HiSuite Proxy, huawei is sending an error report to its servers ( HiSuite doesn't show this error to you ), but while HiSuite Proxy is connected, it realises there's a problem ( not with the rom you chose, but it cannot detect the error is with which package ) and shows you the error.
