### ISSUE TITLE
Question about country code when using this

### ISSUE THREAD

**Issue by mhydamacka** [ProfessorJTJ/HISuite-Proxy#198]
First, I'd like to say thank you for all the work you've done on this site. I've been looking up options for my phone for about a month now. Several hours a day... No site I've found has been this well put together. Thank you for all the work you've done here.
So last month I bought a P30 pro to replace one I already had with a broken screen. The new phone was a great deal on ebay, in perfect condition, listed as a demo. After some quick research I though being a computer tech and pretty well versed in fixing phones I could handle it and if for some reason I was unable to remove the demo I got the same model VOG-L04 that I previously had because I figured I could just swap the mainboards and have a new screen then on my old phone. After some further research and taking part of the demo mode I realized that I cannot add a screen lock and I'd also like to permanently remove the demo by flashing it. 
Here is my question. The demo phone is C819, my old phone is C792 (I'm in Canada). I'm planning to downgrade as this is suggested to remove the demo rom. If I choose the base, cust and program files that have my country code of C792 will that be a problem writing over the old one since I'm writing them all at once and not just flashing the ROM or is that country code locked somewhere else that I have to change it first? Also, do I even need to try downgrading with this or can I just run this with the same file versions but the C792 country codes and that will work? Also, there was not an exact match for the CUST file. The demo has VOG-L04-CUST 9.1.0.3(C819) and this version 9.1.0.3 file isn't availabe with the C792 country code. If I am able to flash with the new country code can I choose a CUST file VOG-L04-CUST 9.1.0.15(C792)?
Thanks again for your hard work and time putting out this info for everyone to use. 
Cheers

**Comment by ProfessorJTJ** [comment]
Hey, if you want to change a demo unit to be global I guess beside firmwares you need to change the device's oeminfo

You will need to modify the oem's VendorCountry to a global string
And then if you can flash global firmwares over demo units ( hisuite proxy can't do that but some paid tools should be able to do it through test point ) you should flash any base, cust and preload combination of the targeted region and you'd be good to go

Cust and preload versions don't really matter that much, they just have to have same first two digits as the base file, like all 3 packages should be 10.1 or 9.1 ( sometimes cust/preload can be 9.0 while base is 9.1 )

**Comment by ziqi1029** [comment]
Is there some way that downgrading from Latest EMUI 11 disables phone's Fast Charging and  USB Connection ?I don't want to upgrade to the latest EMUI11.
