### ISSUE TITLE
need help with brick phone

### ISSUE THREAD

**Issue by darkfighter852** [ProfessorJTJ/HISuite-Proxy#2]
please dude, can u find for me BLA-L09C432 all 3 filese needed for restoration.
i search for 6 hours straight and i cant find, please help me

**Comment by ProfessorJTJ** [comment]
Base:
http://update.dbankcdn.com/TDS/data/files/p3/s15/G4383/g1755/v335000/f1/full/changelog_base.xml

Cust: http://update.dbankcdn.com/TDS/data/files/p3/s15/G4383/g1755/v340056/f1/full/changelog_cust_hw_eu.xml

Preload:
http://update.dbankcdn.com/TDS/data/files/p3/s15/G4383/g1755/v340057/f1/full/changelog_preload_hw_eu_R1.xml

**Comment by darkfighter852** [comment]
Thanks man, il try restore now, thanks for fast answer

**Comment by ProfessorJTJ** [comment]
Anytime sir, can't wait to hear back from you.

**Comment by darkfighter852** [comment]
i got a problem, the hiSuite ask to confirm conection to hbs on phone, but i cant click anything on phone

**Comment by ProfessorJTJ** [comment]
can you show a picture of the error / alert?

**Comment by darkfighter852** [comment]
![image](https://user-images.githubusercontent.com/10888500/80754636-08c85e80-8b38-11ea-9d37-2c72347f7a23.png)

and phone is stuck at 5% instaling update

**Comment by darkfighter852** [comment]
![image](https://user-images.githubusercontent.com/10888500/80754719-2d243b00-8b38-11ea-9b93-cbac60bf2311.png)
and now ask for confirm

**Comment by ProfessorJTJ** [comment]
> ![image](https://user-images.githubusercontent.com/10888500/80754719-2d243b00-8b38-11ea-9b93-cbac60bf2311.png)
> and now ask for confirm

It's trying to connect to your device thinking its alive ( not soft bricked ), just close that alert and you'll be ready to go

I really don't know about the recovery error, wanna try this base package?
http://update.dbankcdn.com/TDS/data/files/p3/s15/G4383/g1755/v360881/f1/full/changelog_base.xml

**Comment by darkfighter852** [comment]
but if click close, it pop back up
ok, il try new base pack

**Comment by darkfighter852** [comment]
fail again, 

im going to sleep, ima try again tomorrow 

tnx for help
