### ISSUE TITLE
Unbrick CLT-L09

### ISSUE THREAD

**Issue by scastiello** [ProfessorJTJ/HISuite-Proxy#20]
Hi, 

I´m trying to unbrick (black sceen) in my Huawei P20 Pro (CLT-L09), I´m using the following links into HISuite-Proxy:

[CLT-LGRP2-OVS 10.0.0.182](http://update.dbankcdn.com/TDS/data/files/p3/s15/G5416/g1755/v456564/f1/full/changelog_base.xml)
[CLT-L09-CUST 10.0.0.5(C432)](http://update.dbankcdn.com/TDS/data/files/p3/s15/G5416/g1755/v473919/f1/full/changelog_cust_hw_eu.xml)
[CLT-L09-PRELOAD 10.0.0.3(C432R1)](http://update.dbankcdn.com/TDS/data/files/p3/s15/G5416/g1755/v329653/f1/full/changelog_preload_hw_eu_R1.xml)

Also check the following options:
- Recovery OS
- CUST PKG
- Preloaded PKG

I add the following line into HiSuiteConfig.xml inside all REGIONS (Default and China):
`<rule type="CLT-L09" cnName="HUAWEI P20 Pro" enName="CLT-L09" option="" ></rule>`

When start HiSuite everithing seems to be working but when I start Recovery process i get the following logging in HISuite-Proxy:
`HTTPS://query.hicloud.com:443/sp_dashboard_global/UrlCommand/CheckNewVersion.aspx`
`HTTP://update.hicloud.com:8180/TDS/data/files/p3/s27/G1083/g0/v468194/f1/full/filelist.xml`
`HTTP://update.hicloud.com:8180/TDS/data/files/p3/s27/G1083/g0/v468194/f1/full/HiSuiteConfig.xml`

And also HiSuite fails the the recovery with the following error message:
`The device does not support system recovery.`

Please could you help me?

**Comment by ProfessorJTJ** [comment]
"HTTP://update.hicloud.com:8180/TDS/data/files/p3/s27/G1083/g0/v468194/f1/full/HiSuiteConfig.xml"

HiSuite is replacing "HiSuiteConfig.xml" fine, go and modify that file once again...

**Comment by scastiello** [comment]
I have done it as you say but I still getting the same error. Any idea? Should be my model in the downloaded HiSuiteConfig.xml?

**Comment by scastiello** [comment]
@ProfessorJTJ Any idea? just for close the issue if not :)
