### ISSUE TITLE
Need POT-AL00/AL00a Preload C00R2 Package

### ISSUE THREAD

**Issue by CancroPlus** [ProfessorJTJ/HISuite-Proxy#201]
Hello, I have a POT-AL00a, my device's Preload package is C00R2, but The Firmfinder V2 only has POT-AL00 C00R3/4/5 on it, because of this, my device can not receive the later Harmony OS updates, so, can you find the C00R2 Preload package of POT-AL00/POT-AL00a？ thank you very much

**Comment by CancroPlus** [comment]
Firmfinder only had POT-AL00's Preload and CUP (Harmony OS 2) on it, so I used POT-AL00, but this caused my phone's version number to be missing, just like in the picture, because of this, I couldn't receive the OTA update later
![652e38318ff126470e3e0cf941f0c95](https://user-images.githubusercontent.com/70503811/164357735-7c14aba5-7a5f-4a26-9bab-e4fa52380a20.jpg)

**Comment by CancroPlus** [comment]
Could you please help me？Dear ProfessorJTJ，thank you very much

**Comment by ProfessorJTJ** [comment]
Thank you for your report, there's been a bug in our app, I've fixed the bug and it's now able to get roms for AL00a models

The new update will be online within 2 - 3 days, because I'm running a new scan.

Once again, thank you for the report.

**Comment by CancroPlus** [comment]
Thanks a lot，if it possible，i will give you a feedback after several days

**Comment by CancroPlus** [comment]
But it looks like something is wrong, I can't download the firmware of AL00a (Firmfinder V2), do I need to wait until after the next update before I can download it
![屏幕截图 2022-04-24 074620](https://user-images.githubusercontent.com/70503811/164958896-7d3e9d88-1172-49fc-b16f-225c9d2c79cd.jpg)
?

**Comment by ProfessorJTJ** [comment]
> But it looks like something is wrong, I can't download the firmware of AL00a (Firmfinder V2), do I need to wait until after the next update before I can download it ![屏幕截图 2022-04-24 074620](https://user-images.githubusercontent.com/70503811/164958896-7d3e9d88-1172-49fc-b16f-225c9d2c79cd.jpg) ?

Yes, I'm still searching for roms, it took more than expected due to some complications.

Once I update the database, I will notify you here.

**Comment by CancroPlus** [comment]
OK，Thanks a lot，I Like this project very much，so thank you again

**Comment by ProfessorJTJ** [comment]
POT-AL00A firmwares were added to the database.

Be aware if you install Harmony 2.0.0.210 over your current 2.0.0.215, your device might show error saying partition corrupted, wiping cache & data from erecovery fixes the issue.

**Comment by CancroPlus** [comment]
Thanks A lot

**Comment by CancroPlus** [comment]
I think I can fix this with Hisuite's system fix

**Comment by CancroPlus** [comment]
Thank you very much, it does not prompt partition corruption, but like a normal OTA, now its version number is complete, you can also carry out OTA, thank you very much
![6bc42060b55b5c9cd760ffdc4e118fb](https://user-images.githubusercontent.com/70503811/165006375-6e2cb917-1197-40b9-8e35-9db9334e6e98.jpg)
![1f4372174e9d38cde96a607c6848133](https://user-images.githubusercontent.com/70503811/165006385-312d9494-8bbc-4361-bd27-e78e13076ddf.jpg)

**Comment by ProfessorJTJ** [comment]
> Thank you very much, it does not prompt partition corruption, but like a normal OTA, now its version number is complete, you can also carry out OTA, thank you very much ![6bc42060b55b5c9cd760ffdc4e118fb](https://user-images.githubusercontent.com/70503811/165006375-6e2cb917-1197-40b9-8e35-9db9334e6e98.jpg)
> 
> ~ Hid the IMEI Serial

Amazing, happy to hear that.
