### ISSUE TITLE
EBG-AN10 EBG-LGRP1-CHN 102.0.0.222

### ISSUE THREAD

**Issue by weidesh** [ProfessorJTJ/HISuite-Proxy#202]
Hi, I can't find Base Software version for EBG-LGPT1-CHN 102.0.0.222 and Cust Software Version for EBG-AN10-CUST 102.0.0.200(C00)

Many Thanks

Tom

**Comment by ProfessorJTJ** [comment]
Hi you can perform harmonyos / emui 12 updates only through hisuite proxy v3, firm finder v2 and hisuite 11.0.0.610

Full guide is here
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide-V2.0

**Comment by weidesh** [comment]
![image](https://user-images.githubusercontent.com/8555253/164366905-0473a98c-492b-405c-b025-7e25c75cfea5.png)

That's what I found. There is no 102.0.0.222

**Comment by ProfessorJTJ** [comment]
> ![image](https://user-images.githubusercontent.com/8555253/164366905-0473a98c-492b-405c-b025-7e25c75cfea5.png)
> 
> That's what I found. There is no 102.0.0.222

With all due respect, you didn't take the time read the guide I sent you.

https://professorjtj.github.io/v2/

**Comment by weidesh** [comment]
> > ![image](https://user-images.githubusercontent.com/8555253/164366905-0473a98c-492b-405c-b025-7e25c75cfea5.png)
> > That's what I found. There is no 102.0.0.222
> 
> With all due respect, you didn't take the time to read the guide I sent you.
> 
> https://professorjtj.github.io/v2/

Found it. It is in the [https://professorjtj.github.io/v2/](https://professorjtj.github.io/v2/) not [https://professorjtj.github.io/](https://professorjtj.github.io/).

Thanks man.
