### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by TheBatmanandroid** [ProfessorJTJ/HISuite-Proxy#204]
Hi there,
I have windows 10.
- dissabled all windows security
- installed proxy latest version v3.0.1
- installed hisuite latest version 11.0.0.610
- started proxy, clikced setup
- started hisuite, connected my mate 20 pro to it, hisuite found emui 12 update for my phone
- clicked update
- CAN'T DOWNLOAD NO INTERNET CONNECTION
Any advices what to try? Tried to reinstall everything, same result.

**Comment by ProfessorJTJ** [comment]
When you click on setup, does hisuite proxy says connection error or all the process goes successfully?

**Comment by TheBatmanandroid** [comment]
All goes well

**Comment by TheBatmanandroid** [comment]
![hp3](https://user-images.githubusercontent.com/104299549/164981868-00a12277-66a0-4be7-8f9e-2028f895a5bd.JPG)
![hp2](https://user-images.githubusercontent.com/104299549/164981869-5256a7c6-8a97-4028-99cd-3681d39b4d4d.JPG)
![hp1](https://user-images.githubusercontent.com/104299549/164981870-b87ef5b9-87d0-4d4d-a710-270210c72520.JPG)

This time came to 50% download, then the same error again.

**Comment by ProfessorJTJ** [comment]
> ![hp3](https://user-images.githubusercontent.com/104299549/164981868-00a12277-66a0-4be7-8f9e-2028f895a5bd.JPG) ![hp2](https://user-images.githubusercontent.com/104299549/164981869-5256a7c6-8a97-4028-99cd-3681d39b4d4d.JPG) ![hp1](https://user-images.githubusercontent.com/104299549/164981870-b87ef5b9-87d0-4d4d-a710-270210c72520.JPG)
> 
> This time came to 50% download, then the same error again.

Copy the zip file link from Hisuite proxy's log box, download it manually and place it at Documents/HiSuite/Rom/romname/full

The folder will already be created, you just have to download the file to there.

**Comment by ProfessorJTJ** [comment]
> > ![hp3](https://user-images.githubusercontent.com/104299549/164981868-00a12277-66a0-4be7-8f9e-2028f895a5bd.JPG) ![hp2](https://user-images.githubusercontent.com/104299549/164981869-5256a7c6-8a97-4028-99cd-3681d39b4d4d.JPG) ![hp1](https://user-images.githubusercontent.com/104299549/164981870-b87ef5b9-87d0-4d4d-a710-270210c72520.JPG)
> > This time came to 50% download, then the same error again.
> 
> Copy the zip file link from Hisuite proxy's log box, download it manually and place it at Documents/HiSuite/Rom/romname/full
> 
> The folder will already be created, you just have to download the file to there.

Or try HiSuite Proxy V3.0.2, it's supposed to fix the internet connection issue. Thanks for the report.
I'd be thankful if you try it out.

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/3.0.2/HiSuite.Proxy.V3.0.2.rar
