### ISSUE TITLE
Usability of new firmware finder.

### ISSUE THREAD

**Issue by TheBatmanandroid** [ProfessorJTJ/HISuite-Proxy#206]
Hi there, so when i try to use old fimware finder and downgrade my p40 pro  region c432 to 131 i get failed to update error.
Then I try new firm finder, and the oldes available rom is 154
I flash 154 and try to DLOAD to 131 but now otg doesnt work :/
Is there any way to get 131 to firm finder v2?

**Comment by CancroPlus** [comment]
https://professorjtj.github.io/v2/
