### ISSUE TITLE
P40 Pro downgrade

### ISSUE THREAD

**Issue by Ruwen97** [ProfessorJTJ/HISuite-Proxy#207]
Dear sir!
My P40 Pro
The current system is 11.0.0.260.  How can I downgrade to a 10.1 system?  I use Hisuite Proxy, hisuite shows that the installation is successful, but the installation error is displayed in the recovery.
Thank you!

**Comment by badmania98** [comment]
Point 0 (zero) b and 2 [https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/post-85769677](url)

**Comment by AsimIbrahim786** [comment]
Same problem here Now i have emui 11.0.0.249(C185E6R3P3) which base file cust & preload i should for emui 10 plz help i tried lots of
