### ISSUE TITLE
How can I use dload files with Hisuite

### ISSUE THREAD

**Issue by Dead8Pixel** [ProfessorJTJ/HISuite-Proxy#209]
I have a japanese p30 pro (Ntt docomo HW-L02) ,I have the original dload firmware on my computer but I can't find how to use it on Hisuite.

PS: Firmware finder doesn't have this firmware

**Comment by badmania98** [comment]
Dload firmware/method is different than HiSuite Proxy:

https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/post-86122137
