### ISSUE TITLE
Huawei nova 7i unable downgrade to 10.0.1.167 from 10.1.0.397, after download 100% it show failed to update 

### ISSUE THREAD

**Issue by momocafe** [ProfessorJTJ/HISuite-Proxy#210]
![279628717_1431419480648297_5799190237935789989_n](https://user-images.githubusercontent.com/105088076/167231733-fa5d8734-13ec-43c0-a6a9-864829d2cefe.jpg)
![279528698_756439845373743_2206652385587321282_n](https://user-images.githubusercontent.com/105088076/167231780-c7b780b7-6ae5-42b5-96f1-dc7694f2e90a.jpg)
![279530815_996933720956473_6755793971050075112_n](https://user-images.githubusercontent.com/105088076/167231782-8988e414-dbce-48b3-aae0-0e0235287e18.jpg)
I am sure that the base, cust and preload software is right region and right model

**Comment by ProfessorJTJ** [comment]
huawei blocks the installation inside your phone purposefully.
