### ISSUE TITLE
P40 Pro+ downgrade

### ISSUE THREAD

**Issue by Ruwen97** [ProfessorJTJ/HISuite-Proxy#212]
Dear sir

Last month, I have a ELS-N39 c432 using the official hisuite from emui12.0.0.232 fall back 11.0.0.232 and then fall back to 10.1.0.137 proxy by Hisuite success.  And super fast charge is not lost.  Why me yesterday another one ELS-N39 in the same way super fast charge is lost?  After the fallback system to 10.1.0.137

**Comment by ProfessorJTJ** [comment]
Unrelated to hisuite proxy, probably the firmwares installed on your phone are different from the ones on the other person.
