### ISSUE TITLE
P40 pro not downgrade to emui 10 from 11

### ISSUE THREAD

**Issue by AsimIbrahim786** [ProfessorJTJ/HISuite-Proxy#213]
P40 pro not downgrade to emui 10 from 11
i have emui 11.0.0.249(C185E6R3P3)
P40 pro plz help

**Comment by AsimIbrahim786** [comment]
I have tried every thing on YouTube but failed

**Comment by ProfessorJTJ** [comment]
Your phone blocks the downgrade, huawei has added that recently on the new roms so people cannot downgrade to vulnerable versions.

**Comment by AsimIbrahim786** [comment]
Thanks for reply

Is there any new method available fot this
