### ISSUE TITLE
P40 lite downgrade JNY-L21

### ISSUE THREAD

**Issue by Bobbimus** [ProfessorJTJ/HISuite-Proxy#215]
Hi i tried to downgrade from 10.1.0.399 to 10.0.1.167. (with cust and preload, rollback os ticked) Using Hisuite 10.1.0.550. The downgrade fails after reboot. The phone shows Software install failed. Same for 10.1.0.206....

**Comment by Kiphleee** [comment]
I have the same problem

**Comment by Bobbimus** [comment]
I solved my problem as mentioned here:
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/page-71
If you have questions remaining go ahead!

**Comment by PWL-YT** [comment]
Where did you got the firmware?
And at the end, did you used dload or Hisuite Proxy for the second downgrade?

**Comment by Bobbimus** [comment]
First i used original hisuite and came to 10.1.0.399 then i used dload  10.1.0.364(C432E1R6P1) 
then i used  that with HiSuite Proxy to 10.0.1.136 (Rollback os ticked, Preload cust included).
You can find the links for firmware and a dload tutorial here:
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/

**Comment by PWL-YT** [comment]
I couldn't find any link to download the dload firmware. Can you share me a page where I can get it? Thanks.

**Comment by Bobbimus** [comment]
dload tutorial:
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/page-13#post-86122137 
according to the other threat you made you should be at the same point where i startet so follow the procedure described on page 71 (Huzalio asked):
https://forum.xda-developers.com/t/badmania98-huawei-p40-lite-pro-plus-guides-news-discussion-support.4346741/page-71

**Comment by Bobbimus** [comment]
I think why you cant downgrade directly right now is because huawei blocked it. So you have to flash a firmeware with dload first where a downgrade isnt blocked. As what i understood the hisuite proxy firmewares are certified and the dload not this is also why you cant use dload files with hisuite proxy.

**Comment by PWL-YT** [comment]
Hi I have successfully downgraded to 10.1.0.364 with dload, now I need to use hisuite proxy but my JNY-L21 has region C432R6 but I can't find any preload firm for R6 for 10.0.1.x. Should I use dload again? Or which preload should I use? Thanks a lot for resolving all my issues.

**Comment by ProfessorJTJ** [comment]
> Hi I have successfully downgraded to 10.1.0.364 with dload, now I need to use hisuite proxy but my JNY-L21 has region C432R6 but I can't find any preload firm for R6 for 10.0.1.x. Should I use dload again? Or which preload should I use? Thanks a lot for resolving all my issues.

Installing any R version is fine.
