### ISSUE TITLE
P40 lite (JNY-L21) Software install failed

### ISSUE THREAD

**Issue by PWL-YT** [ProfessorJTJ/HISuite-Proxy#216]
Greetings,
I would like to install GMS into my P40 lite with Googlefier.

I'm at 10.1.0.399

So I tried 8 or 9 times to downgrade, almost every time to 10.1.0.226, it starts fine, no errors in HiSuite itself, The problem starts when the phone reboots, it tries to verify it for about 15 seconds, then it shows a big red warning with the title "Software install failed" with a description telling that you can get help from a page:
http://www.emui.com/emotiondownload.php?mod=restore

And that webpage is down or no longer exists, I had to describe as of right now I do not have available a second camera to take a photo.

I tried older versions but result is the same.

What's going on?
Any response would be appreciated.
I have attached more details of my version below.

Kind regards. 

![Screenshot_20220524_202619](https://user-images.githubusercontent.com/64767383/170285276-73400dd8-1518-47ba-9392-1f9c2e0498fa.jpg)

**Comment by PWL-YT** [comment]
More details about my version.
![Screenshot_20220524_202619](https://user-images.githubusercontent.com/64767383/170173464-079b695d-6065-4467-8e66-9e6596874df6.jpg)

**Comment by PWL-YT** [comment]
This is the error
![image](https://user-images.githubusercontent.com/64767383/170346641-f994dfe6-77a9-4d9f-912d-922ae36d859a.jpg)

**Comment by Kiphleee** [comment]
I'm facing the same issue.

**Comment by ProfessorJTJ** [comment]
Huawei purposefully blocks the downgrade on your phone to prevent the installation of old vulnerable firmwares. 
There's no general / known solution for this. trying random old firmwares or dloads sometimes works. unrelated to hisuite proxy.
