### ISSUE TITLE
P40 pro USB problem

### ISSUE THREAD

**Issue by xonecomming** [ProfessorJTJ/HISuite-Proxy#217]
I have downgraded the phone from the 12 all the way to 10.1.154 and now i can use USB only for charging, my computer doesn't acknowledge the phone and on my phone it just charges, I've tried to see if i could connect my phone to the USB but that doesn't work either, any suggestions?

**Comment by ProfessorJTJ** [comment]
Upgrade to latest emui or get harmonytp cable

https://gsmserver.com/harmony-tp-cable/
