### ISSUE TITLE
Huawei p30 mistake

### ISSUE THREAD

**Issue by hayder26** [ProfessorJTJ/HISuite-Proxy#219]
![image](https://user-images.githubusercontent.com/106449892/170840426-f8e9508b-0667-4b2f-9f0b-c43b429d55c4.png)
 I get this error, you know what it is due to (I have a p30 ELE-L04 C25E14R1P3 but I changed the rom and it looks like an ELE-L29 C431 that appears when I dial this code on the phone *#*#2846579#*#*. I want to update to emui 12 can you help me?

**Comment by ProfessorJTJ** [comment]
You're using an unsupported versions of hisuite. use HiSuite 10.1 or 11.0.0.610
