### ISSUE TITLE
Update problem.

### ISSUE THREAD

**Issue by Alello23** [ProfessorJTJ/HISuite-Proxy#222]
Hello, I have a problem and it is that I have changed the version of my huawei p40 5g mobile from emui 12 to emui 10 version. And when I want to update to emui from settings/ota it doesn't detect any type of update and when I connect it with a usb cable to the pc I don't get the menu to choose file transfer only upload. help? I'm stuck on the version 10.1.0.182.
![image](https://user-images.githubusercontent.com/94875104/179632665-8328fc10-1993-4696-a5ae-4505c4f2c65f.png)

**Comment by ProfessorJTJ** [comment]
```diff
- ALERT : Downgrading from Latest EMUI 11 disables your phone's Fast Charging, Fastboot, USB Connection and TestPoint.
- The only way to fix it is updating through OTA, Erecovery or Dload by memorycard to latest EMUI 11. 
```

You could also get this cable it fixes the usb connection, then upgrade using hisuite proxy.

https://gsmserver.com/harmony-tp-cable/
