### ISSUE TITLE
offline packages disabled

### ISSUE THREAD

**Issue by AminTun** [ProfessorJTJ/HISuite-Proxy#223]
(version 3.3.0)
offline packages options are disabled & Hisuite-proxy is detected as virus by windows defender on win 11

**Comment by ProfessorJTJ** [comment]
> (version 3.3.0) offline packages options are disabled & Hisuite-proxy is detected as virus by windows defender on win 11

Older versions of hisuite are not detected as virus?

**Comment by AminTun** [comment]
2.4.0.0 was not signaled as virus but 3.1.3 yes

**Comment by ProfessorJTJ** [comment]
> 2.4.0.0 was not signaled as virus but 3.1.3 yes

Please check this version, see if it throws virus warning too.

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/3.3.0/HiSuite.Proxy.V3.3.0.zip

**Comment by ProfessorJTJ** [comment]
Also if you want to skip the download of a firmware, download the zip files are place them at:

Documents/HiSuite/Rom/romname/full
