### ISSUE TITLE
Group version not match Honor 10 lite

### ISSUE THREAD

**Issue by barrios2010** [ProfessorJTJ/HISuite-Proxy#27]
I have an honor 10 lite HRY-LGRP2 Current version 10.0.0.250 and the program is giving me issues while downgrading. It shows "group version not match" when I try to downgrade from EMIUI 10 to EMIUI 9. Switching between different versions of EMIUIE 10 WORKS FINE, but I need to downgrade some apps don't work well in EMIUI 10 and do not know how to bypass this error message. Any help will be appreciated.  
![image](https://user-images.githubusercontent.com/76451226/102815150-e8d0fe00-4399-11eb-98ef-e59a465275c5.png)

**Comment by applefi87** [comment]
I'd heard downgrade EMUI verson likes 11 to 10 is not working for proxy way.
Is hisuit offer your phone a rollback way?   choose update ,and there will have a "other version" blue buttom.
If not, how about  try downgrade way? At least the offical downgrade EMUI is with this way. The proxy app have a roll-back way.  I can't find the post I've seen . you could try to find in xda.

**Comment by ProfessorJTJ** [comment]
You need three packages to rollback. 
Base, CUST and preload.
And you will endup braking your phone, don't do it...

**Comment by barrios2010** [comment]
> I'd heard downgrade EMUI verson likes 11 to 10 is not working for proxy way.
> Is hisuit offer your phone a rollback way? choose update ,and there will have a "other version" blue buttom.
> If not, how about try downgrade way? At least the offical downgrade EMUI is with this way. The proxy app have a roll-back way. I can't find the post I've seen . you could try to find in xda.

Thanks for your reply, however Hisuite is not giving that option to change current version, I used it  some time ago but now it is gone.

**Comment by barrios2010** [comment]
> You need three packages to rollback.
> Base, CUST and preload.
> And you will endup braking your phone, don't do it...

So I'm stuck at emiui 10 ? So sad. I think I will switch to xiaomi or samsung.

**Comment by ndresever** [comment]
Телефон P40 Pro. Но у остальных схема та же
Оказалось, что при этой ошибке нужно дополнительно ставить CUST PKG и Preload PKG в Hisuite Proxy. Найти их можно также в Firmware Finder. Но вместо индекса ELS-LGRP4_OVS будет  индекс ELS_N29_CUST(есть в настройках) или ELS_N29_PRELOAD. Находим последние версии, вносим в Hisuite Proxy и ставим галочки Cust и Preload. После обновляем
