### ISSUE TITLE
mate 30 pro group not match 

### ISSUE THREAD

**Issue by COLOMBIANBOY** [ProfessorJTJ/HISuite-Proxy#28]
I want to update my matte 30 pro to emui 11, but when using hisuite proxy an alert comes out, group version does not match

http://update.dbankcdn.com/TDS/data/files/p3/s15/G6123/g1755/v501760/f1/full//update_full_base.zip

**Comment by daniele1965** [comment]
stesso problema con huawei p40 pro hai risolto ??

**Comment by COLOMBIANBOY** [comment]
mi problema no se como solucionarlo

**Comment by ndresever** [comment]
Телефон P40 Pro. Но у остальных схема та же
Оказалось, что при этой ошибке нужно дополнительно ставить CUST PKG и Preload PKG в Hisuite Proxy. Найти их можно также в Firmware Finder. Но вместо индекса ELS-LGRP4_OVS будет  индекс ELS_N29_CUST(есть в настройках) или ELS_N29_PRELOAD. Находим последние версии, вносим в Hisuite Proxy и ставим галочки Cust и Preload. После обновляем
