### ISSUE TITLE
huawei p40 pro ??

### ISSUE THREAD

**Issue by daniele1965** [ProfessorJTJ/HISuite-Proxy#29]
non mi lascia aggiornare alla versione 11.0.0.153 che e approvato dicendomi
Gruop no device match
come posso fare ???

**Comment by fiordiconio** [comment]
Try to check "CUST PKG" and "preloaded PKG"

**Comment by ndresever** [comment]
Телефон P40 Pro. Но у остальных схема та же
Оказалось, что при этой ошибке нужно дополнительно ставить CUST PKG и Preload PKG в Hisuite Proxy. Найти их можно также в Firmware Finder. Но вместо индекса ELS-LGRP4_OVS будет  индекс ELS_N29_CUST(есть в настройках) или ELS_N29_PRELOAD. Находим последние версии, вносим в Hisuite Proxy и ставим галочки Cust и Preload. После обновляем
