### ISSUE TITLE
Problem Brick

### ISSUE THREAD

**Issue by DukeReyzio** [ProfessorJTJ/HISuite-Proxy#3]
Hello 
My brick phone and I don't understand your tutorial to get out of it. Please Help Me

**Comment by ProfessorJTJ** [comment]
Please mentions the steps you went through and where you're struggling so I can elaborate further.

**Comment by DukeReyzio** [comment]
I do not understand how to edit the xml file for my model the Huawei P20 EML-L09. Please help me

**Comment by ProfessorJTJ** [comment]
> I do not understand how to edit the xml file for my model the Huawei P20 EML-L09. Please help me

https://pastebin.com/AzEKmyza

also be sure the file doesn't get over written ( happens once sometimes, just gotta replace it once again )

**Comment by DukeReyzio** [comment]
It does not work...
![hisuite](https://user-images.githubusercontent.com/65232464/84514380-3b36b100-accb-11ea-802b-a45669b2896d.png)

**Comment by ProfessorJTJ** [comment]
> It does not work...
> ![hisuite](https://user-images.githubusercontent.com/65232464/84514380-3b36b100-accb-11ea-802b-a45669b2896d.png)

Switch it to English kindly. 
Did you connect hisuite to hisuite proxy by setting proxy settings in Hisuite?
Did you choose System recovery in Hisuite and set proper firms?

**Comment by DukeReyzio** [comment]
sorry ... yes i did everything
