### ISSUE TITLE
hisuite proxy not connecting with hisuite

### ISSUE THREAD

**Issue by johnsmith0123** [ProfessorJTJ/HISuite-Proxy#32]
I am having problem with Hisuite connection when using the HIsuite proxy. 

Hisuite says No Internet connection, Please check your network settings. In setting have Custom Proxy 1270.0.1 port 7777 and everything else blank.
I start the Proxy first then HIsuite then the Phone. Disable My internet security also unable and any other programs related to internet. running or disable. 

I am on Windows 10 Enterprise edition. Hisuite and HIsuite proxy are the newer version all updated

Either windows is blocking it or something is blocking it
I have tried 
Start > cmd > run as administrator

netsh advfirewall set allprofiles state off

still not connecting.

Many thanks

![proxy2](https://user-images.githubusercontent.com/77831316/105471575-c8df7380-5c92-11eb-9380-987c86ab33e1.png)
![proxy1](https://user-images.githubusercontent.com/77831316/105471590-cf6deb00-5c92-11eb-93d1-ae0d713fa4a0.png)

**Comment by saadzer** [comment]
Hello, 
I believe it's working only with Hisuite v10 I've had the same error on the latest version 11 and installed an earlier version 10 and it works as it should.

**Comment by johnsmith0123** [comment]
where can i get V10 as can't find V10 anywhere?
Can you upload it and let me have the link please

many thanks

**Comment by johnsmith0123** [comment]
Downloaded V10 still not working as it's saying I am upto date showing right firmware 176 want to downgrade to 130 or Lower. Looks like it's by passing proxy

There must be a fix somewhere
