### ISSUE TITLE
issue with hisuite proxy instalation

### ISSUE THREAD

**Issue by al2603** [ProfessorJTJ/HISuite-Proxy#35]
hi everyone.

yesterday i tried to install hisuite proxy, when i press install button and a started instalation, but, the installer changed green letters to red marking error "patch failed, aborting in process". i tried again and the result is the same, i upload some pictures of program.

help me pls

![falla 2](https://user-images.githubusercontent.com/78658143/107125936-4f3eac80-6872-11eb-8b4b-2c41c8a1a21a.png)

![falla](https://user-images.githubusercontent.com/78658143/107125759-48fc0080-6871-11eb-9c7e-1252cbf5866e.png)

**Comment by al2603** [comment]
aditional facts.
i use windows 7 and i recently made update of hisuite to version 11.0.0.500_OVE

**Comment by ProfessorJTJ** [comment]
Use HiSuite v10

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/1.8.8/HiSuite_10.0.1.100_OVE.zip

**Comment by hzokdj** [comment]
HiSuite_10.1.0.550_OVE
 OK
