### ISSUE TITLE
Slowness when downloading firmware

### ISSUE THREAD

**Issue by Danielsilva00** [ProfessorJTJ/HISuite-Proxy#36]
It has taken hours, many hours to downgrade the p40 pro, please see this, I have a very good PC and net but it takes a lot.

**Comment by ProfessorJTJ** [comment]
> It has taken hours, many hours to downgrade the p40 pro, please see this, I have a very good PC and net but it takes a lot.

Go in the documents, open HiSuite folder, you'll see the firmware being downloaded there in a folder, download the zip manually and put it there, HiSuite will skip the download for you

**Comment by Danielsilva00** [comment]
> > Demorou horas, muitas horas para fazer o downgrade do p40 pro, por favor, veja isso, eu tenho um PC e uma rede muito bons, mas é muito demorado.
> 
> Entre nos documentos, abra a pasta HiSuite, você verá o firmware sendo baixado lá em uma pasta, baixe o zip manualmente e coloque lá, o HiSuite irá pular o download para você

But it's not normal to take that long, today it's taking hours, it's already taken 30 minutes, 1h but not all day

**Comment by Danielsilva00** [comment]
> > > Demorou horas, muitas horas para fazer o downgrade do p40 pro, por favor, veja isso, eu tenho um PC e uma rede muito bons, mas é muito demorado.
> > 
> > 
> > Entre nos documentos, abra a pasta HiSuite, você verá o firmware sendo baixado lá em uma pasta, baixe o zip manualmente e coloque lá, o HiSuite irá pular o download para você
> 
> Mas não é normal demorar tanto, hoje está demorando horas, já demorou 30 minutos, 1h mas não o dia todo

And a lot of people have also been saying that the proxy hisuite is not working, I've had to do and it has to do with the Windows firewall.. But also the delay in downgrading even already with the downloaded file, it has not passed that phase..

**Comment by Danielsilva00** [comment]
It's not working, it takes hours and then it starts and the computer restarts, and it didn't before, please look at this.

**Comment by Danielsilva00** [comment]
Apparently it's settled, it's faster to download.
