### ISSUE TITLE
Does not connect to hisuite 

### ISSUE THREAD

**Issue by Danielsilva00** [ProfessorJTJ/HISuite-Proxy#37]
Even with the right hisuite version, with the firewall Off, everything, the hisuite will not seek the update, Says that already has the latest version installed. Please check this out

**Comment by ProfessorJTJ** [comment]
Firewall has to be off, click on the "SETUP" button, does it show any errors?
If no errors in setup section, run the app as admin and try again

**Comment by Danielsilva00** [comment]
It does not give any error, but the hisuite does not assume the update, the firewall is configured well, but does not give

**Comment by hzokdj** [comment]
Remote server problems

**Comment by Danielsilva00** [comment]
> O Firewall tem que estar desligado, clique no botão "CONFIGURAR", mostra algum erro?
> Se não houver erros na seção de configuração, execute o aplicativo como administrador e tente novamente

Any solution?
