### ISSUE TITLE
Does not Appears the update 

### ISSUE THREAD

**Issue by Danielsilva00** [ProfessorJTJ/HISuite-Proxy#38]
Even with the right hisuite version, with the firewall Off, everything, the hisuite will not seek the update, Says that already has the latest version installed. Please check this out
It does not give any error when clicking setup,  but the hisuite does not assume the update, the firewall is configured well, but does not give

**Comment by wwangchaohui** [comment]
i had same problem ,   i think it caused by  https://pro-teammt.ru/en/online-firmware-database/  server

**Comment by Danielsilva00** [comment]
The server of the firmwaresite is very low, just waiting even
