### ISSUE TITLE
help for how to use offline packages?

### ISSUE THREAD

**Issue by caiabc2021** [ProfessorJTJ/HISuite-Proxy#39]
i have download rom and save to my local disk.
then i want to use offline pkg method to upgrade my huawei phone

1. run hisuiteproxy(2021.3.26 version)
2. set pkg ,cust pkg,base pkg.then i found pkgs be copy to hisuite ROM directory.
3. run hisuite,connect my phone,check firmware, found new rom just my local pkg ,look ok?
4. but,after i click upgrade,run, then hang at download begin side,very very long time. nothing run?
5. i don’t known which step may i make some mistake?
 

- [ ] #

**Comment by ProfessorJTJ** [comment]
Take a screenshot from the application or copy paste the debug logs,
it usually takes a few minutes to verify the packages ( it checks their SHA256 and MD5 checksums )
Don't see any reason why it would hang

**Comment by caiabc2021** [comment]
[
![IMG_2393](https://user-images.githubusercontent.com/81454761/112717641-05e11400-8f29-11eb-87df-dcad1278f028.png)

![IMG_2394](https://user-images.githubusercontent.com/81454761/112717627-f9f55200-8f28-11eb-943a-b60a7b9c522e.png)
](url)

![IMG_2395](https://user-images.githubusercontent.com/81454761/112717649-11343f80-8f29-11eb-990f-4a6bdb255bdc.png)
![IMG_2396](https://user-images.githubusercontent.com/81454761/112717655-172a2080-8f29-11eb-9446-986702c9a4f2.png)
![IMG_2397](https://user-images.githubusercontent.com/81454761/112717660-2315e280-8f29-11eb-8717-3bdf749f04aa.png)
![IMG_2398](https://user-images.githubusercontent.com/81454761/112717666-2d37e100-8f29-11eb-8cec-cba3209a58ee.png)
![IMG_2399](https://user-images.githubusercontent.com/81454761/112717683-40e34780-8f29-11eb-8546-7837611412e1.png)
![IMG_2400](https://user-images.githubusercontent.com/81454761/112717696-4e98cd00-8f29-11eb-8133-a8eaabd31674.png)

![IMG_2401](https://user-images.githubusercontent.com/81454761/112717712-64a68d80-8f29-11eb-892d-a984bb9780ea.png)

**Comment by caiabc2021** [comment]
wait for about one hour,nothing happen!
nothing disk i/o or cpu busy.

**Comment by caiabc2021** [comment]
[
[Desktop.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6215756/Desktop.zip)

](url)

this is logfile from hiproxy and hisuite

**Comment by caiabc2021** [comment]
i think maybe something change need with hisuite dll for offline pkg?
when i click upgrade button at hisute,i found hisuite send nothing to hisuiteproxy, so problem may be not at hisuiteproxy.

**Comment by caiabc2021** [comment]
Regarding the hang problem, I guess whether it is caused by filelist.xml?
This is the content sent by hisuiteproxy proxy：
=======================

![20210331130901](https://user-images.githubusercontent.com/81454761/113093524-a766af00-9222-11eb-828d-0ad56f2e4ef1.png)

===================

The following is the filelist.xml content of Huawei's original package. There are some differences between the two. I wonder if these differences cause the hang?

====================
![20210331130921](https://user-images.githubusercontent.com/81454761/113093539-b0f01700-9222-11eb-88b5-bb3b31f06bfe.png)

**Comment by ProfessorJTJ** [comment]
Finally fixed the "stuck/hang".
it was because HISuite proxy generated the "filelist.xml" file with "<vendor**i**nfo ...." instead of "<vendor**I**nfo ...." ( i -> I )...

Thanks for the report!
