### ISSUE TITLE
maybe some bug at make checksum？

### ISSUE THREAD

**Issue by caiabc2021** [ProfessorJTJ/HISuite-Proxy#40]
offline pkg -->set pkg - preloadpkg with the following zip file，report error then failed.

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/ee/v3/638730ded84b42999e4b04364d301315/full/update_full_preload_LYA-AL00L_all_cn_R2.zip

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/ee/v3/638730ded84b42999e4b04364d301315/full/filelist.xml

**Comment by caiabc2021** [comment]
![20210331004539](https://user-images.githubusercontent.com/81454761/113025439-8a969100-91ba-11eb-8323-d136bee6244d.png)

**Comment by caiabc2021** [comment]
Sorry, you misunderstood my needs!
I want to use the offline ROM package to install, so I have downloaded the offline installation package and stored it on my local disk. As shown below：
![1](https://user-images.githubusercontent.com/81454761/113086778-ec83e480-9214-11eb-947f-28418ef5668c.jpg)


Here, there are three installation packages. They are:
1. TAS-LGRP3-CHN 10.1.0.160, the installation package is update_full_base.zip.
2. TAS-AN00-CUST 10.1.0.155(C00), the installation package is update_full_cust_TAS-AN00_all_cn.zip.
3. TAS-AN00-PRELOAD 10.0.0.2 (C00R6), the installation package is update_full_preload_TAS-AN00_all_cn_R6.zip. 

Then, I started hissuiteproxy and clicked set PKG to the right of Base PKG in the offline packages box, as shown below:
![2](https://user-images.githubusercontent.com/81454761/113087374-112c8c00-9216-11eb-9605-d3171dc8185f.jpg)

Then, I found the base installation package in the file selection dialog as shown below: 
![3](https://user-images.githubusercontent.com/81454761/113087641-a9c30c00-9216-11eb-8692-eaa2f1448142.jpg)

Then, read update_full_base.zip and copy it to ROM, as shown below:
![2021-03-31 11_45_16-](https://user-images.githubusercontent.com/81454761/113087755-e1ca4f00-9216-11eb-8b73-ecfede86b25e.png)

As a result, I saw the following picture, and the firmware version number was already displayed under the base pkg. The packages name has also been grayed out. It indicates that the firmware package update_full_base.zip has been successfully read.
![4](https://user-images.githubusercontent.com/81454761/113088138-9c5a5180-9217-11eb-9b8b-89a4a3f651b2.jpg)

At the same time, the firmware package has been copied to the ROM directory, as shown below:
![2021-03-31 11_53_09-full](https://user-images.githubusercontent.com/81454761/113088288-e17e8380-9217-11eb-9c91-91b9eed6286e.png)

Then, I used the same steps to successfully read the offline package cust pkg (update_full_cust_TAS-AN00_all_cn.zip).

Then, I used the same steps to open the offline package preload pkg. However, after selecting update_full_preload_TAS-AN00_all_cn_R6.zip, after reading it for a while, I reported an error as shown in the figure below, which made it impossible to successfully read the preload pkg offline.
![2021-03-31 12_00_35-HISuite Proxy](https://user-images.githubusercontent.com/81454761/113088827-fb6c9600-9218-11eb-969d-5b2deb67b5a3.png)

The Chinese in the error box is: arithmetic operation caused overflow.

**Comment by ProfessorJTJ** [comment]
Well, you won't succeed in installting that rom, unless you know its "Romid",
you cannot install the rom by only using its ZIP package, you need its ID too.
( soon your firms will be on http://firmfinder.ml

**Comment by ProfessorJTJ** [comment]
Download Latest HISuite Proxy https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.1/HISuite.Proxy.rar

BASE - TAS-LGRP3-CHN 10.1.0.160 - 478584:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/b3/v3/c55e1718484b41b691f977d0d28c20d7/full/filelist.xml

CUST - TAS-AN00-CUST 10.1.0.155(C00) - 441166:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/a5/v3/2f49f4806b4244dcb878c7cd9ab999c5/full/filelist.xml

PRELOAD - TAS-AN00-PRELOAD 10.0.0.2(C00R7) - 367045:
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/a5/v3/56b454f7e7fb425292b5ee46b00ae881/full/filelist.xml


**NOTE:** The preload you were using is for LYA ( LYA-AL00L-PRELOAD 10.0.0 ), be happy the process didn't succeed, otherwise your phone would of soft bricked...

![Capture 6](https://user-images.githubusercontent.com/49002275/113113397-85b7f880-921f-11eb-851a-ee3354443e57.PNG)

**Comment by ProfessorJTJ** [comment]
Fixed the error, thanks for the report.

![Capture 7](https://user-images.githubusercontent.com/49002275/113114397-8b620e00-9220-11eb-98bf-b9b020fd6381.PNG)

**Comment by caiabc2021** [comment]
> Well, you won't succeed in installting that rom, unless you know its "Romid",
> you cannot install the rom by only using its ZIP package, you need its ID too.

First of all, thank you very much for your reply! I want to ask one more question. Why is this ROMID not needed when restoring the phone before, but now it is needed?

**Comment by caiabc2021** [comment]
> **NOTE:** The preload you were using is for LYA ( LYA-AL00L-PRELOAD 10.0.0 ), be happy the process didn't succeed, otherwise your phone would of soft bricked...

Thank you for reminding me seriously. Actually, because I have two mobile phones, one is lya-al00 and the other is tas-an00, so the firmware of both of my mobile phones will be downloaded. When trying the offline mode of preload firmware, both lya-al00 or tas-an00 encountered the problem "arithmetic operation caused overflow." So today's handy example does not seem to match.

**Comment by ProfessorJTJ** [comment]
> > Well, you won't succeed in installting that rom, unless you know its "Romid",
> > you cannot install the rom by only using its ZIP package, you need its ID too.
> 
> First of all, thank you very much for your reply! I want to ask one more question. Why is this ROMID not needed when restoring the phone before, but now it is needed?

It was included in the URL, look:

"http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/**_v386379_**/f1/"
-> /v386379/

but with the new URL links, version ids are not longer in the URL, you have to enter them manually...

**Comment by caiabc2021** [comment]
thank you very much! I have successfully restored the old firmware for the first time.
Looking back, the previous failure was mainly due to not filling in the ROMID.
