### ISSUE TITLE
About the correct use of offline mode

### ISSUE THREAD

**Issue by caiabc2021** [ProfessorJTJ/HISuite-Proxy#43]
Please explain what is the difference between the place marked (1) and the place marked (2) when using the offline package method? And how to use offline package mode correctly.
By the way, it is recommended to increase the width of marked(3) so that the complete content can be displayed.
Thank you!

![333](https://user-images.githubusercontent.com/81454761/113322935-e8a4af00-9347-11eb-82c8-6543215d02e6.jpg)

**Comment by ProfessorJTJ** [comment]
Section 1, only copies the zip file, skipping the download but if you use an old rom, which you have, with old link of it, it will not work. 

2. Copies the zip file and generates filelist.xml and changelog.xml for it, so even if you pass invalid ( 404 not found ) link for it, with the correct ROM ID, it will still work...
3.
I'll look into 3 👍🏻

**Comment by caiabc2021** [comment]
Hello, I have encountered a new problem, which is difficult to solve by myself, please help!

For my mobile phone tas-an00, I want to restore the firmware TAS-LGRP3-CHN 10.0.0.133, but I cannot find the corresponding download link from http://firmfinder.ml/.

I obtained from a friend the update_full_base.zip file corresponding to the base package he saved before. Then I thought of using your offline mode installation. That is, the method (2) in the above figure.

![222](https://user-images.githubusercontent.com/81454761/113472894-a8a11180-9498-11eb-92d8-3e33c2c51f3d.jpg)


Then, I click (1) the corresponding setpkg to open the update_base.zip file I saved locally. Next, the file is read. However, after a while, an error is reported as shown in (2), and as a result, offline mode cannot be used anymore.

I tried to read other versions of update_base.zip with setpkg, and the result is that some files can be successful, some cannot be successful. Take the following file as an example, it cannot be successful:

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/13/v3/7bd8aed8ac3a4777a90c10029da22674/full/update_full_base.zip

**Comment by caiabc2021** [comment]
In other words, I already have update_full_base.zip and the corresponding ROMID, how can I restore the firmware to the phone?

**Comment by ProfessorJTJ** [comment]
The application is failing to read the zip file, it could be corrupted, can you extract the zip using winrar or any other software?

**Comment by caiabc2021** [comment]
I can successfully decompress the update_full_base.zip file.

**Comment by ProfessorJTJ** [comment]
> I can successfully decompress the update_full_base.zip file.
> 
> ![20210403180458](https://user-images.githubusercontent.com/81454761/113475287-3c79da00-94a7-11eb-9af8-93758d7ce475.png)
> ![20210403180624](https://user-images.githubusercontent.com/81454761/113475297-53203100-94a7-11eb-8c13-8b503feca3aa.png)

I used a ready zip library to open the zip files, apparently it's failing, I'll try using another, more modern/updated one and I will make a pre-release for you to test.

**Comment by caiabc2021** [comment]
Did you open the zip package to generate md5 and sha256 verification codes?
Can you consider calling the ready-made commands of win10 directly to complete the verification code?
certutil -hashfile update_full_base.zip md5
certutil -hashfile update_full_base.zip sha256

**Comment by ProfessorJTJ** [comment]
> Did you open the zip package to generate md5 and sha256 verification codes?
> Can you consider calling the ready-made commands of win10 directly to complete the verification code?
> certutil -hashfile update_full_base.zip md5
> certutil -hashfile update_full_base.zip sha256

The app opens it to load the "VERSION" file which contains the rom name...

**Comment by caiabc2021** [comment]
I still hope to be able to use the offline package to flash the firmware.

I tried to load the offline package correctly by clicking (1) as shown in the figure below. Then, fill in the correct url link in the packages url, at this time, you can get the upgrade normally.

![offline](https://user-images.githubusercontent.com/81454761/113496547-46deb700-952d-11eb-93f5-b3b4245e9d0d.jpg)

But, I think, since I use the offline package method, I should be able to get rid of the Internet, so I deliberately changed the URL at (2). As a result, the upgrade package cannot be found.

In this case, if I already have an offline package, but can't get the corresponding URL address on Huawei's firmware server, I still can't really realize offline upgrade?

**Comment by mariuszo73** [comment]
> ![222](https://user-images.githubusercontent.com/81454761/113472894-a8a11180-9498-11eb-92d8-3e33c2c51f3d.jpg)
Can confirm offline package error :)

**Comment by caiabc2021** [comment]
The latest attempt found that if I want to use offline packages as the firmware, I must fill in the old format url instead of the new format, and fill in the ROMID as the url content. In doing so, hissuiteproxy will no longer download filelist.xml and change_base_log.xml files from the Internet.

I have also tried, in order to avoid the insufficiency of hissuiteproxy not being able to read part of the firmware package correctly, I used 7zip to decompress the firmware package and recompress it. After that, hissuiteproxy can read the offline package correctly, and then hissuite can successfully transfer the firmware to the mobile phone. However, after the phone restarts, an error will be reported when verifying the firmware, and the upgrade cannot be smoothly performed. In other words, if the firmware is manually repackaged, it cannot be installed successfully.

**Comment by ProfessorJTJ** [comment]
Please try this version, see if it throw error when you select the zip package.

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.2/HISuite.Proxy.rar

**Comment by mariuszo73** [comment]
I've tested v2.3.2 but this one "does nothing" when you are choosing offline packages (all: base, cust and preload).

To be sure i copied:
- update_sd_base
- update_sd_cust_EML-L29_hw_eu
- update_sd_preload_EML-L29_hw_eu_R1
to main folder of my C:\ drive
Files are extracted with latest WinRAR from: Huawei P20 EML-L29 hw eu Emily-L29C 10.0.0.171(C432E5R1P3) Firmware EMUI10.0.0 05015AQB

Unpacked both HISuite.Proxy.rar versions (2.3.1 and 2.3.2) to separate folders (HSP2310 and HSP2320 respectively) also to C:\
Version 2.3.1 shows "Wrong local header signature" error
Version 2.3.2 -  basically nothing is happening when you pointing a file (s). Tried all possible variants and combinations of HISuite.Proxy options. Even typed full local file paths into packages URL fields :)

**Comment by caiabc2021** [comment]
For the version you gave, I have tested all the multiple zip packages I have downloaded, and they can all be read successfully. I also used the offline package method to successfully restore my phone to the old version of the firmware, indicating that the offline package function is completely normal, and it does not need to be connected to the Internet.

Thank you very much for your tool to help me restore the old firmware, and thank you very much for your patient guidance.

**Comment by ProfessorJTJ** [comment]
> I've tested v2.3.2 but this one "does nothing" when you are choosing offline packages (all: base, cust and preload).
> 
> To be sure i copied:
> 
> * update_sd_base
> * update_sd_cust_EML-L29_hw_eu
> * update_sd_preload_EML-L29_hw_eu_R1
>   to main folder of my C:\ drive
>   Files are extracted with latest WinRAR from: Huawei P20 EML-L29 hw eu Emily-L29C 10.0.0.171(C432E5R1P3) Firmware EMUI10.0.0 05015AQB
> 
> Unpacked both HISuite.Proxy.rar versions (2.3.1 and 2.3.2) to separate folders (HSP2310 and HSP2320 respectively) also to C:
> Version 2.3.1 shows "Wrong local header signature" error
> Version 2.3.2 - basically nothing is happening when you pointing a file (s). Tried all possible variants and combinations of HISuite.Proxy options. Even typed full local file paths into packages URL fields :)

update_sd_base
"SD"
Apparently your package is dload, you can install that by USB OTG or SDCard, it wipes all your data, HISuite Proxy uses the online packages offered by Huawei to install, those can be found on https://firmfinder.ml/ and these packages do not erase your internal data.

**Comment by ProfessorJTJ** [comment]
> For the version you gave, I have tested all the multiple zip packages I have downloaded, and they can all be read successfully. I also used the offline package method to successfully restore my phone to the old version of the firmware, indicating that the offline package function is completely normal, and it does not need to be connected to the Internet.
> 
> Thank you very much for your tool to help me restore the old firmware, and thank you very much for your patient guidance.

Thank you for testing, glad that it worked, sorry for the delay I just had so many things to do....

**Comment by ProfessorJTJ** [comment]
> I've tested v2.3.2 but this one "does nothing" when you are choosing offline packages (all: base, cust and preload).
> 
> To be sure i copied:
> 
> * update_sd_base
> * update_sd_cust_EML-L29_hw_eu
> * update_sd_preload_EML-L29_hw_eu_R1
>   to main folder of my C:\ drive
>   Files are extracted with latest WinRAR from: Huawei P20 EML-L29 hw eu Emily-L29C 10.0.0.171(C432E5R1P3) Firmware EMUI10.0.0 05015AQB
> 
> Unpacked both HISuite.Proxy.rar versions (2.3.1 and 2.3.2) to separate folders (HSP2310 and HSP2320 respectively) also to C:
> Version 2.3.1 shows "Wrong local header signature" error
> Version 2.3.2 - basically nothing is happening when you pointing a file (s). Tried all possible variants and combinations of HISuite.Proxy options. Even typed full local file paths into packages URL fields :)

I have found your firms on firmfinder:
EML-LGRP2-OVS 10.0.0.171 - EML-L29 - C432 - 435253
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/31/v3/f6be92deb01a4a23965699ceba9ada2f/full/filelist.xml

EML-L29-CUST 10.0.0.7(C432) - EML-L29 - C432 - 475207
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/99/v3/99b3b83a8fcc48eca7f57f6b73e51812/full/filelist.xml

EML-L29-PRELOAD 10.0.0.3(C432R1) - EML-L29 - C432 - 328695
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/51/v3/6446b9e4d72a47c99763c303e69f3931/full/filelist.xml


NTOE: You can browse the website and click on "Add Rom" to add them automatically to HISuite Proxy...

**Comment by mariuszo73** [comment]
Wow!
I really appreciate your help and feedback :)
Your tool is amazing when one learn how to use it.
Finally I was able to start recovery process. Downloading and unpacking firmware went smoothly.
However despite version of chosen base firmware flashing stops at 5%, HISuite returns "Recovery unsuccessful" error and phone restarts to bootloop.

I assume it is hardware issue. It was very hard case from the beginning: only active reboot option is fastboot&rescue mode, no recovery, etc. It seems that phone boots to system sometime but screen is black all the time.

I don't expect you can give me solution for that, but maybe.... ;)
Anyway. Thanks again for your effort.
Keep up a good work and take care!

P.S. Is firmware website yours? I see a donation button but not sure if it belongs to you.
You deserve some support. Can't do much but I will buy you coffee at least.
Regards!

**Comment by mariuszo73** [comment]
To much time in front of PC...
I just noticed "HISuite Proxy Support" on PayPal donation page :D
Support sent.

**Comment by ProfessorJTJ** [comment]
> Wow!
> I really appreciate your help and feedback :)
> Your tool is amazing when one learn how to use it.
> Finally I was able to start recovery process. Downloading and unpacking firmware went smoothly.
> However despite version of chosen base firmware flashing stops at 5%, HISuite returns "Recovery unsuccessful" error and phone restarts to bootloop.
> 
> I assume it is hardware issue. It was very hard case from the beginning: only active reboot option is fastboot&rescue mode, no recovery, etc. It seems that phone boots to system sometime but screen is black all the time.
> 
> I don't expect you can give me solution for that, but maybe.... ;)
> Anyway. Thanks again for your effort.
> Keep up a good work and take care!
> 
> P.S. Is firmware website yours? I see a donation button but not sure if it belongs to you.
> You deserve some support. Can't do much but I will buy you coffee at least.
> Regards!

Unfortunately recovery sometimes just fails like that, did you use "Add Firm" feature of the website or copied the data manually?

I'll double check and see if there's another firmware which might help you recover successfully....

Thanks for the donation I really appreciate it <3

**Comment by mariuszo73** [comment]
I was using "Add Firm" option on your website.
Tried different base versions with corresponding cust and preload packages.
Nothing works.
I noticed also that i can only start recovery process only when "Recovery OS" is ticked. All 3 other options causes immediate error (couldn't find package).
