### ISSUE TITLE
Found that HiSuite_11.0.0.510_OVE cannot be used

### ISSUE THREAD

**Issue by caiabc2021** [ProfessorJTJ/HISuite-Proxy#44]
1、install HiSuite_11.0.0.510_OVE.exe
2、Run hissuiteproxy, and then click setup. Prompt me to use HISuite 11.exe.
3、When I use "C:\Program Files (x86)\HiSuite\HiSuite.exe", I can connect to the phone normally. However, when I use hisuit11.exe, I cannot connect to the phone.

When I use "C:\Program Files (x86)\HiSuite\HiSuite.exe",
![20210403210020](https://user-images.githubusercontent.com/81454761/113479128-bf0e9380-94bf-11eb-8a31-c198b5ee4f51.png)

when I use hisuit11.exe, 
![20210403210041](https://user-images.githubusercontent.com/81454761/113479133-c766ce80-94bf-11eb-9d4e-d94af483989f.png)

**Comment by ProfessorJTJ** [comment]
Enable "USB Debugging"

**Comment by caiabc2021** [comment]
If I use the official original program, there is no need to activate usb debug, but automatically prompt to enable hdb

**Comment by caiabc2021** [comment]
After opening the usb debug, it is really available.
Moreover, the speed of transferring ROM to the mobile phone has been greatly accelerated.

Thanks a lot!
