### ISSUE TITLE
Find older roms in newer format

### ISSUE THREAD

**Issue by Invictaz** [ProfessorJTJ/HISuite-Proxy#45]
As the older dbankcdn links are down, how to find firmware links?
For example Huawei P9 EVA-L09
Those are not on firmfinder.ml

Old links are 
http://update.dbankcdn.com/TDS/data/files/p3/s15/G753/g104/v71496/f1/full/update.zip

New links are
http://update.dbankcdn.com/download/data/pub_13/*

It seems we need the ROMID which I Guess is 71496?

@ProfessorJTJ

**Comment by caiabc2021** [comment]
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Firm-Finder

**Comment by Invictaz** [comment]
@ProfessorJTJ The files are NOT on firmfinder
