### ISSUE TITLE
Offline packages not setting

### ISSUE THREAD

**Issue by CrabRave** [ProfessorJTJ/HISuite-Proxy#46]
Took HiSuite from latest download link on github.
Latest commit says that offline package bug fixed.
Windows 10 user, offline packages not setting

**Comment by ProfessorJTJ** [comment]
> Took HiSuite from latest download link on github.
> Latest commit says that offline package bug fixed.
> Windows 10 user, offline packages not setting

Open your package zip and take a screenshot from its files list.
I'm not a wizard.... :/

Also you may want to take a look at 
https://www.firmfinder.ml
