### ISSUE TITLE
BKL-AL20 CANT NOT WORK

### ISSUE THREAD

**Issue by beefjerky331** [ProfessorJTJ/HISuite-Proxy#48]
BKL-AL20 Version : Android10、EMUI10 10.0.0.178
HISuite-Proxy Version : 2.3.5
HISuite Version : 11.0.0.510 OVE

Base PKG : http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/47/v3/5f11cca6de5a4a06a5e6e48445c48c1e/
BKL-LGRP1-CHN 9.1.0.337
351781

CUST PKG : http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/5a/v3/56e35177198442318fd9671ff597b182/
BKL-AL20-CUST 9.1.0.333(C00)
326132

Preload PKG : 
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d0/v3/b3449c29e5f74ec6a34311c24393b772/
BKL-AL20-PRELOAD 9.1.0.1(C00R1)
282912

After downloading and installing the system, the UI prompts that the package failed verification.

i heard someone tell me, im using emui10 system now, there is a cpu overclock function name call GPU-Turbo, if I downgrade to a system(EMUI10 --> EMUI9) without this feature , the system will breakdown, its true?

**Comment by ProfessorJTJ** [comment]
Did you choose "rollback os" in HiSuite proxy or you chose normal update?

![Capture](https://user-images.githubusercontent.com/49002275/115733711-5fa8f280-a39e-11eb-9d6d-2e7e202c77ae.PNG)

**Comment by beefjerky331** [comment]
> 您在HiSuite代理中选择了“回滚操作系统”还是选择了正常更新？
> 
> ![捕获](https://user-images.githubusercontent.com/49002275/115733711-5fa8f280-a39e-11eb-9d6d-2e7e202c77ae.PNG)



> Did you choose "rollback os" in HiSuite proxy or you chose normal update?
> 
> ![Capture](https://user-images.githubusercontent.com/49002275/115733711-5fa8f280-a39e-11eb-9d6d-2e7e202c77ae.PNG)

yes,i choose "rollback os",it cant work.

**Comment by ProfessorJTJ** [comment]
> > Did you choose "rollback os" in HiSuite proxy or you chose normal update?
> > ![Capture](https://user-images.githubusercontent.com/49002275/115733711-5fa8f280-a39e-11eb-9d6d-2e7e202c77ae.PNG)
> 
> yes,i choose "rollback os",it cant work.

Put your links in hisuite proxy, then take a picture from it, let me see how you configured it...

**Comment by beefjerky331** [comment]
> > > Did you choose "rollback os" in HiSuite proxy or you chose normal update?
> > > ![Capture](https://user-images.githubusercontent.com/49002275/115733711-5fa8f280-a39e-11eb-9d6d-2e7e202c77ae.PNG)
> > 
> > 
> > yes,i choose "rollback os",it cant work.
> 
> Put your links in hisuite proxy, then take a picture from it, let me see how you configured it...

![PDXH`$HL1{VI7{31_(OCCH4](https://user-images.githubusercontent.com/44695469/115751388-bbd63b80-a3cb-11eb-8e1d-bc284f4a0bd5.png)

**Comment by ProfessorJTJ** [comment]
Everything seems fine, try with Hisuite 10 

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/1.8.8/HiSuite_10.0.1.100_OVE.zip

**Comment by beefjerky331** [comment]
> Everything seems fine, try with Hisuite 10
> 
> https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/1.8.8/HiSuite_10.0.1.100_OVE.zip

yesyes,thanks for ur reply, i will try it.
