### ISSUE TITLE
Failed to update... Downgrade from 11.0.0.167 to 11.0.0.166  MRX-W09

### ISSUE THREAD

**Issue by Pongchaan** [ProfessorJTJ/HISuite-Proxy#49]
Failed to update... Downgrade from 11.0.0.167 to 11.0.0.166  MRX-W09

**Comment by ProfessorJTJ** [comment]
Why would you do that lol
anyhow, you probably need to add cust and preload packages of 11.0 too, then choose "rollback" in HiSuite Proxy.
You'll most probably lose all your data, so take a backup.

**Comment by Pongchaan** [comment]
I would like to rollback to version 10.1.0.151 to install GMS.
Please tell me the detail of solution that you said => to add cust and preload packages of 11.0
What is the version of HiSuite Proxy I have to use, I saw 2 version of program.

**Comment by ProfessorJTJ** [comment]
HiSuite Proxy 2.3.5 
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/HISuite.Proxy.rar

You need [HiSuite 11](https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3/HiSuite_11.0.0.510_OVE.rar) or [10.1](https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip)
Open HiSuite Proxy and click "SetUp"


What's your phone region, is it C636?

if so search in the website:
Model: MRX-W09
Region: C636
Target version: 10.1

Output:
[MRX-LGRP4-OVS 10.1.0.151](https://www.firmfinder.ml/427442)
[MRX-W09-CUST 10.1.0.5(C636)](https://www.firmfinder.ml/391123)
[MRX-W09-PRELOAD 10.1.0.5(C636R1)](https://www.firmfinder.ml/391124)

Open the links and click "Add Rom" they will be shifted to HiSuite Proxy.
Then choose "OS Type" as "rollback OS"

Now hit "Update" in HiSuite.

**Comment by ProfessorJTJ** [comment]
Please first be sure what packages you need, to avoid bricking your phone
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

Step 3 shows you how to find the exact packages for your phone.

**Comment by Pongchaan** [comment]
I follow your step
The hisuite show windows to switch to order versions and I hit rollback/restore, I wait for long time and show me failed to update
I copy debug to show you, Please read it may be useful to solve this problem

HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/48/v3/bc15fb422a7e47fd88a5749ff9e0487b/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/48/v3/bc15fb422a7e47fd88a5749ff9e0487b/full/changelog/changelog_base_hw_spcseas.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/48/v3/bc15fb422a7e47fd88a5749ff9e0487b/full/changelog_base.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/8d/v3/122be642ef9843a4a2aef1a000c9b129/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/8d/v3/122be642ef9843a4a2aef1a000c9b129/full/changelog_cust_hw_spcseas.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/cb/v3/a444fdae106a476bbdf27ad50f756303/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/cb/v3/a444fdae106a476bbdf27ad50f756303/full/changelog_preload_hw_spcseas_R1.xml
HTTPS://query.hicloud.com:443/sp_ard_common/v1/authorize.action

Thanks

**Comment by ProfessorJTJ** [comment]
You need HiSuite 11

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3/HiSuite_11.0.0.510_OVE.rar

**Comment by Pongchaan** [comment]
Thank very much, ALL Done.

**Comment by ProfessorJTJ** [comment]
Congratulations! Happy to hear that.
