### ISSUE TITLE
no internet connection on hisuite after connecting to proxy

### ISSUE THREAD

**Issue by assess999** [ProfessorJTJ/HISuite-Proxy#50]
i have changed the base pkg , changed its package name and romID for OS target :

ELS-LGRP6-OVS 10.1.0.132

after pressing setup, it says that the connection to proxy is on and working and that i can proceed to installation but after connecting hisuite to my phone and using the custom port, pressing updates there is a pop up error  no internet connection, please check your network settings

im using huawei p40 pro+, hisuite 11.0.0.510_OVE from the huawei website.

**Comment by ProfessorJTJ** [comment]
Do you want to update to EMUI 11? If so be sure to include CUST and Preload packages of 11.0 too

Anyway, open HiSuite 11.exe with red icon on desktop, don't open the green HiSuite.exe icon....

**Comment by assess999** [comment]
i want to downgrade to emui 10.1.0.150 or less for googlefier, and where is the hisuite 11.exe found? i only have the green one from the website, and the red proxy one

**Comment by ProfessorJTJ** [comment]
> i want to downgrade to emui 10.1.0.150 or less for googlefier, and where is the hisuite 11.exe found? i only have the green one from the website, and the red proxy one

When you click on "setup" HiSuite 11.exe is generated on your desktop with red icon, if you don't find it, go to "C:/Program Files(x86)/HiSuite" there you will find HiSuite 11.exe, you need to open this one not HiSuite.exe

Tell me your phone's exact model so I could give you EMUI 10.1/10.0 Cust and preload packages, 
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

Step 3 tells you how to view your phone model

**Comment by ProfessorJTJ** [comment]
By the way as you're on EMUI 10.1 you could just use HiSuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by assess999** [comment]
on hisuite it says ELS-N39, base software version ELS-LGRP6-OVS 11.0.0.180   ELS-N39-CUST 11.0.0.2 (C636)  ELS-N39-PRELOAD 11.0.0.4(C636R2)

**Comment by ProfessorJTJ** [comment]
So in fact you need to have HiSuite 11, did you find the red icon on desktop already? 

Open these links and click "Add Rom" while HiSuite Proxy is open:

[ELS-LGRP6-OVS 10.1.0.132](https://www.firmfinder.ml/418569)
[ELS-N39-PRELOAD 10.1.0.1(C636R2)](https://www.firmfinder.ml/419200)
[ELS-N39-CUST 10.1.0.3(C636)](https://www.firmfinder.ml/418571)

Then choose "OS Type" as "Rollback" and click "Update" in HiSuite, it will say there's no update, Go to other versions, click Go to other versions, hit restore.

Good luck.

**Comment by assess999** [comment]
now my device isnt being detected by the red hisuite, where do i go to find the usb debugging

**Comment by ProfessorJTJ** [comment]
> now my device isnt being detected by the red hisuite, where do i go to find the usb debugging

https://www.youtube.com/watch?v=sgOmwIaDJdY

**Comment by assess999** [comment]
thanks for your help man, now im just waiting for it to install

**Comment by assess999** [comment]
was trying out with different versions of hisuite and firmwares for like 6 hours ytd and today

**Comment by ProfessorJTJ** [comment]
Hope it finished without any problems, good luck!

**Comment by assess999** [comment]
everything seems to work for now, as well as googlefier, except that i cant fix the notifications bug. uninstalling the services makes it so that i cant open playstore anymore to install any apps, so i cannot follow the instructions

**Comment by ProfessorJTJ** [comment]
> everything seems to work for now, as well as googlefier, except that i cant fix the notifications bug. uninstalling the services makes it so that i cant open playstore anymore to install any apps, so i cannot follow the instructions

Glad to hear that it worked, congratulations.
