### ISSUE TITLE
help！！！！！！！！！！

### ISSUE THREAD

**Issue by beeant0512** [ProfessorJTJ/HISuite-Proxy#51]
using hisute-proxy download nova2s(hwo-al00) to version HWI-AL00 8.0.0.195(C00) failed 

phone cannot open and cannot enter recovery mode

**Comment by ProfessorJTJ** [comment]
Did you rollback by HiSuite Proxy from EMUI 9 to 8?

**Comment by beeant0512** [comment]
yes ， EMUI 9 to 8 how can I save my phone

**Comment by ProfessorJTJ** [comment]
I have found dload firmware 9.1.0.201(C00E100R2P9T8) for 0.25$, do you know how to install a dload if I buy it and give you its link?

**Comment by ProfessorJTJ** [comment]
I've did it anyway, try it.... Its EMUI 9.1 for HWI-AL00, hope it gonna fix your issue.

http://dl7.iranmobile.org/Rom/Huawei0568pqt/Nova-2s/HWI-AL00/HWI-AL00_9.1.0.201(C00E100R2P9T8)-id76454.rar

**Comment by beeant0512** [comment]
@ProfessorJTJ 

my phone can not enter recovery mode and can not enter system ， how can I put it into the sdcard ？

**Comment by ProfessorJTJ** [comment]
> @ProfessorJTJ
> 
> my phone can not enter recovery mode and can not enter system ， how can I put it into the sdcard ？

Take out the sdcard, put it into another phone, connect the phone to pc, copy the files, take the sdcard back into your phone...

**Comment by beeant0512** [comment]
it's too hard for me to disassemble the phone

**Comment by beeant0512** [comment]
> I've did it anyway, try it.... Its EMUI 9.1 for HWI-AL00, hope it gonna fix your issue.
> 
> http://dl7.iranmobile.org/Rom/Huawei0568pqt/Nova-2s/HWI-AL00/HWI-AL00_9.1.0.201(C00E100R2P9T8)-id76454.rar

Thanks anyway

**Comment by ProfessorJTJ** [comment]
> it's too hard for me to disassemble the phone

this is probably the only way, you could try hisuite recovery mode, see if it will find any rom for you.
