### ISSUE TITLE
Hisuite Proxy won't grab separate files from one link

### ISSUE THREAD

**Issue by mrdark5555** [ProfessorJTJ/HISuite-Proxy#52]
I was trying to use it to grab the last software version for my BTV-W09 Mediapad M3 but the software is all listed under a single link.  Hisuite Proxy will not differentiate the different files and only grabs one of them for anything.  Base, cust, etc.  Tried putting in the additional url info the direct files, but it truncates it and removes the direct file links.

The link in question is:

HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/96/v3/f78b16d588a54229822ea725de197dd4/

Here are the full file links which it truncates.

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/96/v3/f78b16d588a54229822ea725de197dd4/full/public/update_data_full_public.zip

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/96/v3/f78b16d588a54229822ea725de197dd4/full/BTV-W09_hw_usa/update_full_BTV-W09_hw_usa.zip

http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/96/v3/f78b16d588a54229822ea725de197dd4/full/update.zip

**Comment by ProfessorJTJ** [comment]
This is an old firmware, if you're on EMUI 7 tick the box "EMUI 7 or below" if you're on EMUI 8 tick the box "EMUI 8"

Download latest HiSuite proxy if you don't have it.

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/HISuite.Proxy.rar

<img src="https://uupload.ir/files/eb10_bandicam_2021-04-18_10-57-08-452.jpg" />

**Comment by ProfessorJTJ** [comment]
By the way don't copy the link only, you need its full details. Click "Add Rom" from firmfinder, so the package will be added to HiSutie Proxy correctly.

Your firm link is:
https://www.firmfinder.ml/155749

**Comment by mrdark5555** [comment]
That did the trick.  Thank you so much.
