### ISSUE TITLE
Setup Hisuite Proxy  Crashed! The filename, directory name, or volume label syntax is incorrect. 

### ISSUE THREAD

**Issue by Pongchaan** [ProfessorJTJ/HISuite-Proxy#53]
[21:18:49]: Checking if HISuite is Installed...
 [21:18:50]: HiSuite Exists, Proceeding...
 [21:18:50]: Closing HISuite....
 [21:18:52]: Checking HISuite Version...
 [21:18:53]: HiSuite Version 11 Is Installed, Proceeding....
 [21:18:53]: Patching HISuite Files....
 [21:18:54]: Crashed! The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)
 [21:18:55]: Please Contact Developer If Error Continues
 [21:18:55]: https://github.com/ProfessorJTJ/HISuite-Proxy/issues

**Comment by ProfessorJTJ** [comment]
Are you on EMUI 11?
If no then try with HiSuite 10.1
I need to build a new app with debug logs for you to test and know what's the issue, though if HiSuite 10.1 is good enough for you, we can skip that.

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Pongchaan** [comment]
EMUI11 and use HiSuite 11.0.0.510

**Comment by ProfessorJTJ** [comment]
Replace this exe with the "HiSuite Proxy.exe" you have, then click on "Setup"

then send the log here, also send the file "debugfile.txt" which is in HiSuite Proxy folder, here.

[HiSuite Proxy.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6389264/HiSuite.Proxy.zip)

**Comment by Herbertas11** [comment]
Hey, so i did everything my HiSiute is on version 10.1 and with proxy was all good, no problems, but when i launch HiSiute and go to update it says im on the newest version 10.1.0.176 and i don't want to be on it, i want to be on ELS-LGRP4-OVS 10.1.0.131,
Can you help me at all ?

**Comment by ProfessorJTJ** [comment]
https://www.firmfinder.ml/409481 - ELS-LGRP4-OVS 10.1.0.131 - C432

Open the link, then "Add rom" and choose OS Type in HiSuite proxy as "rollback"

**Comment by ProfessorJTJ** [comment]
> Hey, so i did everything my HiSiute is on version 10.1 and with proxy was all good, no problems, but when i launch HiSiute and go to update it says im on the newest version 10.1.0.176 and i don't want to be on it, i want to be on ELS-LGRP4-OVS 10.1.0.131,
> Can you help me at all ?

https://www.firmfinder.ml/409481 - ELS-LGRP4-OVS 10.1.0.131 - C432

Open the link, then "Add rom" and choose OS Type in HiSuite proxy as "rollback"

**Comment by Pongchaan** [comment]
I use another computer to 

> Replace this exe with the "HiSuite Proxy.exe" you have, then click on "Setup"
> 
> then send the log here, also send the file "debugfile.txt" which is in HiSuite Proxy folder, here.
> 
> [HiSuite Proxy.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6389264/HiSuite.Proxy.zip)

I use another computer to do that
No problem about this problem 
Thanks.

**Comment by Pongchaan** [comment]
> Replace this exe with the "HiSuite Proxy.exe" you have, then click on "Setup"
> 
> then send the log here, also send the file "debugfile.txt" which is in HiSuite Proxy folder, here.
> 
> [HiSuite Proxy.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6389264/HiSuite.Proxy.zip)

Hi 
I did you suggest and this is logfiile detail.

Reading: C:\Program Files (x86)\HiSuite\httpcomponent.dll
Writing: C:\Users\rakku\AppData\Local\Temp\httpcomponent.dll
Replacing: C:\Users\rakku\AppData\Local\Temp\httpcomponent.dll with C:\Program Files (x86)\HiSuite\
Reading: C:\Program Files (x86)\HiSuite\HiSuite.exe
Writing: C:\Users\rakku\AppData\Local\Temp\HiSuite 11.exe
Replacing: C:\Users\rakku\AppData\Local\Temp\HiSuite 11.exe with C:\Program Files (x86)\HiSuite\HiSuite 11.exe
Reading: C:\Program Files (x86)\HiSuite\CommBase.dll
Writing: C:\Users\rakku\AppData\Local\Temp\CommBaze.dll
Replacing: C:\Users\rakku\AppData\Local\Temp\CommBaze.dll with C:\Program Files (x86)\HiSuite\
Creating shortcut: C:\Program Files (x86)\HiSuite\HiSuite 11.exe

Thank you.

**Comment by Herbertas11** [comment]
No everything worked perfectly Sent from my Huawei phone-------- Original message --------From: JTJ ***@***.***>Date: Tue, May 11, 2021, 11:41 AMTo: ProfessorJTJ/HISuite-Proxy ***@***.***>Cc: Herbertas11 ***@***.***>, Comment ***@***.***>Subject: Re: [ProfessorJTJ/HISuite-Proxy] Setup Hisuite Proxy  Crashed! The filename, directory name, or volume label syntax is incorrect.  (#53)


Replace this exe with the "HiSuite Proxy.exe" you have, then click on "Setup"
then send the log here, also send the file "debugfile.txt" which is in HiSuite Proxy folder, here.
HiSuite Proxy.zip

Hi
I did you suggest and this is logfile detail.
Reading: C:\Program Files (x86)\HiSuite\httpcomponent.dll
Writing: C:\Users\rakku\AppData\Local\Temp\httpcomponent.dll
Replacing: C:\Users\rakku\AppData\Local\Temp\httpcomponent.dll with C:\Program Files (x86)\HiSuite
Reading: C:\Program Files (x86)\HiSuite\HiSuite.exe
Writing: C:\Users\rakku\AppData\Local\Temp\HiSuite 11.exe
Replacing: C:\Users\rakku\AppData\Local\Temp\HiSuite 11.exe with C:\Program Files (x86)\HiSuite\HiSuite 11.exe
Reading: C:\Program Files (x86)\HiSuite\CommBase.dll
Writing: C:\Users\rakku\AppData\Local\Temp\CommBaze.dll
Replacing: C:\Users\rakku\AppData\Local\Temp\CommBaze.dll with C:\Program Files (x86)\HiSuite
Creating shortcut: C:\Program Files (x86)\HiSuite\HiSuite 11.exe
Thank you.

Hi, thank you but this time it did not crash, did it?

**Comment by Herbertas11** [comment]
Hello, I needed to restore again and when i tried to open your HiSuite
Poxy.zip file that you sent I could not. Can you send me another one. My
hiSuite version is the same as I wrote before.

2021-04-28, tr, 12:14 Pongchaan ***@***.***> rašė:
