### ISSUE TITLE
how to use offline packages?

### ISSUE THREAD

**Issue by foks101** [ProfessorJTJ/HISuite-Proxy#54]
help pls

**Comment by ProfessorJTJ** [comment]
What's your android version and to what version you want to switch?

**Comment by foks101** [comment]
> 
> 
> What's your android version and to what version you want to switch?

Android version - 8
Build number - JSN-L21 8.2.0.130

Want to switch android version - 8
Want to switch build number - JSN-L21 8.2.0.103

**Comment by ProfessorJTJ** [comment]
Why you don't use firmware from the website?

https://www.firmfinder.ml/

and choose "EMUI 8" in HiSuite Proxy.

unfortunately offline package installation doesn't support old firmwares like EMUI 8 for now.


JSN-L21 8.2.0.102(C461CUSTC461D1)

**Comment by foks101** [comment]
oh ok

**Comment by foks101** [comment]
full_back need second version info

**Comment by foks101** [comment]
Normal OS is working

**Comment by foks101** [comment]
Thank you!
