### ISSUE TITLE
There is no firmware for ELS-NX9 and ANA-NX9 C636 

### ISSUE THREAD

**Issue by Pongchaan** [ProfessorJTJ/HISuite-Proxy#55]
Please advise me if another firmware supports

**Comment by ProfessorJTJ** [comment]
Please read the guide, step 3 says how to find your phone model 


https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by Pongchaan** [comment]
thank you.
