### ISSUE TITLE
Recovery OS not working

### ISSUE THREAD

**Issue by janisslsm** [ProfessorJTJ/HISuite-Proxy#56]
I'm trying to get System Recovery working, I've added NEM-L21 to HiSuiteConfig.xml and I get this
![image](https://user-images.githubusercontent.com/78356133/116688008-bde95d00-a9be-11eb-91ac-d138a4040d5e.png)

My HiSuiteProxy settings
![image](https://user-images.githubusercontent.com/78356133/116687909-95f9f980-a9be-11eb-9d14-ad07095b0723.png)
There's no cust and preload packages for this model as far as I know

**Comment by ProfessorJTJ** [comment]
Well, clearly it's not a hisuite proxy bug.

Send your HiSuiteConfig.xml file here

**Comment by janisslsm** [comment]
[HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404926/HiSuiteConfig.txt)

**Comment by janisslsm** [comment]
> Well, clearly it's not a hisuite proxy bug.
> 
> Send your HiSuiteConfig.xml file here

[HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404928/HiSuiteConfig.txt)

**Comment by ProfessorJTJ** [comment]
> > Well, clearly it's not a hisuite proxy bug.
> > Send your HiSuiteConfig.xml file here
> 
> [HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404928/HiSuiteConfig.txt)

Everything is fine, probably because your phone is a bit old, it doesn't support system recovery.....

**Comment by janisslsm** [comment]
> > > Well, clearly it's not a hisuite proxy bug.
> > > Send your HiSuiteConfig.xml file here
> > 
> > 
> > [HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404928/HiSuiteConfig.txt)
> 
> Everything is fine, probably because your phone is a bit old, it doesn't support system recovery.....

Hm. I'm basically stuck on C432B132 and I'm trying to get back to B361. I've tried HiSuite update but it boots into recovery and says the file does not exist

**Comment by ProfessorJTJ** [comment]
> > > > Well, clearly it's not a hisuite proxy bug.
> > > > Send your HiSuiteConfig.xml file here
> > > 
> > > 
> > > [HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404928/HiSuiteConfig.txt)
> > 
> > 
> > Everything is fine, probably because your phone is a bit old, it doesn't support system recovery.....
> 
> Hm. I'm basically stuck on C432B132 and I'm trying to get back to B361. I've tried HiSuite update but it boots into recovery and says the file does not exist. I was hoping system recovery could do it. It does enter rescue mode whenever I go to system recovery though so I'm not sure.

What android version your phone is on? EMUI 7 or older?
Did you tick "EMUI 7 Or older" box before updating?

**Comment by janisslsm** [comment]
> > > > > Well, clearly it's not a hisuite proxy bug.
> > > > > Send your HiSuiteConfig.xml file here
> > > > 
> > > > 
> > > > [HiSuiteConfig.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6404928/HiSuiteConfig.txt)
> > > 
> > > 
> > > Everything is fine, probably because your phone is a bit old, it doesn't support system recovery.....
> > 
> > 
> > Hm. I'm basically stuck on C432B132 and I'm trying to get back to B361. I've tried HiSuite update but it boots into recovery and says the file does not exist. I was hoping system recovery could do it. It does enter rescue mode whenever I go to system recovery though so I'm not sure.
> 
> What android version your phone is on? EMUI 7 or older?
> Did you tick "EMUI 7 Or older" box before updating?
It's on EMUI 4.1.2/Android 6. I didn't tick it cause whenever I tick it, I get this
![image](https://user-images.githubusercontent.com/78356133/116689178-6e0b9580-a9c0-11eb-9509-2bc3e9e2ddc9.png)

**Comment by ProfessorJTJ** [comment]
Show me a screenshot from HiSuite Proxy....

**Comment by janisslsm** [comment]
> Show me a screenshot from HiSuite Proxy....

![image](https://user-images.githubusercontent.com/78356133/116689713-14f03180-a9c1-11eb-8855-62540c196720.png)

**Comment by ProfessorJTJ** [comment]
> > Show me a screenshot from HiSuite Proxy....
> 
> ![image](https://user-images.githubusercontent.com/78356133/116689713-14f03180-a9c1-11eb-8855-62540c196720.png)

You're using offline package?
That's the problem, HiSuite Proxy doesn't support offline packages for EMUI 7 and older phones.

Let HiSuite download it manually...

**Comment by janisslsm** [comment]
> > > Show me a screenshot from HiSuite Proxy....
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/78356133/116689713-14f03180-a9c1-11eb-8855-62540c196720.png)
> 
> You're using offline package?
> That's the problem, HiSuite Proxy doesn't support offline packages for EMUI 7 and older phones.
> 
> Let HiSuite download it manually...

Same thing 
![image](https://user-images.githubusercontent.com/78356133/116690273-d3ac5180-a9c1-11eb-8c69-999da09816ca.png)

**Comment by ProfessorJTJ** [comment]
On what version of HiSuite are you?

**Comment by janisslsm** [comment]
> On what version of HiSuite are you?

HiSuite_10.0.0.510_OVE.

**Comment by ProfessorJTJ** [comment]
> > On what version of HiSuite are you?
> 
> HiSuite_10.0.0.510_OVE

Can you send me HiSuite logs?

You can find them at:
"C:\Users\USERNAME\AppData\Local\HiSuite\log\SystemUpdate"

**Comment by janisslsm** [comment]
> > > On what version of HiSuite are you?
> > 
> > 
> > HiSuite_10.0.0.510_OVE
> 
> Can you send me HiSuite logs?
> 
> You can find them at:
> "C:\Users\USERNAME\AppData\Local\HiSuite\log\SystemUpdate.log"

[SystemUpdate_20210430_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405038/SystemUpdate_20210430_00.log)

**Comment by ProfessorJTJ** [comment]
HiSuite is malfunctioning...

It's not working properly I honestly don't know why
It should send request to page 
"https://query.hicloud.com/sp_ard_common/**v1**/onestopCheck.action"

but, it's instead sending request to page
"https://query.hicloud.com/sp_ard_common/**v2**/onestopCheck.action"

which is incorrect.....

**Comment by janisslsm** [comment]
> HiSuite is malfunctioning...
> 
> It's not working properly I honestly don't know why
> It should send request to page
> "https://query.hicloud.com/sp_ard_common/**v1**/onestopCheck.action"
> 
> but, it's instead sending request to page
> "https://query.hicloud.com/sp_ard_common/**v2**/onestopCheck.action"
> 
> which is incorrect.....

Is it possible to fix it somehow?

**Comment by ProfessorJTJ** [comment]
Try to uninstall and then reinstall HiSuite, try restarting your phone, see if it will send request to page /v1/

**Comment by ProfessorJTJ** [comment]
Also if you could find an old version of HiSuite, which would work, like V7 of HiSuite or something, I would hack it for you so HiSuite proxy would support it.

**Comment by janisslsm** [comment]
> Also if you could find an old version of HiSuite, which would work, like V7 of HiSuite or something, I would hack it for you so HiSuite proxy would support it.

Still sends to v2. I found V8 and V5 of HiSuite

**Comment by ProfessorJTJ** [comment]
> > Also if you could find an old version of HiSuite, which would work, like V7 of HiSuite or something, I would hack it for you so HiSuite proxy would support it.
> 
> Still sends to v2. I found V8 and V5 of HiSuite

Let's try V5 of HiSuite?

**Comment by janisslsm** [comment]
> > > Also if you could find an old version of HiSuite, which would work, like V7 of HiSuite or something, I would hack it for you so HiSuite proxy would support it.
> > 
> > 
> > Still sends to v2. I found V8 and V5 of HiSuite
> 
> Let's try V5 of HiSuite?

[HiSuite_5.0.2.301_OVE.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405141/HiSuite_5.0.2.301_OVE.zip)

**Comment by hooddy** [comment]
Guys I have the same issue with my P20 Pro. I do understand its not HiSuite proxy related but I don not know how to fix my phone. It is in soft breacked state with bootloop. I have add model into config and it still show me unsupported phone. Can someone advice me how to fix it please?

**Comment by ProfessorJTJ** [comment]
> Guys I have the same issue with my P20 Pro. I do understand its not HiSuite proxy related but I don not know how to fix my phone. It is in soft breacked state with bootloop. I have add model into config and it still show me unsupported phone. Can someone advice me how to fix it please?

Send your HiSuiteConfig.xml file here

**Comment by ProfessorJTJ** [comment]
> > > > Also if you could find an old version of HiSuite, which would work, like V7 of HiSuite or something, I would hack it for you so HiSuite proxy would support it.
> > > 
> > > 
> > > Still sends to v2. I found V8 and V5 of HiSuite
> > 
> > 
> > Let's try V5 of HiSuite?
> 
> [HiSuite_5.0.2.301_OVE.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405141/HiSuite_5.0.2.301_OVE.zip)

Doesn't need to be cracked, Just set the proxy settings, Open HiSuite settings enter proxy details.

Then click on 'update" see what's the result...

![Capture](https://user-images.githubusercontent.com/49002275/116692988-7c62ad00-a9d2-11eb-99b7-2e6fa0e55481.PNG)

**Comment by hooddy** [comment]
> Send your HiSuiteConfig.xml file here

[HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405198/HiSuiteConfig.zip)

**Comment by ProfessorJTJ** [comment]
> > Send your HiSuiteConfig.xml file here
> 
> [HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405198/HiSuiteConfig.zip)
> Its Android 8 onboard with unlobkd boot. I remove some app with adb and phone breaks.

Can't you install TWRP and then flash the rom?

Anyway, your HiSuiteConfig file was not correct, try this one
[HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405224/HiSuiteConfig.zip)

**Comment by ProfessorJTJ** [comment]
> It's working now.
> ![image](https://user-images.githubusercontent.com/78356133/116693260-4e776b80-a9c6-11eb-9641-7130e1b694e1.png)
> I'll report back again, if the update fails or not.

Good luck!, can't wait to hear the results.

**Comment by hooddy** [comment]
> 
> 
> > > Send your HiSuiteConfig.xml file here
> > 
> > 
> > [HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405198/HiSuiteConfig.zip)
> > Its Android 8 onboard with unlobkd boot. I remove some app with adb and phone breaks.
> 
> Can't you install TWRP and then flash the rom?
> 
> Anyway, your HiSuiteConfig file was not correct, try this one
> [HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405224/HiSuiteConfig.zip)
> 
> NOTE: TRY recovery without HiSuite Proxy, if HiSuite said there's no recovery found for you, then try HiSuite proxy...

I have CLT-AL00 fw. Not sure about TWRP. I dunno in where part flash it - recovery or e-recovery.

**Comment by ProfessorJTJ** [comment]
> > > > Send your HiSuiteConfig.xml file here
> > > 
> > > 
> > > [HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405198/HiSuiteConfig.zip)
> > > Its Android 8 onboard with unlobkd boot. I remove some app with adb and phone breaks.
> > 
> > 
> > Can't you install TWRP and then flash the rom?
> > Anyway, your HiSuiteConfig file was not correct, try this one
> > [HiSuiteConfig.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405224/HiSuiteConfig.zip)
> > NOTE: TRY recovery without HiSuite Proxy, if HiSuite said there's no recovery found for you, then try HiSuite proxy...
> 
> I have CLT-AL00 fw. Not sure about TWRP. I dunno in where part flash it - recovery or e-recovery.

CLT-AL00 and HiSuite says your phone doesn't support Recovery?
can you send HiSuite's logs?

Can be found at "C:\Users\USERNAME\AppData\Local\HiSuite\log\SystemUpdate.log"

please open a new issue  to keep this one neat.

**Comment by ProfessorJTJ** [comment]
So.... any result?

**Comment by janisslsm** [comment]
Goes into update mode and ends up failing at 1% of verifying update packages. I'm trying system recovery right now.
![image](https://user-images.githubusercontent.com/78356133/116699618-74a10980-a9ce-11eb-90e2-10acdf1fc52f.png)

**Comment by ProfessorJTJ** [comment]
> > > Goes into update mode and ends up failing at 1% of verifying update packages. I'm trying system recovery right now.
> > > Seems to get somewhere with HiSuite V5
> > 
> > 
> > Did you use offline package? that's wrong.
> > You hit "EMUI 7 or older" correct?
> > Be careful not to brick your phone.
> 
> Yes I hit EMUI 7 or older.

That's weird then, if I were you, I'd try with HiSuite 8

**Comment by janisslsm** [comment]
> > > > Goes into update mode and ends up failing at 1% of verifying update packages. I'm trying system recovery right now.
> > > > Seems to get somewhere with HiSuite V5
> > > 
> > > 
> > > Did you use offline package? that's wrong.
> > > You hit "EMUI 7 or older" correct?
> > > Be careful not to brick your phone.
> > 
> > 
> > Yes I hit EMUI 7 or older.
> 
> That's weird then, if I were you, I'd try with HiSuite 8

Alright, I'll try that.

**Comment by janisslsm** [comment]
I get this with HiSuite 8 
![image](https://user-images.githubusercontent.com/78356133/116700866-f2194980-a9cf-11eb-8126-acd62f9d937c.png)

**Comment by ProfessorJTJ** [comment]
> I get this with HiSuite 8
> ![image](https://user-images.githubusercontent.com/78356133/116700866-f2194980-a9cf-11eb-8126-acd62f9d937c.png)
> 
> Github isnt letting me upload the zip

I'll crack it in 10 minutes and send you the new HiSuite Proxy.exe

**Comment by ProfessorJTJ** [comment]
Replace this with the .exe you have, then click on "setup"

[HiSuite Proxy.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405641/HiSuite.Proxy.zip)

**Comment by janisslsm** [comment]
I ended up getting it working, I got rid of the HiSuite app on the phone and then let HiSuite 8.0.1.300 reinstall it and it's trying to install the update right now.

**Comment by ProfessorJTJ** [comment]
> I ended up getting it working, I got rid of the HiSuite app on the phone and then let HiSuite 8.0.1.300 reinstall it and it's trying to install the update right now.

Yay, good luck!

**Comment by janisslsm** [comment]
Still fails to install the update. "Failed to check the update files." that's what the recovery gives me. Not sure what else I could try.

**Comment by ProfessorJTJ** [comment]
> Still fails to install the update. "Failed to check the update files." that's what the recovery gives me. Not sure what else I could try.

that sucks, try "EMUI 8" option :/

**Comment by janisslsm** [comment]
> > Still fails to install the update. "Failed to check the update files." that's what the recovery gives me. Not sure what else I could try.
> 
> that sucks, try "EMUI 8" option :/
![image](https://user-images.githubusercontent.com/78356133/116707773-b71b1400-a9d7-11eb-9c2e-fcdbdf479f95.png)

**Comment by janisslsm** [comment]
I'll try HiSuite V4

**Comment by janisslsm** [comment]
Still doesn't work. :/

**Comment by janisslsm** [comment]
I managed to upgrade it in a weird way via dload method. Thanks for your help.
