### ISSUE TITLE
Can not recover P20 Pro with CLT-AL00

### ISSUE THREAD

**Issue by hooddy** [ProfessorJTJ/HISuite-Proxy#57]
I am trying to recover my soft breaked P20 Pro with CLT-AL00 with open bootloader.
There is HiSuite logs.
[log.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6405284/log.zip)

**Comment by ProfessorJTJ** [comment]
`[2021-04-30 15:21:43:233][L2_VIM][sn=2][RESULT: TRUE][HiSuite_SystemUpdate][[[DATA1: getvar devicemodel  return devicemodel: CLT-A00\r\nfinished. total time: 0.007s\r\n[tid=11428]]]][/php]`

Shouldn't the devicemodel be CLT-AL00?

**Comment by hooddy** [comment]
> 
> 
> `[2021-04-30 15:21:43:233][L2_VIM][sn=2][RESULT: TRUE][HiSuite_SystemUpdate][[[DATA1: getvar devicemodel return devicemodel: CLT-A00\r\nfinished. total time: 0.007s\r\n[tid=11428]]]][/php]`
> 
> Shouldn't the devicemodel be CLT-AL00?
> 
Well it was Russian market model but I change localization code with HCU service and flash Chinese FW. It works fine in past.
I just though Chinise F will have no Google in it like in MAte 40 Pro but it doesn't - it contain some GApps in it anyway.

> By the way as you used adb and bricked the phone, if you wipe cache & data, it doesn't help?
No it doesn't. I use Multi Tool 8 for manipulation but it use adb in anyway. 

I am trying to use dload flash but I do not have corresponding type-c OTG connector and/or usb flash. I am trying 3 different connectors and  few flashes with no luck. As well I trying to use WiFi recovery with the same results.

I have stock recovery and e-recovery still. If I flash TWRP can I recover it? I don't undesrstand where to flash it - recovery or e-recovery.

**Comment by ProfessorJTJ** [comment]
> > `[2021-04-30 15:21:43:233][L2_VIM][sn=2][RESULT: TRUE][HiSuite_SystemUpdate][[[DATA1: getvar devicemodel return devicemodel: CLT-A00\r\nfinished. total time: 0.007s\r\n[tid=11428]]]][/php]`
> > Shouldn't the devicemodel be CLT-AL00?
> 
> Well it was Russian market model but I change localization code with HCU service and flash Chinese FW. It works fine in past.
> I just though Chinise FW will have no Google in it like in Mate 40 Pro but it doesn't - it contain some GApps in it anyway.
> 
> > By the way as you used adb and bricked the phone, if you wipe cache & data, it doesn't help?
> > No it doesn't. I use Multi Tool 8 for manipulation but it use adb in anyway.
> 
> I am trying to use dload flash but I do not have corresponding type-c OTG connector and/or usb flash. I am trying 3 different connectors and few flashes with no luck. As well I trying to use WiFi recovery with the same results.
> 
> I have stock recovery and e-recovery still. If I flash TWRP can I recover it? I don't undesrstand where to flash it - recovery or e-recovery.

The guy explains here how to flash twrp

https://forum.xda-developers.com/t/recovery-p20-unofficial-twrp-3-2-1-0-16-04-2018.3778585/
