### ISSUE TITLE
HiSuite Proxy says, If your phone doesn't connect, enable 'USB Debugging' but I already did that

### ISSUE THREAD

**Issue by DavidBoom20** [ProfessorJTJ/HISuite-Proxy#58]
[16:50:29]: Checking if HISuite is Installed...
 [16:50:30]: HiSuite Exists, Proceeding...
 [16:50:30]: Closing HISuite....
 [16:50:32]: Checking HISuite Version...
 [16:50:33]: HiSuite Version 11 Is Installed, Proceeding....
 [16:50:33]: Patching HISuite Files....
 [16:50:34]: Patch succeeded, Proceeding....
 [16:50:35]: Checking HISuite Proxy Settings...
 [16:50:35]: Proxy Settings Are Already Set, Proceeding...
 [16:50:36]: Checking Hosts File For Redundant Entries....
 [16:50:36]: Hosts File Is Already Neat, Proceeding...
 [16:50:37]: Checking Connection To HISuite Proxy....
 [16:50:38]: HISuite Proxy Is On And Working.
 [16:50:38]: 
 [16:50:39]: Checks Finished, You can proceed to installation now!
 [16:50:39]: Use HISuite 11.exe instead of your older file...
 [16:50:40]: If your phone doesn't connect, **enable 'USB Debugging'.**

The thing is, I already use HiSuite 11 on the Desktop (red icon) and i Enabled USB Debugging.
My phone (ANA-NX9) connects to HiSuite 11 (the one with the red icon) but it still dosen't work...

Does anyone know what to do?

![Screenshot (3)](https://user-images.githubusercontent.com/83547168/116819562-d5684780-ab70-11eb-810d-36796150531f.png)

**Comment by ProfessorJTJ** [comment]
You're passing rom name in the url field, basically you haven't setup hisuite proxy properly.

Find proper rom and click on "Add rom" in here
https://www.firmfinder.ml/

**Comment by DavidBoom20** [comment]
I can't find my Device (P40/ANA-NX9) on that list.

**Comment by ProfessorJTJ** [comment]
> I can't find my Device (P40/ANA-NX9) on that list.

Because it's not NX9 it's probably N49 or 04 or smth

https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

Read step 3 of the guide to find your correct phone model...

**Comment by DavidBoom20** [comment]
I've gone on the website that you sent me and found my model! (it was ana-n29 😅)
Then I filled out the Base package url, the package name and RomID in HiSuite Proxy (as you can see in the picture)
The problem is, it still dosen't work...
What did I do wrong? Is there anymore information missing?

![Screenshot (4)](https://user-images.githubusercontent.com/83547168/116821035-668eec80-ab78-11eb-9c0a-2d5e445d83b7.png)

**Comment by ProfessorJTJ** [comment]
> I've gone on the website that you sent me and found my model! (it was ana-n29 😅)
> Then I filled out the Base package url, the package name and RomID in HiSuite Proxy (as you can see in the picture)
> The problem is, it still dosen't work...
> What did I do wrong? Is there anymore information missing?
> 
> ![Screenshot (4)](https://user-images.githubusercontent.com/83547168/116821035-668eec80-ab78-11eb-9c0a-2d5e445d83b7.png)

You probably need CUST and preload packages too
CUST and Preload has to be 10.1.0, if you didn't find, you can use cust/preload of 10.0
If you're rolling back choose OS Type as Rollback or you might stick in bootloop until you wipe cache and data.

**Comment by DavidBoom20** [comment]
Thanks, gonna try that now...

**Comment by ProfessorJTJ** [comment]
If you're still facing problems you can view this complete video

https://youtu.be/CdYpZlXlgOQ

**Comment by Alxseb** [comment]
Hi, I have a Mate 40 Pro and I want to downgrade the software, from version 11.0.0.174 to 11.0.0.114. I downloaded Hi Suite and followed exactly the steps in the tutorial but it gives me a connection error. If I install an older version of HiSuite, it gives me an installation error after downloading the rom.

**Comment by ProfessorJTJ** [comment]
> Hi, I have a Mate 40 Pro and I want to downgrade the software, from version 11.0.0.174 to 11.0.0.114. I downloaded Hi Suite and followed exactly the steps in the tutorial but it gives me a connection error. If I install an older version of HiSuite, it gives me an installation error after downloading the rom.

Hey, that's because you're opening the green hisuite 11,
When you patch hisuite 11, you have to open a red icon hisuite with the name Hisuite 11.exe, HiSuite proxy makes it on desktop for you.


For the second problem,

Are you using Hisuite 10.1? Only hisuite 11 and 10.1 support emui 11 so download 10.1
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip


Are you still facing the error or you're already on hisuite 10.1?

Then the problem is, your phone is possibly and Chinese and re-branded, so Huawei thinks your phone is uncertified for updates.

Want to force update? There's a checkbox at the bottom of hisuite proxy named "Force Auth Bridge" tick that box and you should be good to go.

Good luck!


Note: be sure to choose OS Type as Rollback, or you might stick in bootloop, till you wipe cache and data.

**Comment by Alxseb** [comment]
My mistake was that I opened HiSuite with the green button. I then opened the version with the red button, it connected, it downloaded the rom it was installed but when the phone was restarted the update fail appeared.

**Comment by Alxseb** [comment]
And the version remain the same

**Comment by ProfessorJTJ** [comment]
> My mistake was that I opened HiSuite with the green button. I then opened the version with the red button, it connected, it downloaded the rom it was installed but when the phone was restarted the update fail appeared.

C:/Users/your user/App Data/local/HiSuite/logs/Systemupdate

I could view your log to check if your phone is possibly re-branded, and yes rebranding causes this along with not entering correct ROMID
You could give "Force Auth Bridge" a try, if it's re-branded it would still let the update install....

**Comment by ProfessorJTJ** [comment]
You could join the telegram group for faster communication


https://t.me/firmfinder


Heading to sleep now, good night!

**Comment by Alxseb** [comment]
good night

**Comment by DavidBoom20** [comment]
> If you're still facing problems you can view this complete video
> 
> https://youtu.be/CdYpZlXlgOQ


I've done all the steps and now everything works as it should, including google mobile services and all google apps! This is actually my father's phone. I told him that he should buy a Huawei phone because they are currently very cheap. (probably because of all the gms stuff)
You really helped me a lot, because without you I would never have done it!😅  I'm thinking of buying a Mate 40 pro this year as I've had a Mate 20 lite for almost 2 years now.
I appreciated your help
See you next time!😉

**Comment by ProfessorJTJ** [comment]
> > If you're still facing problems you can view this complete video
> > https://youtu.be/CdYpZlXlgOQ
> 
> I've done all the steps and now everything works as it should, including google mobile services and all google apps! This is actually my father's phone. I told him that he should buy a Huawei phone because they are currently very cheap. (probably because of all the gms stuff)
> You really helped me a lot, because without you I would never have done it!😅 I'm thinking of buying a Mate 40 pro this year as I've had a Mate 20 lite for almost 2 years now.
> I appreciated your help
> See you next time!😉

Congrats buddy, happy to hear that 👍🏻

**Comment by Alxseb** [comment]
I also tried the "Force Auth Bridge" but without success. I checked the imei and the phone is made for europe, it was not re-branded from china version. I'm attaching some photos with the error.![IMG_20210502_230353](https://user-images.githubusercontent.com/83552909/116848577-903a2900-abf5-11eb-868f-a4c8cbf82219.jpg)
![IMG_20210502_230400](https://user-images.githubusercontent.com/83552909/116848614-a3e58f80-abf5-11eb-91ce-124c93fdf4b5.jpg)
![IMG_20210502_230528](https://user-images.githubusercontent.com/83552909/116848642-b52e9c00-abf5-11eb-9ae3-b2113bbbf4c5.jpg)

**Comment by ProfessorJTJ** [comment]
> I also tried the "Force Auth Bridge" but without success. I checked the imei and the phone is made for europe, it was not re-branded from china version. I'm attaching some photos with the error.![IMG_20210502_230353](https://user-images.githubusercontent.com/83552909/116848577-903a2900-abf5-11eb-868f-a4c8cbf82219.jpg)
> ![IMG_20210502_230400](https://user-images.githubusercontent.com/83552909/116848614-a3e58f80-abf5-11eb-91ce-124c93fdf4b5.jpg)
> ![IMG_20210502_230528](https://user-images.githubusercontent.com/83552909/116848642-b52e9c00-abf5-11eb-9ae3-b2113bbbf4c5.jpg)

Well, I cannot help you like this, at least send hisuite logs...
"C:/Users/your user/App Data/local/HiSuite/logs/Systemupdate"

**Comment by Alxseb** [comment]
[SystemUpdate_20210503_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6413271/SystemUpdate_20210503_00.log)

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210503_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6413271/SystemUpdate_20210503_00.log)

`[2021-05-03 09:16:31:216][L2_VIM][fn=4][RESULT: FALSE][HiSuite_SystemUpdate][[[CAUSE: ERROR_CODE=0]]][[[DATA1: GetAuthFile file=data=`

Though the file data is correct, it's showing RESULT: FALSE, I don't know if this is normal, but you can help me to dig more into it.

Tick the box "Debug Logging" When HiSuite finishes downloading, starts to pushing the rom to the phone ( installing ), you can cancel the update and send the file "logs.txt" ( which will be nearby HiSuite Proxy.exe ) here.

Probably ( not sure ) that Huawei is using a new authentication method for its new phones, which are not supported by the proxy, so I'd need the logs to see what's going wrong....

**Comment by ProfessorJTJ** [comment]
Edit: I just checked some other phones and its normal for the auth to show RESULT: FALSE

**Comment by Alxseb** [comment]
So, what can I do?

**Comment by ProfessorJTJ** [comment]
> So, what can I do?

I don't know if this will do any help, but you could tick "Debug Logging" and get "logs.txt" which will be nearby HiSuite Proxy ( after HiSuite finishes download and authenticates ) then send it here....

**Comment by Alxseb** [comment]
[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6413806/logs.txt)

**Comment by ProfessorJTJ** [comment]
[HiSuite Proxy.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6413901/HiSuite.Proxy.zip)

Repalce this exe with the one you got, and see if it will work... ( only difference I see is that official huawei response has "versionType" and "pointVersion" which are missing from HiSuite Proxy's response... ) I don't know if this is a big deal, but you could give it a try

By the way you can take a backup from 

"Documents\Hisuite\ROM/NOH-LGRP2-OVS 11.0.0.114/full/update_full_base.zip"
"Documents\Hisuite\ROM/NOH-N29-CUST 11.0.0.6(C432)/full/update_full_cust_NOH-N29_hw_eu.zip" 
"Documents\Hisuite\ROM/NOH-N29-PRELOAD 11.0.0.1(C432R6)/full/update_full_preload_NOH-N29_hw_eu_R6.zip"

So you don't have to download the ROMS each time, you will just place the zips there and HiSuite will skip the download for you

**Comment by Alxseb** [comment]
Is there a chance to unlock the bootloader? We couldn't find any decoding service for Mate 40 Pro. I think I have a chance if I use the dload mode

**Comment by Alxseb** [comment]
By the way, is not working with new HiSuite.exe file :(

**Comment by Alxseb** [comment]
I think the problem is not from the program, I think it is from the phone. This version may not support installing previous versions

**Comment by ProfessorJTJ** [comment]
> Is there a chance to unlock the bootloader? We couldn't find any decoding service for Mate 40 Pro. I think I have a chance if I use the dload mode

Unfortunately I don't know any such services...

:/ maybe Huawei added extra security checks on mate 40
