### ISSUE TITLE
CUST and PRELOAD for ELS-N29

### ISSUE THREAD

**Issue by MousMakes** [ProfessorJTJ/HISuite-Proxy#59]
I tested updating my firmware with 10.1.0.146 OVS from teammt, but got the "Group version not match error", so i think i need the CUST and PRELOAD as well, since i have EMUI 11 and will need to downgrade to 10 (to install google services). 

My actual versions: 
Base: ELS-LGRP4-OVS 11.0.0.180
CUST: ELS-N29-CUST 11.0.0.3(C432)
PRELOAD: 11.0.0.4(C432R6)

I already searched on teammt and found these: 
ELS-LGRP4-OVS 10.1.0.146 (Is the latest before 15. Juli)
ELS-N29-CUST 10.1.0.8(C432)
ELS-N29-PRELOAD 10.1.0.1(C432R6)

How do i know if these are compatible?

**Comment by ProfessorJTJ** [comment]
Buddy, teammt servers are down for a millenia now. Use the new firmfinder
https://www.firmfinder.ml

Guide
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

Video guide
https://youtu.be/CdYpZlXlgOQ

**Comment by MousMakes** [comment]
I found the problem.

firmfinder.ml does not include the CUST and PRELOAD selected in the video description in their normal view. You need to change the archive in the bottom left corner. At the default view only the OVS packages are displayed...
