### ISSUE TITLE
Typing "full"will cause the word to disappear

### ISSUE THREAD

**Issue by lesterchan** [ProfessorJTJ/HISuite-Proxy#6]
Click on the screenshot below and it will bring you to YouTube that shows a screen recording of the bug.

[![Screen Recording Of The Bug](https://img.youtube.com/vi/etBUqGvvrR8/0.jpg)](https://www.youtube.com/watch?v=etBUqGvvrR8)

Because of this, I can not paste URL like http://update.dbankcdn.com/TDS/data/files/p3/s15/G5731/g1755/v410289/f1/full/changelog_base.xml into the field as it contains the word "full"

**Comment by ProfessorJTJ** [comment]
It's not a bug, the url doesn't need to be complete, it has to be shrunk till /f1/
No problem, just proceed to the installation

**Comment by lesterchan** [comment]
Weird, then why some other people are able to show the full URL? I am not sure is it because of this, the HiSuite is unable to detect the updated firmware. It keeps prompting You Have The Latest Version

**Comment by ProfessorJTJ** [comment]
> Weird, then why some other people are able to show the full URL? I am not sure is it because of this, the HiSuite is unable to detect the updated firmware. It keeps prompting You Have The Latest Version

No person can copy paste the full url, and if they do that will bug the script and hisuite won't run properly. 

Be sure you have clicked on "SetUP" and it competed the process
Open Hisuite settings and be sure proxy settings are set as address 127.0.0.1 and port 7777
Also click on Show low debug and be sure Hisuite proxy is receiving requests

**Comment by lesterchan** [comment]
Ah gotcha! The missing key is the Hisuite Proxy Setting. Thank you! The step is missing from https://forum.xda-developers.com/huawei-p30-pro/how-to/guide-how-to-flash-approved-fullota-zip-t4112775

**Comment by ProfessorJTJ** [comment]
> Ah gotcha! The missing key is the Hisuite Proxy Setting. Thank you! The step is missing from https://forum.xda-developers.com/huawei-p30-pro/how-to/guide-how-to-flash-approved-fullota-zip-t4112775

"Setup" is supposed to set proxy settings, dunno if it's failing for you :/

**Comment by lesterchan** [comment]
Yea, I ran setup many times (at first I thought to do it wrongly). It didn't do it for me =(

**Comment by ProfessorJTJ** [comment]
> Yea, I ran setup many times (at first I thought to do it wrongly). It didn't do it for me =(

Are you interested in helping me to solve that bug?
If yes contact me on telegram
https://t.me/lurexdj

**Comment by ProfessorJTJ** [comment]
> Yea, I ran setup many times (at first I thought to do it wrongly). It didn't do it for me =(

Solved!
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/tag/1.8.2
