### ISSUE TITLE
cannot recover or rollback os

### ISSUE THREAD

**Issue by cMonedula** [ProfessorJTJ/HISuite-Proxy#62]
hello! i am aware this is a mistake completely on my part, but i've seen you help other users so i'm hoping you could help me as well (their solutions haven't worked for me).

yesterday i first dabbled in updating my phone (Honor 9X Lite - JSN-L21 c431; yes it shares the model number with Honor 8X, it was running EMUI 9.1 until yesterday) and i was successful in updating it to JSN-LGRP2-OVS 9.1.0.360 with the help of your proxy. i used only the base files, CUST and PRELOAD was turned off.

this is the part where my curiosity got the better of me, and since i saw that the 8X EMUI 9.1 update files worked for me, surely the EMUI 10 ones would as well? so did a full install as you advised in the wiki and ended up with these versions ([https://ctrlv.sk/87ti](https://ctrlv.sk/87ti)). then i noticed the phone, while otherwise operational on EMUI 10, couldn't use the cameras at all and wanted to go back to EMUI 9.1.

could you please advise me on how to downgrade? i've tried many ways, through dloading and such, but i always end up with  a "Software install failed!" screen. the phone works otherwise, but as it is my daily driver i really need the cameras working (taking photos of school notes and such). i am not worried about losing my data, as i have it all backed up on a computer.

i am really desperate at this point, so thank you for at least taking the time to read this.

**Comment by ProfessorJTJ** [comment]
You see that the picture you posted here is missing the preload package right?
Please send me the file which is at:
C:/Users/Your User/App Data/Local/log/systemupdate.log

So I can dig deeper into what's happening... 

HOWEVER, Use EMUI 9.1 files ( Base, Cust, Preload ), and choose OS Type as "Rollback" and there is a box named "Force Auth Bridge" tick this box.

Probably your phone is no longer certified for installing Huawei Roms, in this case ticking the box "Force Auth Bridge" is supposed to fix it.

**Comment by cMonedula** [comment]
i took a scrolling screenshot, if there's no preload in the pic there probably isn't one at all (no idea how that happened, i am pretty sure i included one in the install).

there's no log folder in local appdata or a systemupdate.log file... any other places i could check? i got the Hisuite Proxy as a folder with an exe on my desktop (not a full system install) if that matters.

also, please review this screenshot and tell me what i did wrong, it doesn't want to work all of a sudden (the hisuite popout says "no internet connection, check network settings" but my internet works just fine.)
![image](https://user-images.githubusercontent.com/62065484/118394948-0bfd9200-b648-11eb-945c-a76dd86b8d76.png)

honestly, at this point it's like half bricked (and unable to update, like, at all) so i'm open to suggestions.

**Comment by ProfessorJTJ** [comment]
> i took a scrolling screenshot, if there's no preload in the pic there probably isn't one at all (no idea how that happened, i am pretty sure i included one in the install).
> 
> there's no log folder in local appdata or a systemupdate.log file... any other places i could check? i got the Hisuite Proxy as a folder with an exe on my desktop (not a full system install) if that matters.
> 
> also, please review this screenshot and tell me what i did wrong, it doesn't want to work all of a sudden (the hisuite popout says "no internet connection, check network settings" but my internet works just fine.)
> ![image](https://user-images.githubusercontent.com/62065484/118394948-0bfd9200-b648-11eb-945c-a76dd86b8d76.png)
> 
> honestly, at this point it's like half bricked (and unable to update, like, at all) so i'm open to suggestions.

My bad, it's in

App data/local/HiSuite/log

After you click "setup" in HiSuite proxy, open the hisuite 11 with red icon on desktop instead of the green hisuite.

**Comment by ProfessorJTJ** [comment]
By the way, for the preload missing, people encounter such a problem when for example their phone is C432 but they install C185 firmware.

Their phone become uncertified for updates but they usually do not face problems.
Using Auth Bridge and installing original C432 firmware again usually fixes it ( preload and cust firmwares are region based, but base firmwares are all fine, but installing another region base may also kill ota update )

**Comment by cMonedula** [comment]
okay, here's the log! [SystemUpdate_20210516_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6489147/SystemUpdate_20210516_00.log)

and, well, one more thing popped up and that is that the patched Hisuite (v11, if that matters) can't connect to my phone. is that on purpose, should i use the recovery option? i went and killed all hisuite-related tasks i could see before launching it, if that matters 

(and i just want to thank you for taking the time to help me! i really appreciate it, have you by any chance got a brave creators account set up?)

**Comment by ProfessorJTJ** [comment]
> okay, here's the log! [SystemUpdate_20210516_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6489147/SystemUpdate_20210516_00.log)
> 
> and, well, one more thing popped up and that is that the patched Hisuite (v11, if that matters) can't connect to my phone. is that on purpose, should i use the recovery option? i went and killed all hisuite-related tasks i could see before launching it, if that matters
> 
> (and i just want to thank you for taking the time to help me! i really appreciate it, have you by any chance got a brave creators account set up?)

If you use hisuite 10.1 you would not encounter these problems, well, enable USB Debugging and it will be fixed

I'll check the log now. 


Aaaa, what's creator account?

**Comment by ProfessorJTJ** [comment]
Hey, your device model is not JSN-L21
It's JSN-L21X , be sure you choose L21X emui 9.1 firmwares for the rollback!

That's why your preload and rom installation certificate are void. Because you installed a firmware of another model on your phone....

**Comment by cMonedula** [comment]
woah, i had no idea! guess my phone's and Honor 8X's firmware aren't that similar after all :D

i installed and proxy'd Hisuite 10.1, the update is currently installing. i try to not have my hopes too high but i really hope it'll work :D is it okay if there's no version number listed? like the "new version:" just has a blank after it

as for the creator account, it's provided by Brave so i suggest maybe taking a look at it? i have a few BATs, it ain't much but i'd be glad to at least partially reward your time spent helping me and developing this utility :D

**Comment by ProfessorJTJ** [comment]
> woah, i had no idea! guess my phone's and Honor 8X's firmware aren't that similar after all :D
> 
> i installed and proxy'd Hisuite 10.1, the update is currently installing. i try to not have my hopes too high but i really hope it'll work :D is it okay if there's no version number listed? like the "new version:" just has a blank after it
> 
> as for the creator account, it's provided by Brave so i suggest maybe taking a look at it? i have a few BATs, it ain't much but i'd be glad to at least partially reward your time spent helping me and developing this utility :D

Yeah when your device is modified, preload version gets hidden and when you try to install new version, rom name become invisible, but the update succeeds ( in case you ticked the box named Force Auth Bridge )

Sure I'll take a look at it.

**Comment by cMonedula** [comment]
welp, it kind of didn't work. here's my proxy window if it can be of any help, but the phone just gave me a "Software install failed!".
![image](https://user-images.githubusercontent.com/62065484/118400199-df09a900-b660-11eb-8aa6-7ec6cfa54acc.png)

**Comment by ProfessorJTJ** [comment]
> welp, it kind of didn't work. here's my proxy window if it can be of any help, but the phone just gave me a "Software install failed!".
> ![image](https://user-images.githubusercontent.com/62065484/118400199-df09a900-b660-11eb-8aa6-7ec6cfa54acc.png)

Send the file systemupdate.log

Also you had force Auth Bridge ticked, correct?

**Comment by cMonedula** [comment]
yep, as you advised!

here's the log [SystemUpdate_20210516_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6489346/SystemUpdate_20210516_00.log)

**Comment by ProfessorJTJ** [comment]
Maybe you need the rollback firmwares?

Well, I've got rollback firmwares of JSN-L21, do you want to risk flashing on JSN-L21X?

Base:
JSN-LGRP2-OVS 9.1.0.266 - 368641
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/14/v3/ab3a267d98a44116b268465197b43597/full/changelog_base.xml

Cust:
JSN-L21-CUST 9.1.0.1(C431) - 368648
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/ea/v3/7b20c5ce22914265aa8fe0374da419b2/full/changelog_cust_hw_eea.xml

Preload:
JSN-L21-PRELOAD 9.1.0.1(C431R1) - 339974
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/5/v3/07e4a873a014488ea1e5d412edbc1515/full/changelog_preload_hw_eea_R1.xml

**Comment by ProfessorJTJ** [comment]
You could also try rolling back to 

JSN-LGRP2-OVS 9.1.0.293 : https://www.firmfinder.ml/379018

JSN-L21-CUST 9.1.0.2(C431) : https://www.firmfinder.ml/374047

JSN-L21X-PRELOAD 9.1.0.1(C431R1) : https://www.firmfinder.ml/374046

**Comment by cMonedula** [comment]
not gonna lie, the emui 9 UI is a sight for sore eyes :D now i'm stuck with a different kinda problem and that is an odd google voice keyboard kinda thing that does not accept voice input at all and can't be switched for anything else (so i can't progress beyond the initial os setup), do you by any chance have a way to fix that?

**Comment by ProfessorJTJ** [comment]
> not gonna lie, the emui 9 UI is a sight for sore eyes :D now i'm stuck with a different kinda problem and that is an odd google voice keyboard kinda thing that does not accept voice input at all and can't be switched for anything else (so i can't progress beyond the initial os setup), do you by any chance have a way to fix that?

Used JSN-L21 firmwares or L21X?
Maybe now try dload of emui 9.1 for L21X / your phone?

**Comment by cMonedula** [comment]
i'm not exactly sure but i think the L21 firmware did the trick for me. the thing is the phone asks me to connect to wifi (doesn't let me skip, says something about my installation being compromised or so) but i can't enter the wifi password so i'm kind of stuck there... should i try to recover through hisuite or something?

**Comment by ProfessorJTJ** [comment]
> i'm not exactly sure but i think the L21 firmware did the trick for me. the thing is the phone asks me to connect to wifi (doesn't let me skip, says something about my installation being compromised or so) but i can't enter the wifi password (that weird google voice thing, there are also no bottom navigation buttons/gesture controls so i'm kind of stuck there... should i try to recover through hisuite or something?

HiSuite might not be able to recovery, because it can only re-flash the firmwares you already have, I would suggest try the dload you download and tested before, as you're on EMUI 9.1 now, it might succeed.

Yeah the installation is most possibly corrupted due to L21 being on L21X

**Comment by ProfessorJTJ** [comment]
Edit:
You can try to install the firmwares I gave for L21X using recovery mode... ( might work because all the versions are newer than L21's firms )

First, Modify HiSuite's HiSuiteConfig.xml file, it can be found at:
C://Users/Your System username/App data/Local/HiSuite/userdata/UpdateDogDev

Add your phone model ( JSN-L21X ) under <Phone> tag of <REGION name="Default">

Then boot your phone into fastboot, connect to PC, fill firmwares in HiSuite Proxy as:

JSN-LGRP2-OVS 9.1.0.293 : https://www.firmfinder.ml/379018

JSN-L21-CUST 9.1.0.2(C431) : https://www.firmfinder.ml/374047

JSN-L21X-PRELOAD 9.1.0.1(C431R1) : https://www.firmfinder.ml/374046

then choose "OS Type" in HiSuite Proxy as "Recovery OS" tick "Force Auth Bridge" and finally click on System Recovery in HiSuite.

( For the first time HiSuite might override the HiSuiteConfig.xml file, so re modify it, and re-try, good luck! )

**Comment by cMonedula** [comment]
the phone works just fine after the recovery update, camera and all! thank you so much, i appreciate your help a lot and while i can't do much i'll be happy to contribute some coffee money to your brave creator thingy :D

**Comment by ProfessorJTJ** [comment]
> the phone works just fine after the recovery update, camera and all! thank you so much, i appreciate your help a lot and while i can't do much i'll be happy to contribute some coffee money to your brave creator thingy :D

Congratulations, so happy to hear that.

Nah just enjoy your phone, my country is under heavy sanctions I can't do much with abroad payments, so don't waste them.

Congratulations once again 😎
