### ISSUE TITLE
HiSuite or HiSuite-Proxy program

### ISSUE THREAD

**Issue by maksym86** [ProfessorJTJ/HISuite-Proxy#65]
Good day!  Please help me how to roll back the firmware to the previous version (via the HiSuite or HiSuite-Proxy program
![20210602_004522](https://user-images.githubusercontent.com/85182395/120352746-11432800-c33c-11eb-8c47-55a7aed56457.jpg)
![20210602_005021](https://user-images.githubusercontent.com/85182395/120353167-71d26500-c33c-11eb-9a68-c6b8dd3c5214.jpg)

).  Google services don't work at all.  Huawei honor 8x phone.  Many thanks

Добрый день! Помогите пожалуйста мне как откатить прошивку на предыдущию версию (через программу HiSuite или HiSuite-Proxy). Сервисы Гугл не работают вообще. Телефон Huawei honor 8x . Большое спасибо.

**Comment by ProfessorJTJ** [comment]
8.2.0.118 is old enough?

https://www.firmfinder.ml/167938

Click on add rom

Set "os type" in hisuite proxy as "Rollback OS"

Tick the box "Old Firmware" (EMUI 8)
