### ISSUE TITLE
MATE40PRO+  how to roll back the firmware to the previous version?

### ISSUE THREAD

**Issue by tigercgy** [ProfessorJTJ/HISuite-Proxy#66]
MATE40 PRO+ , fireware is  11.0.177(C00E171R7P1) ，how to roll back to 11.0.135? 

I use HiSuite-Proxy 2.3.7 &  HiSuite 11.0.530OVE，download firmware successfully，but when phone verify over，rollback failed, cannot flashback previous firmware。help me, thank you very much!

**Comment by ProfessorJTJ** [comment]
Some firmwares don't support rollback....

Send your log file, it can be found at:
C:/Users/Your User Name/App Data/Local/HiSuite/Logs/systemupdate.log

**Comment by tigercgy** [comment]
[SystemUpdate_20210601_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6585196/SystemUpdate_20210601_00.log)

log file has been uploaded!  I wonder if  all series of mate40  is not supported to rollback？BUT, I test p40pro+ is ok !

**Comment by ProfessorJTJ** [comment]
Everything is going fine, probably Version 11.0.0.177 does not support rollback.

You can try to:
Include only the base file https://www.firmfinder.ml/500693
Keep OS Type as Normal

Update.

You might need to do data & cache wipe if it succeeds. ( partition will be corrupted, wiping data and cache will fix it )

**Comment by tigercgy** [comment]
I try as as mentioned above, but it still failed.  the log file is below

**Comment by tigercgy** [comment]
I find that my phone model（mate40 series) isn't  in  HiSuiteConfig.xml.
shoud  I add an entry for my phone model?

**Comment by ProfessorJTJ** [comment]
You don't need it, that's only for system recovery when a phone is soft bricked and doesn't boot.

The firmware on your phone blocks rollbacks to older versions unfortunately we cannot do anything about it because Huawei made it like that to avoid rollbacks

**Comment by tigercgy** [comment]
> You don't need it, that's only for system recovery when a phone is soft bricked and doesn't boot.
> 
> The firmware on your phone blocks rollbacks to older versions unfortunately we cannot do anything about it because Huawei made it like that to avoid rollbacks

oh，_it's  so sad ！ But  I have a idea， first I upgrade to hongmeng OS； then, I use Hisute proxy downgrade to 11.0.135。Can I rollback in this way?

**Comment by tigercgy** [comment]
hello  Professor, good morning! May I ask a question?
What's the function of HiSuite Proxy's Authentication bridge? 
Shoud I check  this item（Force Auth Bridge), and then I hope it will going fine?

**Comment by ProfessorJTJ** [comment]
> hello Professor, good morning! May I ask a question?
> What's the function of HiSuite Proxy's Authentication bridge?
> Shoud I check this item（Force Auth Bridge), and then I hope it will going fine?

I'm not quite sure but in case Huawei made the anti rollback through the authentication, it will work, you can try it out

**Comment by tigercgy** [comment]
> > hello Professor, good morning! May I ask a question?
> > What's the function of HiSuite Proxy's Authentication bridge?
> > Shoud I check this item（Force Auth Bridge), and then I hope it will going fine?
> 
> I'm not quite sure but in case Huawei made the anti rollback through the authentication, it will work, you can try it out

Thanks a lot for your help!  I will try it.  by the way, if  failed again(check Force Auth Bridge), will the phone be soft bricked?

**Comment by ProfessorJTJ** [comment]
> > > hello Professor, good morning! May I ask a question?
> > > What's the function of HiSuite Proxy's Authentication bridge?
> > > Shoud I check this item（Force Auth Bridge), and then I hope it will going fine?
> > 
> > 
> > I'm not quite sure but in case Huawei made the anti rollback through the authentication, it will work, you can try it out
> 
> Thanks a lot for your help! I will try it. by the way, if failed again(check Force Auth Bridge), will the phone be soft bricked?

No, if it fails it won't soft brick, if it succeeds and you chose os type as "update" it will say partition corrupted and ask you to wipe cache and data, after you do everything will be fine

**Comment by tigercgy** [comment]
It still failed.  Force Auth Bridge didn't work 。when the phone verify  to 4%，the screen display "update failed", must reboot device.

**Comment by chenz97** [comment]
> It still failed. Force Auth Bridge didn't work 。when the phone verify to 4%，the screen display "update failed", must reboot device.

Same error. verification failed at 4%. I suspect a hardware error.
