### ISSUE TITLE
Huawei Mate 30 Pro, Google Service

### ISSUE THREAD

**Issue by mike0155** [ProfessorJTJ/HISuite-Proxy#67]
Hello
Can I install Google Service or it is no longer possible now? I couldn't install Google Play on the Mate 30 Pro. Error message is - the device is not Play protect certified. Google has a list of certified devices, Mate 30 Pro is not listed. (see appendix) Can I display my device as another device (Mate 20 Pro) when connected to GSM? Thanks.
![Screenshot_20210601_231455_com google android gms](https://user-images.githubusercontent.com/85336021/120770371-5cb52c00-c51e-11eb-8145-45273e290012.jpg)

**Comment by ProfessorJTJ** [comment]
https://www.youtube.com/watch?v=CdYpZlXlgOQ

**Comment by mike0155** [comment]
I did 3 times as in video, for about a few minutes Google, Google Play worked, then the error message: "This device is not certified for Play Protect." What else can I do? I think I don't have any more Schans. What could i do wrong?
"For Huawei Mate 30 Pro need to downgrade to firmware 136",  i have firmware 134!!!

1. Base 11.0.0.180;  2. Base 10.1.0.270;   3. Base 10.0.0.134; 

![1_mal](https://user-images.githubusercontent.com/85336021/121604640-32e29480-ca4b-11eb-88fe-0f9e37c81576.jpg)
![2_mal](https://user-images.githubusercontent.com/85336021/121604644-3413c180-ca4b-11eb-8790-33ed06894014.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/85336021/121604645-34ac5800-ca4b-11eb-9b8e-1f2c3d52b371.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/85336021/121604647-3544ee80-ca4b-11eb-9362-2a5c838777b2.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/85336021/121604648-35dd8500-ca4b-11eb-8519-1b55e411713f.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/85336021/121604652-35dd8500-ca4b-11eb-87ca-ec8af88a9483.jpg)
![Start](https://user-images.githubusercontent.com/85336021/121604653-370eb200-ca4b-11eb-865c-cf1bd5007d40.jpg)
