### ISSUE TITLE
P40 pro unable to downgrade using hisuite proxy

### ISSUE THREAD

**Issue by sekhar515** [ProfessorJTJ/HISuite-Proxy#69]
Hi sir, My EMUI build number is 11.0.0.183 and I'm trying to downgrade to EMUI10 to install GMS. I was able to follow all the steps and was able to reach the download step. after downloading 100 % Hisuite throwed me error "Failed to Update". I used firmware finder site to get the base version ELS-LGRP4-OVS 10.1.0.182 , Custom ELS-N29-CUST 10.1.0.8(C636) & preload ELS-N29-PRELOAD 10.1.0.1(C636R5). I need to downgrade back to 10 for GMS which is very important for me as of now. Please help me sir. You help is much appreciated.

note: unable to install latest Hisuite no error nothing but not getting installed. Using hiSuite 10.0.1.100. No option for switch to old rom. I used HiSuite proxy and tried to downgrade.

**Comment by ProfessorJTJ** [comment]
Hi, there is a box in hisuite proxy called "Force Auth Bridge" tick it and try again

Send your log file in where in case the issue still not fixed
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by sekhar515** [comment]
Hi Sir,

Below are the system logs for Hisuite:
[SystemUpdate_20210612_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6641252/SystemUpdate_20210612_00.log)

Previously tried system log is attached below:
[SystemUpdate_20210611_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6641253/SystemUpdate_20210611_00.log)

Thanks for prompt response, hope I can downgrade and install GMS on mobile.

**Comment by ProfessorJTJ** [comment]
Hey, am so sorry for the delay, I just had a lottttt going on in here....
anyway, you need HiSuite 10.1 or 11 to be able to flash roms on EMUI 11 phones

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by sekhar515** [comment]
Thank you for the response sir. I'M unable to install anything higher than 10.0.0.100 on my laptop.  It never shows any error just it extracts and when i click on install ask for confirmation and nothing happens after that. Tried multiple times and tried in multiple operating systems too. Installed on windows 7 with no luck and for the sake of hisuite i formated my laptop lost all data and installed windows 10 too with no luck.

Any  suggestions please to get latest version installed on my laptop any tricks. Thanks in advance

**Comment by ProfessorJTJ** [comment]
I have never encountered such problem, unfortunately I'm clueless.

I've attached HiSuite 11's apk file, try to:
Connect phone to pc
Let HiSuite Enter password dialog open
Install the new APK File
Open HiSuite in your phone
Enter the password in HiSuite

I'm not sure if this is going to work, but no problem with giving it a shot, right?

[HiSuite.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643396/HiSuite.zip)

**Comment by sekhar515** [comment]
Sir, thank you I was able to fix he installation issue from Google after installing visiual c++ 2015 redritributable file.

Now I have a big problem, I downgraded the software to 132 and now my mobile is restarting every 20 seconds, If I try to do anything like changing the settings etc it reboots. Unable to install another firmware as it rebooting and diconnecting.

Tried resetting to factory defaults and no change same problem of restarting, tried from safe mode to same problem.

Is their any way to fix this please?

**Comment by ProfessorJTJ** [comment]
Send the latest log
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log


I think you have installed another model's firmwares...

**Comment by sekhar515** [comment]
[SystemUpdate_20210613_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643694/SystemUpdate_20210613_00.log)
Hi Sir, 
 
attached the log file

Hope there will be some solution apart from service.

I think installed the correct version mentioned to my c636 model.

**Comment by sekhar515** [comment]
Moreover, wifi keeps disconnecting after the reboot and also it never recognized the sim card available in phone shows no service.

I can access fastboot mode and also recovery mode using volume buttons fastboot with volume down button and recovery reset using volume up button.

**Comment by ProfessorJTJ** [comment]
You have installed LGRP6 base on your LGRP4 phone...

**Comment by sekhar515** [comment]
So no option to roll back Sir?

**Comment by ProfessorJTJ** [comment]
Basically you have installed P40 Pro+ firmware on P40 Pro
I don't know if system recovery will be able to fix this

C://Users/Your System username/App data/Local/HiSuite/userdata/UpdateDogDev

Open the file "HiSuiteConfig.xml"

Add your phone model below <REGION name="Default"> and <REGION name="China"> ( ELS-N29 )

Add base, cust preload of N29, LGRP4
Choose os type as "Recovery OS", tick Force Auth Bridge box, boot phone into fastboot, connect, click recover in hisuite, 

You might need to modify the file again ( adding your phone model ) if it showed that your device is not supported.

**Comment by sekhar515** [comment]
[code.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643730/code.txt)
Sir,

If you dont mind can you check whether I added correctly:

"Add your phone model below <REGION name="Default"> and <REGION name="China"> ( ELS-N29 )"

I attached the entire code, where I added <rule type="ELS-N29" cnName="HUAWEI P40 Pro" enName="ELS-N29" option="" ></rule>

Just want t make sure its correct. I'm really sorry for troubling you like this

Thanks in advance, If you change the code I will just copy ate in te config file, Your help is much appreciated Sir.

**Comment by ProfessorJTJ** [comment]
> [code.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643730/code.txt)
> Sir,
> 
> If you dont mind can you check whether I added correctly:
> 
> "Add your phone model below and ( ELS-N29 )"
> 
> I attached the entire code, where I added
> 
> Just want t make sure its correct. I'm really sorry for troubling you like this
> 
> While i clicked on recovery before editig the code, it said the device doesn't support recovery, contact service center.
> 
> Thanks in advance, If you change the code I will just copy ate in te config file, Your help is much appreciated Sir.

I'm on phone so I cannot modify it, but you added your model under China region, but did not add it under \<REGION name="Default"\>

**Comment by sekhar515** [comment]
Thank you Sir,

I added <rule type="ELS-N29" cnName="HUAWEI P40 Pro" enName="ELS-N29" option="" ></rule>
this code under <REGION name = "Default".

Added LGRP4 base file, along with custom and preloaded which I didnt change as they are for supporting model.

Selected recovery OS and connected my hone in fastboot mode. Should I just go ahead and open the Hi Suite software >> Click on System Recovery"?

**Comment by tigercgy** [comment]
原来楼主把P40PRO+的固件刷到P40PRO手机里了...

**Comment by ProfessorJTJ** [comment]
> Thank you Sir,
> 
> I added
> this code under <REGION name = "Default".
> 
> Added LGRP4 base file, along with custom and preloaded which I didnt change as they are for supporting model.
> 
> Selected recovery OS and connected my hone in fastboot mode. Should I just go ahead and open the Hi Suite software >> Click on System Recovery"?

Yup, also don't forget to tick the box "Force Auth Bridge"

**Comment by sekhar515** [comment]
Sir,

I did exactly what you have infomed and by selecting the Force Auth Bridge too.

After downloading and Decompress >> device restarted from the fastboot mode and the installation recovery went to 10 % and got error "recovery Failed" on Hisuite and "Software install Failed" on my mobile.

Please help me where I went wrong?

**Comment by ProfessorJTJ** [comment]
> Sir,
> 
> I did exactly what you have infomed and by selecting the Force Auth Bridge too.
> 
> After downloading and Decompress >> device restarted from the fastboot mode and the installation recovery went to 10 % and got error "recovery Failed" on Hisuite and "Software install Failed" on my mobile.
> 
> Please help me where I went wrong?

Probably because you have LGRP6 on LGRP4 recovery will not work, but your lsat hope is, try HiSuite 11

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.6/HiSuite_11.0.0.530_OVE.rar

**Comment by sekhar515** [comment]
Should I follow same procedure installing Hisuite 11?

**Comment by ProfessorJTJ** [comment]
> Should I follow same procedure installing Hisuite 11?

Just after clicking "Setup" don't open the green hisuite, there will be a red icon HiSuite on desktop named HiSuite 11.exe, you have to open this one

**Comment by sekhar515** [comment]
Hi Sir,

Same issue again with HiSuite 11, did everything and downloaded >> De compress > Installation when to 100 % directly from 5% and showed "recovery Failed" on Hisuite and "Software install Failed" on my mobile.

[SystemUpdate_20210613_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643811/SystemUpdate_20210613_00.log)
Attached the log

So I think I'm done with all possible steps right Sir?

Do you have any other solution like installing other ROM etc?

**Comment by ProfessorJTJ** [comment]
> Hi Sir,
> 
> I used the red hisuite shortcut from desktop
> 
> Same issue again with HiSuite 11, did everything and downloaded >> De compress > Installation when to 100 % directly from 5% and showed "recovery Failed" on Hisuite and "Software install Failed" on my mobile.
> 
> [SystemUpdate_20210613_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6643811/SystemUpdate_20210613_00.log)
> Attached the log
> 
> So I think I'm done with all possible steps right Sir?
> 
> Do you have any other solution like installing other ROM etc?

Unfortunately, I guess you need to take the phone to Huawei's customer service....

**Comment by sekhar515** [comment]
Okay, Thanks for your support Sir, learnt so many things. Thank you so much

**Comment by sekhar515** [comment]
Sir,

Sorry again, but I took it to service center in my place and they are saying its international version and cant get serviced in India as its not released in India. Now am completely stuck sir, Please help me with any solution if you have to fix this even if it not tested properly. I need this device Sir, I purchased with all my savings and it just gone like that in search of Google services

**Comment by ProfessorJTJ** [comment]
> Sir,
> 
> Sorry again, but I took it to service center in my place and they are saying its international version and cant get serviced in India as its not released in India. Now am completely stuck sir, Please help me with any solution if you have to fix this even if it not tested properly. I need this device Sir, I purchased with all my savings and it just gone like that in search of Google services

Contact this service, they might be able to help you

https://ministryofsolutions.com/

**Comment by Topmovil** [comment]
Hi! I've a similar issue. The same phone, and when I click on search update it says I've the lastest official one and doesn't gets the linked on Hisuite Proxy. 

I'm using the provided Hisuite 10.1.1.550 and your latest app.

Regards,

**Comment by ProfessorJTJ** [comment]
> Hi! I've a similar issue. The same phone, and when I click on search update it says I've the lastest official one and doesn't gets the linked on Hisuite Proxy.
> 
> I'm using the provided Hisuite 10.1.1.550 and your latest app.
> 
> Regards,

Attach a screenshot from hisuite proxy at least.

**Comment by Topmovil** [comment]
![SCREENSHOT](https://user-images.githubusercontent.com/85999418/122216363-9c7bfc00-ceac-11eb-8558-3a907753c0b1.JPG)
Here it is!

**Comment by Topmovil** [comment]
I'm on EMUI 10.1.0.183 atm.

Regards,

**Comment by ProfessorJTJ** [comment]
> ![SCREENSHOT](https://user-images.githubusercontent.com/85999418/122216363-9c7bfc00-ceac-11eb-8558-3a907753c0b1.JPG)
> Here it is!

The link you have is invalid and apparently taken from team-mt firmfinder which no longer works.

find your firmware in here and click on "Add Rom"
https://www.firmfinder.ml/

**Comment by Topmovil** [comment]
Thank you! It worked like a charm! I'm downloading update now :-)

**Comment by sekhar515** [comment]
Sir just need some info. I was able to get back my mobile to older version. Thanks for your reference. Installed GMS with lot of effort.  There is an update pooing up? Should I go ahead and update? Will I lose GMS??
Thanks in advance

**Comment by ProfessorJTJ** [comment]
> Sir just need some info. I was able to get back my mobile to older version. Thanks for your reference. Installed GMS with lot of effort. There is an update poping up? Should I go ahead and update? Will I lose GMS??
> Thanks in advance

You are welcome, happy to hear that it's fixed, OTA updates don't wipe your data, no you will not lose Google services, you can still have GSM on emui 11 too, but if you logout or remove them you will need to rollback to install gsm again

**Comment by sekhar515** [comment]
Thank you sir.  Upgraded and some apps working fine but few are working only on mobile network. While I turn on airplane mode and on the WiFi I can access all apps without issue but when I turn off the airplane mode.. I can't access some apps as they just keep on loading that's it (same apps working fine with WiFi and airplane mode on)
Is this upgrade or Gms issue?

**Comment by sekhar515** [comment]
Done
