### ISSUE TITLE
Group version not match error

### ISSUE THREAD

**Issue by tunasahinn** [ProfessorJTJ/HISuite-Proxy#7]
![image](https://user-images.githubusercontent.com/49642331/86897088-a2e7ec80-c10f-11ea-9560-eb719337271b.png)

I'm trying to update my P20 lite (ANE-LX1), but proxy isn't work. Says ''group version not match''. Here is the update link: http://update.dbankcdn.com/TDS/data/files/p3/s15/G3948/g1755/v414674/f1/full/update_full_base.zip

**Comment by ProfessorJTJ** [comment]
You need to add CUST and Preload packages of the desired package.
After you add CUST and Preload Urls, tick the boxes "CUST PKG" and "Preload PKG"

**Comment by tunasahinn** [comment]
Ah thank you so much, now installing :D I have a request, can you send language files (if available). I want to translate it to Turkish.

**Comment by ProfessorJTJ** [comment]
> Ah thank you so much, now installing :D I have a request, can you send language files (if available). I want to translate it to Turkish.

I didn't add the messages in a special file, so unfortunately it's not easy to get them all out and replace them, however, good idea, I will add this feature, where it would load it's language from a special file beside it. ( perhaps tomorrow as I'm already exhausted today )

**Comment by COLOMBIANBOY** [comment]
hi proffesor  I'm presenting the same problem but I want to know where I get the information from: the CUST and Preload packages from the desired base.
