### ISSUE TITLE
HP only finds one out of three ZIPs from filelist.xml - CMR-AL09C432B161(8.0.0.161) - 147412

### ISSUE THREAD

**Issue by newbit1** [ProfessorJTJ/HISuite-Proxy#70]
Hi,

when I try to Download and install the Firmware CMR-AL09C432B161(8.0.0.161) - [147412](https://www.firmfinder.ml/147412)
Hisuite Proxy only shows weird Version Number and doesn't download all the three packages from the [filelist.xml](http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/7a/v3/a07256d662e241b6afaa27d41de92334/full/filelist.xml)
It only downloads the update_full_CMR-AL09_hw_eu.zip (560MB)
But they are definitely there!!
[update.zip](http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/7a/v3/a07256d662e241b6afaa27d41de92334/full/update.zip)
[update_data_full_public.zip](http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/7a/v3/a07256d662e241b6afaa27d41de92334/full/public/update_data_full_public.zip)
[update_full_CMR-AL09_hw_eu.zip](http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hotaMigrate_900_9/7a/v3/a07256d662e241b6afaa27d41de92334/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip)

Same result with Force Auth Bridge ticked.

Is there any way I can fix this myself? On Oreo it doesn't has CUST and Preload.
Without HP I could officially downgrade from CMR-AL09 9.0.1.161 to CMR-AL09 8.0.0.196, and then
via sd_update to CMR-AL09 8.0.0.192.

Thanks in Advance
Cheers
NewBit

<details>
<summary>Logs</summary>

```
HTTPS://query.hicloud.com:443/sp_dashboard_global/UrlCommand/CheckNewVersion.aspx
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog/changelog_base_hw_eu.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog.xml
HTTPS://query.hicloud.com:443/BL/v1/VersionCheck
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog/changelog_base_hw_eu.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog.xml
HTTPS://query.hicloud.com:443/BL/v1/VersionCheck
HTTPS://query.hicloud.com:443/sp_ard_common/v1/authorize.action
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog/changelog_base_hw_eu.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog.xml
HTTPS://query.hicloud.com:443/BL/v1/VersionCheck
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTPS://query.hicloud.com:443/sp_ard_common/v2/onestopCheck.action?latest=true
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/filelist.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog/changelog_base_hw_eu.xml
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/changelog.xml
HTTPS://query.hicloud.com:443/BL/v1/VersionCheck
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip
HTTP://update.dbankcdn.com:80/download/data/pub_13/HWHOTA_hotaMigrate_900_9/d5/v3/91b3b882ca4144be91fb31a6eece1a05/full/CMR-AL09_hw_eu/update_full_CMR-AL09_hw_eu.zip
HTTPS://query.hicloud.com:443/sp_ard_common/v1/authorize.action

```
</details>

<img src="https://user-images.githubusercontent.com/37043777/122175111-a5a4a300-ce83-11eb-8bba-69d1951fde0b.png" height="200" />
<img src="https://user-images.githubusercontent.com/37043777/122175112-a63d3980-ce83-11eb-9159-48bb791db1cd.png" height="200" />

**Comment by ProfessorJTJ** [comment]
Hi, there is a box named named "Old Firmware" be sure to tick it.

**Comment by newbit1** [comment]
> 
> 
> Hi, there is a box in HiSuite Proxy named "Old Firmware" be sure to tick it.

Thanks, this worked! Sorry, I didn't notice that tick box before.
It doesn't install the Firmware though, but this might be an unrelated issue.

Thanks

**Comment by ProfessorJTJ** [comment]
> > Hi, there is a box in HiSuite Proxy named "Old Firmware" be sure to tick it.
> 
> Thanks, this worked! Sorry, I didn't notice that tick box before.
> It doesn't install the Firmware though, but this might be an unrelated issue.
> 
> Thanks

Unfortunately even though the package is full ota, if it doesn't match your current version, Huawei prevents the installation

**Comment by newbit1** [comment]
> Unfortunately even though the package is full ota, if it doesn't match your current version, Huawei prevents the installation

I figured that in the oeminfo partition were a few Versions listed.
CMR-AL09 9.1.0.333, CMR-AL09 9.0.1.161 and CMR-AL09 8.0.0.196
So I could downgrade via sd_update (dload) in forced upgrade mode to 9.0.1.161
And then in normal Hisuite it let me downgrade to 8.0.0.196.
Again, I could downgrade via sd_update (dload) in forced upgrade mode to 8.0.0.192.
My goal is to go down to 8.0.0.161 or even lower. But this is the lowest sd_update Package I could find.

I didn't dare to manipulate the oeminfo string yet.
