### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Herbertas11** [ProfessorJTJ/HISuite-Proxy#71]
So i want to downgrade my firmware to the version where i can use gms.
I use this https://www.firmfinder.ml/409481 for the proxy it was given to you back when i did this like 4 month ago.
Now i try using this and it shows me an error on the proxy
![image](https://user-images.githubusercontent.com/83340438/122819488-3562ab00-d2e3-11eb-8443-6559cdfd64c3.png)
![image](https://user-images.githubusercontent.com/83340438/122819504-3b588c00-d2e3-11eb-9972-fd4412a00b1f.png)
BTW I tried using force auth bridge but it still comes up with an error.
I want to put my phone to ELS-LGRP4-OVS 10.1.0.131 - C432 version or if there is a better one that i can still use to download the google apps.

**Comment by ProfessorJTJ** [comment]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
