### ISSUE TITLE
problema para actualizar p30 ele-l04 c605

### ISSUE THREAD

**Issue by canabigore** [ProfessorJTJ/HISuite-Proxy#74]
amigo perdon tengo este problema cuando esta configurando el hisuiteproxi

![hisuiteproxi failed](https://user-images.githubusercontent.com/87135289/124936068-d469f100-dfcb-11eb-93c1-8bb169c5d3c2.jpg)

**Comment by ProfessorJTJ** [comment]
Install this HiSuite
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by canabigore** [comment]
disculpa ahora me salio esto :/   ![fail rebranded](https://user-images.githubusercontent.com/87135289/124941633-8efbf280-dfd0-11eb-8914-1ee564a8df91.jpg)

**Comment by ProfessorJTJ** [comment]
> disculpa ahora me salio esto :/ ![fail rebranded](https://user-images.githubusercontent.com/87135289/124941633-8efbf280-dfd0-11eb-8914-1ee564a8df91.jpg)

Click on Accept

**Comment by ProfessorJTJ** [comment]
You're welcome 👍🏻
