### ISSUE TITLE
Connection To HISuite Proxy Failed....

### ISSUE THREAD

**Issue by ciorax20** [ProfessorJTJ/HISuite-Proxy#76]
![image](https://user-images.githubusercontent.com/87233719/125164528-6d9b3200-e19b-11eb-89d9-b536c969447c.png)
Hello, i have this error, when i try to downgrade mate 30 pro.

**Comment by ProfessorJTJ** [comment]
Nice background wallpaper.

Open command prompt and enter the command
netstat -a -b

See which application is using port 7777, close it's task from Task Manager.

**Comment by ciorax20** [comment]
> Nice background wallpaper.
> 
> Open command prompt and enter the command
> netstat -a -b
> 
> See which application is using port 7777, close it's task from Task Manager.

Thanks you so much. But i found the port 7777 has been used by ASUSLINK, i have stoped from task, and now is still there.

![image](https://user-images.githubusercontent.com/87233719/125165069-ffa43a00-e19d-11eb-94ca-0eb38b9901d6.png)

**Comment by ProfessorJTJ** [comment]
> > Nice background wallpaper.
> > Open command prompt and enter the command
> > netstat -a -b
> > See which application is using port 7777, close it's task from Task Manager.
> 
> Thanks you so much. But i found the port 7777 has been used by ASUSLINK, i have stoped from task, and now is still there.
> 
> ![image](https://user-images.githubusercontent.com/87233719/125165069-ffa43a00-e19d-11eb-94ca-0eb38b9901d6.png)

There is a program which is restarting ASUSLIN, keep HiSuite Proxy open, then close ASUSLINK, so HiSuite proxy will take over the port.

**Comment by ciorax20** [comment]
i have done and still the same. im checking again netstat, and now i can see only this

![image](https://user-images.githubusercontent.com/87233719/125165572-2fecd800-e1a0-11eb-95b6-a96570e36148.png)

**Comment by ciorax20** [comment]
i have blocked also asus to connect on internet. and still the same. offf im crazyyyy 

I will try my best until i succed. Thank you so much.

**Comment by ProfessorJTJ** [comment]
> i have blocked also asus to connect on internet. and still the same. offf im crazyyyy
> 
> I will try my best until i succed. Thank you so much.

Usually on Asus laptops, "ArmouryCrateControlInterface.exe" is the one using port 7777, see if you close it any change will happen

**Comment by ciorax20** [comment]
> y on Asus laptops, "ArmouryCrateCon

Yes. Was that ArmouryCrate. But now next problem.
![image](https://user-images.githubusercontent.com/87233719/125171065-df36a880-e1ba-11eb-9182-642e5aa56d24.png)

**Comment by ciorax20** [comment]
> > i have blocked also asus to connect on internet. and still the same. offf im crazyyyy
> > I will try my best until i succed. Thank you so much.
> 
> Usually on Asus laptops, "ArmouryCrateControlInterface.exe" is the one using port 7777, see if you close it any change will happen

by the way, thank you SIr for helping me.

**Comment by ProfessorJTJ** [comment]
> > y on Asus laptops, "ArmouryCrateCon
> 
> Yes. Was that ArmouryCrate. But now next problem.
> ![image](https://user-images.githubusercontent.com/87233719/125171065-df36a880-e1ba-11eb-9182-642e5aa56d24.png)

Instead of the green hisuite, use the red one, it's on desktop named HiSuite 11.exe

![125165069-ffa43a00-e19d-11eb-94ca-0eb38b9901d6](https://user-images.githubusercontent.com/49002275/125171421-6c80f980-e1c9-11eb-875f-1833b96ec822.png)

**Comment by ciorax20** [comment]
Thank you so much Sir ProfessorJTJ , your support is very helpful!

**Comment by ciorax20** [comment]
But next is again problem. Doesnt show me other version!
Sorry to disturbing u!

![image](https://user-images.githubusercontent.com/87233719/125171809-dd6ee400-e1be-11eb-8ec6-a1500c6d7717.png)

**Comment by ProfessorJTJ** [comment]
> But next is again problem. Doesnt show me other version!
> Sorry to disturbing u!
> 
> ![image](https://user-images.githubusercontent.com/87233719/125171809-dd6ee400-e1be-11eb-8ec6-a1500c6d7717.png)

Take a picture from Hisuite proxy
You want to rollback to emui 10.1? You need to add base, cust and preload packages

**Comment by ciorax20** [comment]
Yes, i wanna install GMS services on mate 30 pro!

**Comment by ciorax20** [comment]
![image](https://user-images.githubusercontent.com/87233719/125173286-304c9980-e1c7-11eb-96b9-aa57f907e260.png)

**Comment by ciorax20** [comment]
But i dont have that button Switch to other version!

**Comment by ProfessorJTJ** [comment]
LIO-LGRP2-OVS 10.1.0.236 : https://www.firmfinder.ml/410125

LIO-L29-CUST 10.0.0.6(C432) : https://www.firmfinder.ml/316966

LIO-L29-PRELOAD 10.0.0.1(C432R8) : https://www.firmfinder.ml/351058


Open the links and click on "Add Rom*

**Comment by ciorax20** [comment]
Thank you so much Professor! God bless you and ur familly!

You are the best!

**Comment by ciorax20** [comment]
i have sent some love on fullclip39@gmail.com ! THank you
