### ISSUE TITLE
I keep get patch fail

### ISSUE THREAD

**Issue by Keith25cc** [ProfessorJTJ/HISuite-Proxy#77]
I get stuck for several time after the Patching Hisuite Files procedure

**Comment by ProfessorJTJ** [comment]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Keith25cc** [comment]
Wow it works tqvm Have A nice day  Sent from Mail for Windows 10 From: JTJSent: Monday, 26 July, 2021 12:52 AMTo: ProfessorJTJ/HISuite-ProxyCc: Keith25cc; AuthorSubject: Re: [ProfessorJTJ/HISuite-Proxy] I keep get patch fail (#77) Use hisuite 10.1https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
