### ISSUE TITLE
Downgrade P40 Pro does not work

### ISSUE THREAD

**Issue by sudoxroot** [ProfessorJTJ/HISuite-Proxy#78]
Hey,
I want to install GMS, unfortunately there are some problems.
If I try, HiSuite gives the error message "Failed to Update".
![image](https://user-images.githubusercontent.com/71279669/127655255-cdf2b1a6-c7b6-46b2-a787-a397c7b16f15.png)

I've already tried: 
- Force Auth Bridge ON/OFF
- HiSuite v10.1.0.510 / v10.1.0.550 / v11.0.0.550

Any idea?

**Comment by ProfessorJTJ** [comment]
Remove hisuite from your phone, install HiSuite 10.1 on your pc and try again with "Force Auth Bridge" ticked.

HiSuite 10.1
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

If no luck then send your log file, can be found at
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by sudoxroot** [comment]
The same problem as before

[SystemUpdate_20210730_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6907732/SystemUpdate_20210730_00.log)

**Comment by ProfessorJTJ** [comment]
> The same problem as before
> 
> [SystemUpdate_20210730_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6907732/SystemUpdate_20210730_00.log)

There's a box called "Debug Logging" in HiSuite proxy, tick it and retry then send the log which is generated in hisuite proxy folder under the name "log.txt"

**Comment by sudoxroot** [comment]
I already had it ticked .. Here's the log

[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6907824/logs.txt)

**Comment by ProfessorJTJ** [comment]
> I already had it ticked .. Here's the log
> 
> [logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6907824/logs.txt)

You have passed rom version ELS-LGRP4-OVS 10.1.0.131 as base, cust and preload, you are lucky that the authentication was failing, otherwise your phone was gonna hardly brick...

Open the links and click on "Add rom"

Base - ELS-LGRP4-OVS 10.1.0.131 : https://www.firmfinder.ml/409481
Preload - ELS-N29-PRELOAD 10.1.0.1(C432R6) : https://www.firmfinder.ml/409483
Cust - ELS-N29-CUST 10.1.0.7(C432) : https://www.firmfinder.ml/384705

**Comment by sudoxroot** [comment]
Thank you very much
it works
