### ISSUE TITLE
Hisuite11.0.0.320_OVE

### ISSUE THREAD

**Issue by google-mirror** [ProfessorJTJ/HISuite-Proxy#8]
"This file is already patched." But actually not and Hisuite says no network connection.

**Comment by ProfessorJTJ** [comment]
I guess that version of HISuite isn't supported by the app yet, go for version 10.1.0.550 instead

**Comment by google-mirror** [comment]
How can I patch the binary manually?

**Comment by ProfessorJTJ** [comment]
> How can I patch the binary manually?

It's not as easy as you might think, first you need IDA Pro application then you've to patch the codes, first searching for https connect function in the httpcomponent.dll file and disabling certification check which exists there 
And then you need to replace query.hicloud.com string which exists in that function, into anything but other than itself....

**Comment by google-mirror** [comment]
Is that function called NetWork::AppBaseHttpClient::verifyCommonName I should patch?

**Comment by ProfessorJTJ** [comment]
> [httpcomponent.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/5216795/httpcomponent.zip)
> Is that function called NetWork::AppBaseHttpClient::verifyCommonName I should patch?

No I reckon it was called httpsconnect or something similar
