### ISSUE TITLE
Sir, I want to know what the red region mean? Can I diselect it? What's more, Hisute update or downgrade always take many minutes, I mean the flash time, not the downloading time, so how can I fix it? Thanks!

### ISSUE THREAD

**Issue by ChiwenJ** [ProfessorJTJ/HISuite-Proxy#80]
![image](https://user-images.githubusercontent.com/57949247/128446429-be6fbd02-fae8-4e78-801d-923c1de5a98c.png)

**Comment by ProfessorJTJ** [comment]
During the "Installation" period, hisuite actually copies the rom files to your phone, if it's moving slowly, be sure that your usb cable is original and by the company.

"Point Version" is optional and has no effect on the installation.

**Comment by ChiwenJ** [comment]
Thanks a lot! I use a usb cable buied from 5 years ago and maybe that's the reason. Anymore, thanks again for your kindly help!
