### ISSUE TITLE
Unable to SETUP - `Pach failed`

### ISSUE THREAD

**Issue by f-mateusz89** [ProfessorJTJ/HISuite-Proxy#81]
I've trying to run it as an administrator.
OS: Windows 11 Pro, 10.0.22000
Is there any place with additional log information?

```
[12:29:08]: Patch failed, Aborting process....
[12:29:08]: Please Contact Developer If Error Continues
 ```

![image](https://user-images.githubusercontent.com/51092178/128693238-b3f62dec-1289-4082-846f-0ab1e72fc188.png)

**Comment by ProfessorJTJ** [comment]
Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
