### ISSUE TITLE
 Huawei P40Pro's quick charge  dosen’t work after switching system to EMUI 10.1 

### ISSUE THREAD

**Issue by RichengLiang** [ProfessorJTJ/HISuite-Proxy#82]
Hi, ProfessorJTJ!
Thank you for providing such a handy tool, but my  Huawei P40Pro's quick charge  dosen’t work when I switch the system from emui 11(version: 11.0.0.185) to emui 10.1(version:10.1.0.116). Besides, when I connect my p40pro to a computer, the phone can only be charged and cannot transfer files. As far as I know, this is also happening with other phones(such as Huawei mate30/PRO).  Do you know the reason for this situation ? 
Looking forward to your reply, thanks!

**Comment by superaitaotao** [comment]
@RichengLiang did you manage to resolve this issue? I can't supercharge my phone after downgrading to emui 10.1 as well.
