### ISSUE TITLE
HiSuite Proxy not working with Windows 11

### ISSUE THREAD

**Issue by grooverider2016** [ProfessorJTJ/HISuite-Proxy#83]
Hi

I have installed HiSuite Proxy and Hisuite 11.0.0.550_OVE and it fails when patching HiSuite. A manual patch says its unable to patch this version of HiSuite. I have tried using older version of HiSuite and also Older versions of HiSuite Proxy but same error each time.

**Comment by grooverider2016** [comment]
Phone is P40 Pro running EMUI 11 so i think needs to be running HiSuite 11 iirc

**Comment by ProfessorJTJ** [comment]
Try this hisuite

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
