### ISSUE TITLE
p40 Lite downgrade

### ISSUE THREAD

**Issue by fredericosilva22** [ProfessorJTJ/HISuite-Proxy#84]
Hello, I downgraded my P40 Lite, after updating the EMUI it didn't restart, is there any way to reset the EMUI without being able to access the mobile screen?

**Comment by ProfessorJTJ** [comment]
Did you add base, cust and preload packages or only base?

Did you choose OS type as Rollback Os or you kept it as Normal OS?

**Comment by fredericosilva22** [comment]
I tried to change the version to an old one through suiteprox, but I couldn't because errors appeared, so I downloaded version 10.1.0.136 and through a USB stick I did a software update on *#*#2846579#*#*

**Comment by ProfessorJTJ** [comment]
Recovery has a long procedure.

1. You need to modify a file.
C://Users/Your System username/App data/Local/HiSuite/userdata/UpdateDogDev/HiSuiteConfig.xml"

Add your phone model inside that file, under <REGION name="Default"

2. Boot into fastboot and connect your phone to pc

3. Click on recovery

4. Redo step 1

5. Read the log file
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Find what Base, cust and preload packages are installed. 


6. Find the 3 packages (base, cust and preload) in firmfinder

https://www.firmfinder.ml

7. Add the packages to HiSuite proxy

8. Choose OS Type as "Recovery OS" in HiSuite proxy.

9. Click on "recover" in HiSuite.

10. Good luck.

**Comment by fredericosilva22** [comment]
my problem is that the jny-lx1 version doesn't show up in the firmfinder, i tried with the jny-l21 but it gave an error halfway through the recovery in hisuite.

**Comment by ProfessorJTJ** [comment]
Then just connect your phone to the computer and use hisuite's recovery

In the file HiSuiteConfig.xml add all the models
JNY-L02 L22 L21 L01

Then check hisuite's log file to find out what model your phone is

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by fredericosilva22** [comment]
I'm really sorry for the work and time, but I don't know what's going wrong!

in hisuite when recovering the system gives error in step 3 when it reaches 99% in recovering.

on systemupdate the following information appeared, I don't know if the original or if it was the changes I made...
************************ full_recovery ************************ *
* udid:true
* VendorCountry:hw-me
* C_Version:C432
* D_version:D000
* DashBoard: 41.003.53.00.06
* DeviceName:JNY-L21
* packageType:full_recovery
* Firmware:
* FirmWare_Base:JNY-LGRP2-OVS 10.1.0.302
* FirmWare_Cust:JNY-L21-CUST 10.1.0.1(C432)
* FirmWare_Preload:JNY-L21-PRELOAD 10.1.0.1(C432R6)
* Language:
* OS:Android 10
* SaleInfo:

in hisuiteconfig I put it like this:
<rule type="JNY-L01" cnName="HUAWEI P40 Lite(JNY-L01)" enName="HUAWEI P40 Lite(JNY-L01)" option="" ></rule>
<rule type="JNY-L02" cnName="HUAWEI P40 Lite(JNY-L02)" enName="HUAWEI P40 Lite(JNY-L02)" option="" ></rule>
<rule type="JNY-L21" cnName="HUAWEI P40 Lite(JNY-L21)" enName="HUAWEI P40 Lite(JNY-L21)" option="" ></rule>
<rule type="JNY-L22" cnName="HUAWEI P40 Lite(JNY-L22)" enName="HUAWEI P40 Lite(JNY-L22)" option="" ></rule>

**Comment by fredericosilva22** [comment]
<rule type="JNY-L01" cnName="HUAWEI P40 Lite(JNY-L01)" enName="HUAWEI P40 Lite(JNY-L01)" option="" ></rule>
	    <rule type="JNY-L02" cnName="HUAWEI P40 Lite(JNY-L02)" enName="HUAWEI P40 Lite(JNY-L02)" option="" ></rule>
	    <rule type="JNY-L21" cnName="HUAWEI P40 Lite(JNY-L21)" enName="HUAWEI P40 Lite(JNY-L21)" option="" ></rule>
	    <rule type="JNY-L22" cnName="HUAWEI P40 Lite(JNY-L22)" enName="HUAWEI P40 Lite(JNY-L22)" option="" ></rule>

**Comment by fredericosilva22** [comment]
in hisuiteconfig I put it like this:

<rule type="JNY-L01" cnName="HUAWEI P40 Lite(JNY-L01)" enName="HUAWEI P40 Lite(JNY-L01)" option="" ></rule>
	    <rule type="JNY-L02" cnName="HUAWEI P40 Lite(JNY-L02)" enName="HUAWEI P40 Lite(JNY-L02)" option="" ></rule>
	    <rule type="JNY-L21" cnName="HUAWEI P40 Lite(JNY-L21)" enName="HUAWEI P40 Lite(JNY-L21)" option="" ></rule>
	    <rule type="JNY-L22" cnName="HUAWEI P40 Lite(JNY-L22)" enName="HUAWEI P40 Lite(JNY-L22)" option="" ></rule>

**Comment by ProfessorJTJ** [comment]
On what firmware your phone was?

Try different rom combination, for example these

FirmWare_Base:JNY-LGRP2-OVS 10.1.0.302
FirmWare_Cust:JNY-L21-CUST 10.1.0.1(C432)
FirmWare_Preload:JNY-L21-PRELOAD 10.1.0.1(C432R6)

And choose OS Type in hisuite proxy as Recovery os, then try to recover, it might succeed, if not try with emui 11 roms, find roms in here

https://www.firmfinder.ml

**Comment by fredericosilva22** [comment]
thank you my friend, it's solved, you're the greatest, next step is to install Google services in this version, I've done it in other older versions at the first attempt, that's what caused my previous problem, trying to downgrade!! Any idea?

**Comment by ProfessorJTJ** [comment]
> thank you my friend, it's solved, you're the greatest, next step is to install Google services in this version, I've done it in other older versions at the first attempt, that's what caused my previous problem, trying to downgrade!! Any idea?

You're on emui 11 and trying to downgrade?
You can use hisuite proxy to downgrade, just choose the base, cust and preload packages which you want from the website l
https://www.firmfinder.ml

And in hisuite proxy choose OS type as Rollback os

**Comment by fredericosilva22** [comment]
MY PHONE:
Model: JNY-LX1
compilation number: 10.1.0.302 (C432E1R6P1)
EMUI: 10.1.0
Android Version: 10


I tried it with Googlefier but it shows error, with GSpace but it's not the same thing, a lot of things don't work the same, because of Google Play services. with Googlefier it works if it's in version 10.1.0.111 , it's safe to rollback with HiSuite proxy to that version or I'll be without mobile again!

**Comment by ProfessorJTJ** [comment]
> MY PHONE:
> Model: JNY-LX1
> compilation number: 10.1.0.302 (C432E1R6P1)
> EMUI: 10.1.0
> Android Version: 10
> 
> I tried it with Googlefier but it shows error, with GSpace but it's not the same thing, a lot of things don't work the same, because of Google Play services. with Googlefier it works if it's in version 10.1.0.111 , it's safe to rollback with HiSuite proxy to that version or I'll be without mobile again!

Just be sure to add base, cust and preload packages and choose OS type as Rollback OS, it will most probably succeed the rollback.

**Comment by Rbeccari74** [comment]
Hola Frederico, solucionaste el problema con P40 lite?

**Comment by fredericosilva22** [comment]
Olá, não consegui porque depois de fazer o downgrade até ao fim, instalação
o EMUI e ao reiniciar bloqueou o P40 e nunca mais arrancou! Enviei para a
garantia e deram-me outro! Vtei a tentar de outra maneira diferente e
voltou a aconteceu o mesmo, voltei a enviar para a garantia e por sorte
reapraram-no e ficou como se origem novamente, sem os serviços da Google!!
Está ainda na caixa porque não sei como fazer sem o bloquear novamente!

Obrigado,
Frederico Silva

A terça, 17/05/2022, 02:28, Rbeccari74 ***@***.***> escreveu:

**Comment by Rbeccari74** [comment]
Hola Frederico, soy de Argentina, me pasó lo mismo pero yo logré volver a la versión EMUI 12 desde eRecovery (insistiendo, porque falló muchas muchas veces), ahora estoy utilizando GSpace. De todas maneras voy a intentar hacer Downgrade cuando tenga mi P20 pro que envié a cambiar batería a Chile. Lo que hice fue bajar una ROM stock oficial desde downloadgsm.com, solo por USD2. Estamos en contacto.

**Comment by Rbeccari74** [comment]
Yo había bajado de EMUI 12 a EMUI 10.0.1.167 (C605) y no me permitía utilizar USB ni OTG, ni actualizar desde el software. Al final logré volver al EMUI 12 desde eRecovery. Cuando lo intente nuevamente te aviso como resulta. Saludos.
