### ISSUE TITLE
Harmony 166 Downgrade questions

### ISSUE THREAD

**Issue by chinayinchunhui** [ProfessorJTJ/HISuite-Proxy#85]
Hello!
I use p40pro. Huawei blocked the downgrade after updating the Harmony 166 system. Now it can only be downgraded to 11.0.0.185 through the official assistant. Have you developed a new tool? Can I downgrade to a lower system as before? If you have relevant tools, you can send them to my email 923380724@qq.com

**Comment by ProfessorJTJ** [comment]
Hi, the same tool is supposed to work, downgrade to EMUI 11 then use HiSuite Proxy to downgrade to EMUI 10.1, you can find your desired firmwares on the website
https://firmfinder.ml/

**Comment by chinayinchunhui** [comment]
Hello!
I have tried. My current mobile phone uses the 11.0.0.185 system. I can download firmware using the 10.0.1.100 ove provided by you. When installing this software, you will be prompted that it is unable to connect to the network. Is it good to reflect that the USB fast charge will not work after degradation?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProfessorJTJ/HISuite-Proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProfessorJTJ/HISuite-Proxy] Harmony 166 Downgrade questions (#85)





 
Hi, the same tool is supposed to work, downgrade to EMUI 11 then use HiSuite Proxy to downgrade to EMUI 10.1, you can find your desired firmwares on the website
 https://firmfinder.ml/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ProfessorJTJ** [comment]
> Hello! I have tried. My current mobile phone uses the 11.0.0.185 system. I can download firmware using the 10.0.1.100 ove provided by you. When installing this software, you will be prompted that it is unable to connect to the network. Is it good to reflect that the USB fast charge will not work after degradation?

Use HiSuite 10.1 and install EMUI 10.1 NOT 10.0, your phone might brick, downgrade like this 11 -> 10.1 -> 10.0

Yes, fast charge and File Transfer gets disabled when you downgrade ( apparently its a new security procedure by Huawei )

HiSuite 10.1 -> https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by chinayinchunhui** [comment]
Hello!
Is there any way to solve Huawei's new complete strategy of disabling USB and fast charging?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProfessorJTJ/HISuite-Proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProfessorJTJ/HISuite-Proxy] Harmony 166 Downgrade questions (#85)





  
Hello! I have tried. My current mobile phone uses the 11.0.0.185 system. I can download firmware using the 10.0.1.100 ove provided by you. When installing this software, you will be prompted that it is unable to connect to the network. Is it good to reflect that the USB fast charge will not work after degradation?
  
Use HiSuite 10.1 and install EMUI 10.1 NOT 10.0, your phone might brick, downgrade like this 11 -&gt; 10.1 -&gt; 10.0
 
Yes, fast charge and File Transfer gets disabled when you downgrade ( apparently its a new security procedure by Huawei )
 
HiSuite 10.1 -&gt; https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ProfessorJTJ** [comment]
> Hello! Is there any way to solve Huawei's new complete strategy of disabling USB and fast charging?

Unfortunately I don't think, probably the only way is upgrading....

**Comment by chinayinchunhui** [comment]
Now I try to brush els-lgrp3-chn 11.0.0.180 to see if it can succeed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProfessorJTJ/HISuite-Proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProfessorJTJ/HISuite-Proxy] Harmony 166 Downgrade questions (#85)





  
Hello! Is there any way to solve Huawei's new complete strategy of disabling USB and fast charging?
  
Unfortunately I don't think, probably the only way is upgrading....
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinayinchunhui** [comment]
Hello!
I just tested it. You must upgrade to version 166 to restore the fast charging and USB options. Thank you for your guidance! If you develop new tools later, please send me! Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProfessorJTJ/HISuite-Proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProfessorJTJ/HISuite-Proxy] Harmony 166 Downgrade questions (#85)





  
Hello! Is there any way to solve Huawei's new complete strategy of disabling USB and fast charging?
  
Unfortunately I don't think, probably the only way is upgrading....
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by superaitaotao** [comment]
hi @ProfessorJTJ, I downgraded my Huawei Mate30 pro from EMUI 11 to EMUI 10.0... and now my USB is not working..
May I know how I can resolve this? I cannot upgrade my phone as well..

**Comment by ProfessorJTJ** [comment]
> hi @ProfessorJTJ, I downgraded my Huawei Mate30 pro from EMUI 11 to EMUI 10.0... and now my USB is not working..
> May I know how I can resolve this? I cannot upgrade my phone as well..
> 
> Thanks a lot!

Hey, the only way available to fix it is upgrading to latest available firmware.
Phone software update shows no update?
HiSuite doesn't detect the phone when connected to pc?
Enabling HDB and USB Debugging has no effect?

**Comment by superaitaotao** [comment]
yes..
phone shows no update
HiSuite doesn't detect the phone and my HiSuite version is 10.1.0
Yes, enabling HDB and USB debugging has no effect..
My version is 10.0.0.204 now

**Comment by ProfessorJTJ** [comment]
> hi @ProfessorJTJ thanks for replying!
> yes..
> phone shows no update
> HiSuite doesn't detect the phone and my HiSuite version is 10.1.0
> Yes, enabling HDB and USB debugging has no effect..
> My version is 10.0.0.204 now

Turn off your phone and boot into erecovery, see if you can upgrade your phone from there, if not then boot into fastboot and see if your pc recognises your phone. If it does, you can use hisuite's rescue mode to install a higher version on your phone

**Comment by superaitaotao** [comment]
> > hi @ProfessorJTJ thanks for replying!
> > yes..
> > phone shows no update
> > HiSuite doesn't detect the phone and my HiSuite version is 10.1.0
> > Yes, enabling HDB and USB debugging has no effect..
> > My version is 10.0.0.204 now
> 
> Turn off your phone and boot into erecovery, see if you can upgrade your phone from there, if not then boot into fastboot and see if your pc recognises your phone. If it does, you can use hisuite's rescue mode to install a higher version on your phone

thanks a lot @ProfessorJTJ, updating in the recovery mode works!

**Comment by saigonsouth-richard** [comment]
I found the solution for USB/Fastcharge disble issue for Harmony 2.0.0.165 downgrading.

**Comment by saigonsouth-richard** [comment]
1.    I just uses usb3.2 gen 2 cable with type c to c , and then the phone can be connect to computer/laptop to manipulate data transfer / upgrading / downgrading as normal...
2.   I used PD fastcharger with the usb3.2 c to c cable,  it can fastcharge for your phone as usual.

It works for all phones, hope it is useful/helpful for you !

**Comment by saigonsouth-richard** [comment]
> Hello! Is there any way to solve Huawei's new complete strategy of disabling USB and fast charging?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ProfessorJTJ/HISuite-Proxy" ***@***.***&gt;; 发送时间:&nbsp;2021年8月17日(星期二) 下午3:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ProfessorJTJ/HISuite-Proxy] Harmony 166 Downgrade questions (#85) Hello! I have tried. My current mobile phone uses the 11.0.0.185 system. I can download firmware using the 10.0.1.100 ove provided by you. When installing this software, you will be prompted that it is unable to connect to the network. Is it good to reflect that the USB fast charge will not work after degradation? Use HiSuite 10.1 and install EMUI 10.1 NOT 10.0, your phone might brick, downgrade like this 11 -&gt; 10.1 -&gt; 10.0 Yes, fast charge and File Transfer gets disabled when you downgrade ( apparently its a new security procedure by Huawei ) HiSuite 10.1 -&gt; https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I just posted the solution, hope it is helpful for you!
