### ISSUE TITLE
USB Transfer Files not work when downgrade to EMUI 10.1

### ISSUE THREAD

**Issue by ChiwenJ** [ProfessorJTJ/HISuite-Proxy#86]
I saw the last posted issues, and now I meet the same question.
I use Hisuite-Proxy to downgrade my mate 30 5G from EMUI 11.0.0.185 to EMUI 10.1.0.160, usb file transfer can not work, fast charge not be tesed because I don't have a super charger beside me. 
I have tried to upgrade to EMUI 11.00.0.176, the same problem exists. I will try to upgrade to EMUI 11.0.0.180 by wifi because usb can't work. Hope it will work when I upgrade to EMUI 11.0.0.180. Or maybe I need to upgrade to HarmonyOS. I will update this post when I have an answer.
Anymore, thanks ProfessorJTJ, thanks a pretty tool HISuite-Proxy. Maybe it's time to embrace HarmonyOS!

**Comment by ProfessorJTJ** [comment]
USB file transfer is required for hisuite to work? I don't think.... If you're testing on hisuite 11 try with Hisuite 10.1 incase you want to use hisuite proxy....

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by ChiwenJ** [comment]
No, I mean my phone can/t connect to PC with or without Hisuite. Even there is no a USB connect option, when I insert my cable to PC, it shows just charging.

**Comment by ChiwenJ** [comment]
EMUI 11.0.0.180 to HarmonyOS 2.0.0.133, USB file transfer function still not work when connect to PC, it shows just charging. When I update HarmonyOS 2.0.0.133 to 2.0.0.166, USB file transfer function(option) appearing when connect to PC. I don't test when downgrade from HarmonyOS 2.0.0.166 to EMUI 11.0.0.185 the USB file transfer option is still work or not. That's all.

**Comment by ChiwenJ** [comment]
EMUI 11.0.0.180 to HarmonyOS 2.0.0.133, USB file transfer function still not work when connect to PC, it shows just charging. When I update HarmonyOS 2.0.0.133 to 2.0.0.166, USB file transfer function(option) appearing when connect to PC. I don't test when downgrade from HarmonyOS 2.0.0.166 to EMUI 11.0.0.185 the USB file transfer option is still work or not. That's all.

**Comment by superaitaotao** [comment]
@ChiwenJ how did you resolve your USB issue?
I can't connect to PC as well..

**Comment by alvercheng** [comment]
@ChiwenJ  @ProfessorJTJ The same issue is happening, after downgrading to emui 10.1 the USB capability to trasnfer files to computer is gone, it wont read my device and rollback but I need to transfer files I need to restore back up from hisuite to my device but device wont read, usb capability is gone only charging mode, no option to change to file transfer in notif bar

and btw if ever that I restore my back ups from hisuite will it break the googlefier and google apps? or will it still work if i restore my backups like photos videos contact settings other apps (not including G apps)?
