### ISSUE TITLE
unable to install software after downgrade huawei p40 pro

### ISSUE THREAD

**Issue by SemekhinV** [ProfessorJTJ/HISuite-Proxy#88]
HI, sir. I apologize in advance for my English. I am trying to downgrade the firmware version following your advice. All the necessary files are downloaded and installed normally, but at the very moment of installing the firmware on the device, I get the error "Software installation failed". Attempts to return the device to factory settings and repeated installation attempts did not give results, can you help ?
[SystemUpdate_20210823_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7035013/SystemUpdate_20210823_00.log)

**Comment by ProfessorJTJ** [comment]
Hi, apparently you are choosing the firmwares incorrectly, you used C10 ( Russia ) CUST package along with C432 ( Europe ) Preload package, open these 3 links and just click on "Add Rom" don't copy any data manually....

ELS-LGRP4-OVS 10.1.0.131 : https://www.firmfinder.ml/410049
ELS-N29-PRELOAD 10.1.0.1(C10R6) : https://www.firmfinder.ml/410192
ELS-N29-CUST 10.1.0.6(C10) : https://www.firmfinder.ml/384579

**Comment by SemekhinV** [comment]
Thank you more for your answer, everything worked out.
