### ISSUE TITLE
I can't find software that works with my phone [NOT REALLY AN ISSUE]

### ISSUE THREAD

**Issue by Alex84152** [ProfessorJTJ/HISuite-Proxy#9]
I have a Huawei P20 EML-L09 (C792E15R1P11)

I try all cust/preload for C792 and nothing is working with my phone

Little look on what I tried:

preload 9.1.0.12 : http://update.dbankcdn.com/TDS/data/files/p3/s15/G4398/g1755/v332471/f1/full//update_full_preload_EML-L09_default_ca_R1.zip

preload 9.1.0.11: http://update.dbankcdn.com/TDS/data/files/p3/s15/G5029/g0/v280981/f1/full//update_full_preload_EML-L09_default_ca_R1.zip

cust 9.1.0.16 : http://update.dbankcdn.com/TDS/data/files/p3/s15/G4398/g1755/v332472/f1/full//update_full_cust_EML-L09_default_ca.zip

cust 9.1.0.11: http://update.dbankcdn.com/TDS/data/files/p3/s15/G3267/g1699/v278505/f1/full//update_full_cust_EML-L09_default_ca.zip

9.1.0.15 cust: http://update.dbankcdn.com/TDS/data/files/p3/s15/G5029/g0/v280989/f1/full//update_full_cust_EML-L09_default_ca.zip

9.1.0.316 base: http://update.dbankcdn.com/TDS/data/files/p3/s15/G5029/g0/v281028/f1/full/update_full_base.zip

9.1.0.311 base: http://update.dbankcdn.com/TDS/data/files/p3/s15/G5029/g0/v301974/f1/full//update_full_base.zip

9.1.0.327 base: http://update.dbankcdn.com/TDS/data/files/p3/s15/G4398/g1755/v294306/f1/full//update_base.zip

I would like to find a solution because my phone is still blocked on EMUI 9.0.

Best regards, Alex84152

**Comment by ProfessorJTJ** [comment]
Any firmware and base supposed to work it just has to be approved for installation by huawei (you can check that in the "advanced" section of the app)

**Comment by Alex84152** [comment]
I know and it's approved but when I update my phone the download stop at 50-99% and say no internet connection.

**Comment by ProfessorJTJ** [comment]
> I know and it's approved but when I update my phone the download stop at 50-99% and say no internet connection.

Perhaps your pc runs out of ram or similar problem is occurring. 
You can pre-download the roms and place them in HiSuite Folder in Documents, downloaded Roms get stored somewhere there, explore that folder and see where you have to put them, it will skip the download

**Comment by Alex84152** [comment]
Ah okay I'll look at this but otherwise for the download I do not believe that my pc is the cause because I have 16GB of RAM and my internet connection is very reliable.

**Comment by Alex84152** [comment]
Besides, I was wondering how we should choose the preload and cust versions? Should they be on the same version? Do one of them have to be newer than the other? It seems that for my model that the choices are very limited and then it is impossible to have them on the same version.
