### ISSUE TITLE
huawei P40 PRO PLUS downgrade error

### ISSUE THREAD

**Issue by trapezlus** [ProfessorJTJ/HISuite-Proxy#90]
tried downgrading using this video as reference https://www.youtube.com/watch?v=9qSD87TwUDw&t=160s
PERSONAL MOBLE INFO
-BASE- ELS-LGRP6-OVS 11.0.0.192
-CUST- ELS-N39-CUST 11.0.0.3(C432)
-PRELOAD- ELS-N39-PRELOAD 11.0.0.3(C432R3)
Just want to use googe on my phone,, please help
when adding rom and starting setup, it shows this-
[12:02:47]: Patch failed, Aborting process....
 [12:02:47]: Please Contact Developer If Error Continues
please help me @anmolbajaj211@gmail.com or rishibajaj79@yahoo.co.in

**Comment by ProfessorJTJ** [comment]
Hello, use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
