### ISSUE TITLE
Huawei Mate 20 Pro LYA-L09 bricked after downgrade, then Recovery OS Type worked but not anymore

### ISSUE THREAD

**Issue by Jukuuuuu** [ProfessorJTJ/HISuite-Proxy#92]
Hello professor,

Since March-April 2021, I wanted to upgrade my Mate 20 Pro (LYA-L29) from EMUI 10.1 to EMUI 11, but after trying everything, via Settings, My HUAWEI, HiSuite, eRecovery : it tells me that i'm up to date. I went on the official Huawei formum to ask a technical support, they tried to help me without any success.

Now, I am on vacation, so I decided that it was time to roll up my sleeves and try something myself.

I remembered that Huawei tells me that logically, I'm eligible for the update, but maybe I need to do a reset. So I backed up all my stuff through Hisuite, then I reset my phone... but I still can't update to EMUI 11.

So I rolled back from EMUI 10.1 to EMUI 10 via HiSuite, because it was the only "official" way to do something, everything went well... but I still can't update to EMUI 11, or even to EMUI 10.1...

Then, because it was always the only way to try something "legit", I rolled back my Mate 20 Pro from EMUI 10 to EMUI 9.1... At least I tried: at the end of the update, my phone was bricked (started directly into eRecovery mode).

eRecovery wanted to save me by installing a 10.0.0.180 version via WiFi... 

After telling me it was a success, the phone restarted with this message: "Your device has failed verification ans may not work properly."

![InkedH4sIAAAAAAAAAD2QzU7DMBCE38Xngrxexz-cmsSOygVxKOfKcZxgqU0rNwEB4t1xooi9fdrZndH8kPke0vHrFsgTAbIj3fVz3BAz9vEcXtxlwT499OkUL24IJ7oOAEjOlFDF420cNvWrm96z2ou85SJ4Bj33rW9ReMal7BhDnSmr2_j93GXpodyvvynlILSkeeVTcFO_LI](https://user-images.githubusercontent.com/25824315/131195971-d3751982-d2a4-4586-9092-f343d5a6b013.jpg)

So after hours of digging the Internet, I found your magical tool!!!

I used the OS Recovery function of HiSuite Proxy with HiSuite 10.0.1.100, with success (HiSuiteConfig.xml editing worked well, etc.) with these files:

LYA-LGRP2-OVS 9.1.0.358
LYA-L29-PRELOAD 9.0.0.16(C432R1)
LYA-L29-CUST 9.0.0.10(C432)

But it doesn't worked... Still the same red message on boot... My phone is bricked...

**Even worse, since this attempt, I can't use the Recovery OS function: after downloading and unpacking, HiSuite tells me: "Your device is not supported for system recovery"**. I reinstalled Hisuite 10, re-edited HiSuiteConfig.xml, nothing...

Here is my SystemUpdate last file. Big surprise, since I had my phone, I was on C432, but my CUST is in C431 and my Country is eea insted of eu... Really strange, because I bought my phone brand new on Amazon in Feb 2020.

[SystemUpdate_20210827_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7069743/SystemUpdate_20210827_00.log)

I cleared data (cache wiped, factory reset), then I tried different recoveries (EMUI 10 and 9.1, in C432, then in C431), but HiSuite continues to tell me that my phone isn't compatible with recovery.

I can access to Memory card/OTG update mode, USB update mode... (and fastboot).

**What do you think can I do about my phone? Do you think you can help me? If you succed, I swear that I'll donate you a bit of money because I think that it's important to have tools like FirmFinder and HiSuiteProxy to keep control on our devices**

PS: Sorry if my English isn't perfect, i'm from France ;)

Thank you in advance!

Jukuuuuu

**Comment by ProfessorJTJ** [comment]
Hey, so sad to hear that, the problem is your phone is half way on EMUI 9, you have the base and the preload packages rolled back but your CUST is still at EMUI 10, what method did you use to rollback from 10.0 to 9.1?

Unfortunately you cannot use Huawei's rescue mode to rollback your phone ( so if you install CUST 9.0 over your current 10.0 CUST it will not succeed and the issue will still remain )

*    FirmWare_Base:LYA-LGRP2-OVS 9.1.0.358
*    FirmWare_Cust:LYA-L29-CUST 10.0.0.8(C432)
*    FirmWare_Preload:LYA-L29-PRELOAD 9.0.0.16(C431R1)

If you could use HiSuite rescue mod use EMUI 10.0 packages, hopefully it will work....
LYA-LGRP2-OVS 10.0.0.154 : https://www.firmfinder.ml/327906
LYA-L29-PRELOAD 10.0.0.5(C432R1) : https://www.firmfinder.ml/330175
LYA-L29-CUST 10.0.0.7(C432) : https://www.firmfinder.ml/330182

HOWEVER "after downloading and unpacking, HiSuite tells me: "Your device is not supported for system recovery"" I guess that's because C431 rom is installed is installed on C432 phone, your phone is basically unauthorized for any rom installation, ticking the box "Force Auth Bridge" in HiSuite Proxy might be able to fix it, if not then you have to use paid services to revive your phone.

**Comment by Jukuuuuu** [comment]
Hi, yes I used the Update function of HiSuite to downgrade my Mate 20 Pro from 10.1 to 9.1, nothing special...

> If you could use HiSuite rescue mod use EMUI 10.0 packages, hopefully it will work....
> LYA-LGRP2-OVS 10.0.0.154 : https://www.firmfinder.ml/327906


LYA-LGRP2-OVS 10.0.0.154 is a C431 version, while preoload and cust files that you've suggested are in C432. 

Is it normal?

I'll give it a try if it's good!

Thank you for your help :)

**Comment by ProfessorJTJ** [comment]
> Hi, yes I used the Update function of HiSuite to downgrade my Mate 20 Pro from 10.1 to 9.1, nothing special...
> 
> > If you could use HiSuite rescue mod use EMUI 10.0 packages, hopefully it will work....
> > LYA-LGRP2-OVS 10.0.0.154 : https://www.firmfinder.ml/327906
> 
> LYA-LGRP2-OVS 10.0.0.154 is a C431 version, while preoload and cust files that you've suggested are in C432.
> 
> Is it normal?
> 
> I'll give it a try if it's good!
> 
> Thank you for your help :)

Yeah I double checked, C432 and C431 have the exact same base package

**Comment by Jukuuuuu** [comment]
Hi, I just tried to do a recovery tonight, with no success (after downloading and unpacking, same error)... I'll try to send my Mate 20 to an official technical center, my unit is covered by warranty until december, maybe, if I'm lucky, they can save it...

Thank you for your help, I'm rewarding you with some €uros :)

**Comment by ProfessorJTJ** [comment]
> Hi, I just tried to do a recovery tonight, with no success (after downloading and unpacking, same error)... I'll try to send my Mate 20 to an official technical center, my unit is covered by warranty until december, maybe, if I'm lucky, they can save it...
> 
> Thank you for your help, I'm rewarding you with some €uros :)

Thank you for your generosity, I hope you get it back soon. if you still have updating issues, I'd happily guide you on how to update it using HiSuite Proxy.

**Comment by PikuZheng** [comment]
Hi, There is a way to modify the underlying data to change the area. I suspect that your phone has been modified, so it cannot be upgraded.

**Comment by Jukuuuuu** [comment]
Hi, maybe you can help me then :)

**Comment by PikuZheng** [comment]
and what's more, you should reconnect usb cable after HiSuite confirmd your phone is in recovery mode, just before "Your device is not supported for system recovery"
That's a huage cheating and wast lots of my time...

**Comment by Jukuuuuu** [comment]
Ok, so I can try right now with these files?

LYA-LGRP2-OVS 10.0.0.154 : https://www.firmfinder.ml/327906
LYA-L29-PRELOAD 10.0.0.5(C432R1) : https://www.firmfinder.ml/330175
LYA-L29-CUST 10.0.0.7(C432) : https://www.firmfinder.ml/330182

Or do I need to modify theme before flashing them?

**Comment by PikuZheng** [comment]
I want to know whether your phone can be directly connected to wifi and upgrade through eRecovery (without hisuite)

**Comment by Jukuuuuu** [comment]
Yes, I have access to eRecovery. When connected to WiFi it tries to install a 10.0.1.100 version.

**Comment by Jukuuuuu** [comment]
So, have you got any idea with eRecovery, maybe by sharing my WiFI with a PC and a proxy, containing the correct files?

**Comment by PikuZheng** [comment]
> So, have you got any idea with eRecovery, maybe by sharing my WiFI with a PC and a proxy, containing the correct files?

yes. at the moment, I modified the system date to 2019/12/31 and downgrade my CTL-AL00 to 9.1.336 **without HISuite-Proxy**.

just overturned all my known news. Maybe that "fuse" is similar to a dated ssl certificate? I don't know. I'm trying downgrade to 9.0.0.187 with HISuite-Proxy

**Comment by Jukuuuuu** [comment]
In fact I already tried to recover my phone by using eRecovery, as I mentioned above, without success...
I've just sent my device to an official technical center to recover it. Because this was caused by HiSuite, maybe it'll be covered by the warranty.

**Comment by PikuZheng** [comment]
Sorry to hear that. but have you considered a hardware problem like CPU virtual soldering, NAND bad block, quite common...
