### ISSUE TITLE
(need help) downgrade always fail

### ISSUE THREAD

**Issue by PikuZheng** [ProfessorJTJ/HISuite-Proxy#93]
I'm trying downgrade from 10.0.0.134 to 9.1. 

everything looks fine except the phone can't verify pakage, just after transferring the upgrade package to the phone. (a red ! on phone's screen but HiSuite successed)

I have tried various configuration combinations and I wonder if there is a problem with authorize bridge.

And HiSuite_11.0.0.530_OVE \ Hisuite_10.1.0.550_OVE \ HiSuite_10.0.1.100_OVE have the same expression.

I also tried to check "old fimware" but the progress bar will stuck before installation (download finished).

There is no description about "point version" in the document, but no luck whether it is checked or not. Should I checked it?

Any suggestions are fine, thanks.

[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072395/logs.txt)
[SystemUpdate_20210829_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072398/SystemUpdate_20210829_00.log)
![剪贴板03](https://user-images.githubusercontent.com/12579522/131249718-6180677a-44be-4fb7-b675-bfc5619260ea.png)

**Comment by ProfessorJTJ** [comment]
Clean your systemupdate log, clean logs.txt file.

Don't tick Old firmware, don't tick authentication bridge

Tick Debug Logging, point version has no effect

Be sure os type is rollback, try again, if failed send the fresh logs

**Comment by PikuZheng** [comment]
![IMG_20210829_202546.jpg](https://user-images.githubusercontent.com/12579522/131255479-0f535d36-060b-42bf-950f-5b1eeb2b59f0.jpg)![IMG_20210829_202559.jpg](https://user-images.githubusercontent.com/12579522/131255482-c22eefe0-551d-42e2-ab55-5e98f8cb8eff.jpg)

**Comment by PikuZheng** [comment]
[SystemUpdate_20210829_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072762/SystemUpdate_20210829_00.log)
[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072763/logs.txt)

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210829_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072762/SystemUpdate_20210829_00.log)
> [logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072763/logs.txt)

From what I see everything is going correctly, what you can do though is, probably Huawei is blocking your rollback to 9.1 so first downgrade to the lowest possible 10.0 version for example if you're on 10.0.0.120 go to 10.0.0.100 or lower then try downgrading to 9.1

**Comment by PikuZheng** [comment]
> > [SystemUpdate_20210829_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072762/SystemUpdate_20210829_00.log)
> > [logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7072763/logs.txt)
> 
> From what I see everything is going correctly, what you can do though is, probably Huawei is blocking your rollback to 9.1 so first downgrade to the lowest possible 10.0 version for example if you're on 10.0.0.120 go to 10.0.0.100 or lower then try downgrading to 9.1

yes it is already downgraded to the oldest version of 10.0   T_T

**Comment by PikuZheng** [comment]
After some dig, we found that it always fails when using HISuite-Proxy across major versions, include 9.1.x to 10.0.x, and 10.0.x to 9.1.x, and 9.1.x to 9.0.x.
The phenomenon is everything looks correct but package verify failed on the phone.
I think something is different while HiSuite try to connect to query.hicloud.com and get some authorize code, when using or not using Proxy.
May @ProfessorJTJ please investigate this issue a little bit?

**Comment by ProfessorJTJ** [comment]
> After some dig, we found that it always fails when using HISuite-Proxy across major versions, include 9.1.x to 10.0.x, and 10.0.x to 9.1.x, and 9.1.x to 9.0.x.
> The phenomenon is everything looks correct but package verify failed on the phone.
> I think something is different while HiSuite try to connect to query.hicloud.com and get some authorize code, when using or not using Proxy.
> May @ProfessorJTJ please investigate this issue a little bit?

Try installing 10.0 on 9.1 using hisuite proxy, while having "Debug Logging" box ticked, then share the logs.txt file here along with Systemupdate.log

I'll also do a small change on hisuite proxy and send you a new program to test...

**Comment by PikuZheng** [comment]
[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7105965/logs.txt)
[SystemUpdate_20210903_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7105966/SystemUpdate_20210903_00.log)

**Comment by ProfessorJTJ** [comment]
> [logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7105965/logs.txt)
> [SystemUpdate_20210903_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7105966/SystemUpdate_20210903_00.log)

Ok now, clean the Systemupdate.log file, do update to emui 10 without using hisuite proxy, after downloading finishes and "installing" starts, cancel it and send the Systemupdate.log to me

**Comment by PikuZheng** [comment]
[SystemUpdate_20210903_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7106796/SystemUpdate_20210903_00.log)

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210903_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7106796/SystemUpdate_20210903_00.log)

So you are not using the same packages as official hisuite, try the following packages to go to emui 10.0 with Hisuite, it will most likely succeed.

https://www.firmfinder.ml/363340 CLT-LGRP1-CHN 10.0.0.156

https://www.firmfinder.ml/363341 CLT-AL00-CUST 10.0.0.156(C00)

https://www.firmfinder.ml/346819 CLT-AL00-PRELOAD 10.0.0.4(C00R1)

**Comment by PikuZheng** [comment]
Here is downgrade log with HiSuite-Proxy (downgrade failed):
[logs.txt](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7108930/logs.txt)
[SystemUpdate_20210904_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7108929/SystemUpdate_20210904_00.log)
config:
![剪贴板03](https://user-images.githubusercontent.com/12579522/132075660-e2f8ca61-3d9b-4dbf-b00a-3c49dc65dd47.png)
Without Hisuite-Proxy here:
[SystemUpdate_20210904_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7108938/SystemUpdate_20210904_00.log)

**Comment by jennifer364** [comment]
Hi, My phone is huawei P40 pro, I'm trying downgrade EMUI 11 to EMUI 10 but when I do it by Hisuite 11 & Hisuite proxy 10 its not running, as file, Is there any way to solve this problem
![Uploading IMG_20210928_100004_edit_76213081624305.jpg…]()

**Comment by ProfessorJTJ** [comment]
> Hi, My phone is huawei P40 pro, I'm trying downgrade EMUI 11 to EMUI 10 but when I do it by Hisuite 11 & Hisuite proxy 10 its not running, as file, Is there any way to solve this problem

Hi, the picture is not uploaded properly

Try with Hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by Loggsie** [comment]
> After some dig, we found that it always fails when using HISuite-Proxy across major versions, include 9.1.x to 10.0.x, and 10.0.x to 9.1.x, and 9.1.x to 9.0.x. The phenomenon is everything looks correct but package verify failed on the phone. I think something is different while HiSuite try to connect to query.hicloud.com and get some authorize code, when using or not using Proxy. May @ProfessorJTJ please investigate this issue a little bit?

BASE has to be downgraded in sequence or else the ROM verification will fail upon reboot.

Follow this I posted earlier https://github.com/ProfessorJTJ/HISuite-Proxy/issues/127
