### ISSUE TITLE
P40 Pro ELS-N29 Proxy patch proble

### ISSUE THREAD

**Issue by LazarP40pro** [ProfessorJTJ/HISuite-Proxy#95]
![Screenshot_1](https://user-images.githubusercontent.com/89745221/131260571-719b65bc-fe82-4442-af72-1a765ae534ca.png)

I have a problem when i want to downgrade software on my P40 Pro from emui 11 to emui 10
ELS-N29 - C432 | ELS-LGRP4-OVS 10.1.0.131
ELS-N29 - C432 | ELS-N29-CUST 10.1.0.8(C432)
ELS-N29 - C432 | ELS-N29-PRELOAD 10.1.0.2(C432R5)

**Comment by ProfessorJTJ** [comment]
Install HiSuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
