### ISSUE TITLE
Hi! How to use Offline packages?

### ISSUE THREAD

**Issue by witersen** [ProfessorJTJ/HISuite-Proxy#96]
Hello, how to use the offline packages function? I have downloaded the base package, cust package and preload package of the target system. Now these zip files are on my computer. How can I use the offline packages function of the software to load these files

**Comment by ProfessorJTJ** [comment]
"Documents/HiSuite/Rom" place them there in their respective folders. you need to add the firmwares properly to HiSuite Proxy first. their url, name and id.

**Comment by witersen** [comment]
Thank you for your reply! My mobile phone is mate20pro (LYA-AL00), I can't get the firmware from https://www.firmfinder.ml/  with version 9.0.0.107, so even though I already have base package, cust package and preload package locally(All from the official), I don't have URL and ID. is there any solution?

**Comment by ProfessorJTJ** [comment]
> LYA-AL00

Open the packages' zip file, you will see a file there named "Version" I need that file's content.... copy and paste the exact version of the 3 of them.

**Comment by witersen** [comment]
-update_sd_base.zip
	-META-INF(floder)
	-full_mainpkg.tag
	-PTABLE.APP
	-ptable.img
	-SD_update.tag
	-sec_xloader_header
	-SOFTWARE_VER_LIST.mbn
	-UPDATE.APP
	-UPT_VER.tag
  
--------SOFTWARE_VER_LIST.mbn-content-start--------
HMA 9.0.0(CHN)
LYA 9.0.0(CHN)
LYA-LGRP1-CHN 9.0.0.46
LYA-LGRP1-CHN 9.0.0.102
LYA-LGRP1-CHN 9.0.0.103
LYA-LGRP1-CHN 9.0.0.106
LYA-LGRP1-CHN 9.0.0.107
--------SOFTWARE_VER_LIST.mbn-content-end--------


-update_sd_cust_LYA-AL00_all_cn.zip
	-META-INF(floder)
	-full_mainpkg.tag
	-PKG_TYPE.tag
	-PTABLE.APP
	-PTABLE_CUST.mbn
	-SD_update.tag
	-SOFTWARE_VER_LIST.mbn
	-UPDATE.APP
	-UPT_VER.tag
  
--------SOFTWARE_VER_LIST.mbn-content-start--------
HMA-AL00-CUST 9.0.0(C00)
LYA-AL00-CUST 9.0.0(C00)
LYAAL00B000
LYA-AL00-CUST 9.0.0.102(C00)
LYA-AL00-CUST 9.0.0.103(C00)
--------SOFTWARE_VER_LIST.mbn-content-end--------


-update_sd_cust_LYA-AL00_all_cn.zip
	-META-INF(floder)
	-full_mainpkg.tag
	-PKG_TYPE.tag
	-PTABLE.APP
	-PTABLE_PRELOAD.mbn
	-SD_update.tag
	-SOFTWARE_VER_LIST.mbn
	-UPDATE.APP
	-UPT_VER.tag
  
--------SOFTWARE_VER_LIST.mbn-content-start--------
LYA-AL00-PRELOAD 9.0.0(C00R1)
--------SOFTWARE_VER_LIST.mbn-content-end--------

**Comment by ProfessorJTJ** [comment]
"update_sd_base.zip"

Apparently you're trying to install a dload package using HiSuite Proxy, unforunately you're out of luck, HiSuite uses online packages not dload ones.

**Comment by witersen** [comment]
get it , still thanks!
