### ISSUE TITLE
'No internet Connection' at 99%

### ISSUE THREAD

**Issue by MrSquiffy** [ProfessorJTJ/HISuite-Proxy#97]
Hi there

I've been trying to downgrade my P40, but every time I get to downloading the files, at 99% I get the 'No Internet Connection' error.

I am using the correct version of HiSuite (10.0.1.100_OVE). Firewall and antivirus have been turned off, ROMs have been sourced from firmfinder.ml . 

I've attached multiple pictures which hopefully illustrate the problem, and I believe I've got all settings correct. How do I go about fixing this?

Cheers!
![correct version install](https://user-images.githubusercontent.com/83025281/132004994-e6114ed7-e3de-4b91-8170-724f7d73fabb.png)
![HiProxy Settings](https://user-images.githubusercontent.com/83025281/132005013-d677ba75-2a38-4db2-9842-f7d3005db922.png)
![99percent and correct HiSuit Version](https://user-images.githubusercontent.com/83025281/132005031-7c218300-8f1f-48ea-9b72-269ab3b0aefa.png)
![No internet connection](https://user-images.githubusercontent.com/83025281/132005048-328f7cde-8680-46e5-826f-650c9e751916.png)

**Comment by ProfessorJTJ** [comment]
If you're on emui 11, use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by MrSquiffy** [comment]
Hi there, I've tried using the version you linked, but unfortunately it still isn't working. You can see in the attached picture I'm using this version. Is there any incompatibility caused by the latest EMUI update? (currently on 11.0.0.202)

Additionally, am I right in assuming that I still use the regular HiSuite.exe? The set-up log doesn't show a separate exe file being made (when I tried to use the current version, it created a new HiSuite 11.exe file)
![10 1 0 5 hisuite-notworking](https://user-images.githubusercontent.com/83025281/132010321-67ef1fa3-db7a-490a-bf12-2acc91f9bba9.png)

**Comment by ProfessorJTJ** [comment]
> Hi there, I've tried using the version you linked, but unfortunately it still isn't working. You can see in the attached picture I'm using this version. Is there any incompatibility caused by the latest EMUI update? (currently on 11.0.0.202)
> 
> Additionally, am I right in assuming that I still use the regular HiSuite.exe? The set-up log doesn't show a separate exe file being made (when I tried to use the current version, it created a new HiSuite 11.exe file)
> ![10 1 0 5 hisuite-notworking](https://user-images.githubusercontent.com/83025281/132010321-67ef1fa3-db7a-490a-bf12-2acc91f9bba9.png)

Post your Systemupdate.log log file, it can be found at
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

Meanwhile, tick the box "Force Auth Bridge" and try again.

**Comment by barymuffinz** [comment]
Hi guys,
i just resolve this problem after use this version of hisuite https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3/HiSuite_11.0.0.510_OVE.rar and i just saw you used another file at PRELOAD than me.

attached ss
![Bez tytułu](https://user-images.githubusercontent.com/90057559/132035003-34b4ac83-9c70-48d4-82de-f69120906128.png)

**Comment by barymuffinz** [comment]
> > Hi there, I've tried using the version you linked, but unfortunately it still isn't working. You can see in the attached picture I'm using this version. Is there any incompatibility caused by the latest EMUI update? (currently on 11.0.0.202)
> > Additionally, am I right in assuming that I still use the regular HiSuite.exe? The set-up log doesn't show a separate exe file being made (when I tried to use the current version, it created a new HiSuite 11.exe file)
> > ![10 1 0 5 hisuite-notworking](https://user-images.githubusercontent.com/83025281/132010321-67ef1fa3-db7a-490a-bf12-2acc91f9bba9.png)
> 
> Post your Systemupdate.log log file, it can be found at
> C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log
> 
> Meanwhile, tick the box "Force Auth Bridge" and try again.

Just i wanted to extract all files to install google store, but i cannot connect with hdb. I was checking few solutions but everyone does not work.. Do you have any idea?

**Comment by MrSquiffy** [comment]
Hi there, I've tried using it with Force Auth Bridge, and it still hasn't worked. I've provided logs for both attempts.

That said, i checked the log file for the proxy, and I was able to download the update_full_base.zip file. Is there any way I can use this with the offline settings on HiProxy to do the downgrade?
[SystemUpdate_20210904_00_NoAuthBridge.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7110020/SystemUpdate_20210904_00_NoAuthBridge.log)
[SystemUpdate_20210904_00_AuthBridge.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7110021/SystemUpdate_20210904_00_AuthBridge.log)
![update file](https://user-images.githubusercontent.com/83025281/132098758-263a944f-a203-43e3-a591-ab9485240006.png)


Thank you very much. I appreciate the help you're lending to get this working for me

**Comment by ProfessorJTJ** [comment]
> Hi there, I've tried using it with Force Auth Bridge, and it still hasn't worked. I've provided logs for both attempts.
> 
> That said, i checked the log file for the proxy, and I was able to download the update_full_base.zip file. Is there any way I can use this with the offline settings on HiProxy to do the downgrade?
> [SystemUpdate_20210904_00_NoAuthBridge.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7110020/SystemUpdate_20210904_00_NoAuthBridge.log)
> [SystemUpdate_20210904_00_AuthBridge.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7110021/SystemUpdate_20210904_00_AuthBridge.log)
> ![update file](https://user-images.githubusercontent.com/83025281/132098758-263a944f-a203-43e3-a591-ab9485240006.png)
> 
> Thank you very much. I appreciate the help you're lending to get this working for me

I thought the problem is with the authorization, apparently it's not, from the log my assumption is one of the packages is corrupted, according to the log:

"[2021-09-04 15:38:36:769][L2_VIM][sn=28][RESULT: TRUE][HiSuite_SystemUpdate][[[DATA1: sha256 not match.[tid=1788]]]]"

Try using other 3 package combination, other base, and preload, keep the Cust as it is, see if the same error is going to be in the log

**Comment by MrSquiffy** [comment]
Hi there, I've tried using other files other than the preload (as there is only one with R5). Is there any problem if I use a Preload with a different R number?
![huawei info](https://user-images.githubusercontent.com/83025281/132103442-c5fefdd3-818c-4118-a857-7a8aabf8afff.jpg)

**Comment by ProfessorJTJ** [comment]
> Hi there, I've tried using other files other than the preload (as there is only one with R5). Is there any problem if I use a Preload with a different R number?
> ![huawei info](https://user-images.githubusercontent.com/83025281/132103442-c5fefdd3-818c-4118-a857-7a8aabf8afff.jpg)

It's supposed to be fine, you wouldn't encounter any problems.

**Comment by nnzz86** [comment]
![Untitled](https://user-images.githubusercontent.com/90571517/133074563-ffd56ae8-0831-4d67-8dbb-d8f7c279b90c.jpg)
plz help
emui 11.0.0.198 to emui 10.1

**Comment by ProfessorJTJ** [comment]
> ![Untitled](https://user-images.githubusercontent.com/90571517/133074563-ffd56ae8-0831-4d67-8dbb-d8f7c279b90c.jpg)
> plz help
> emui 11.0.0.198 to emui 10.1

Use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

By the way you will lose your usb connection.

**Comment by nnzz86** [comment]
I've tried using the version you linked, but unfortunately it still isn't working

**Comment by ProfessorJTJ** [comment]
> I've tried using the version you linked, but unfortunately it still isn't working

Tick the box force Auth Bridge and send the log file

C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by nnzz86** [comment]
[SystemUpdate_20210913_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7154391/SystemUpdate_20210913_00.log)

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210913_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7154391/SystemUpdate_20210913_00.log)

You have mentioned your problem in the wrong issue.
HiSuite doesn't start downloading at all right?

Click on "setup" in HiSuite proxy, does it show any errors there or completes successfully?

**Comment by nnzz86** [comment]
yup.. setup complete successfull

**Comment by ProfessorJTJ** [comment]
> yup.. setup complete successfull

This is weird, first time happening :/

**Comment by nnzz86** [comment]
sir.. help me in teamviwer

**Comment by nnzz86** [comment]
![Untitled](https://user-images.githubusercontent.com/90571517/133466400-30d1d276-cdbc-444a-83e5-0e1176d94670.jpg)
problem solve after format my pc
