### ISSUE TITLE
where is the problem?

### ISSUE THREAD

**Issue by ortoptist** [ProfessorJTJ/HISuite-Proxy#98]
![2021-09-05_21-29-37](https://user-images.githubusercontent.com/90153406/132137678-e204b0bd-9c4f-4fcb-8284-fcdce88b4201.png)

**Comment by ortoptist** [comment]
allow
HiSuite_11.0.0.550_OVE -->HiSuite_11.0.0.510_OVE

**Comment by ProfessorJTJ** [comment]
Or you can use hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip
