### ISSUE TITLE
Can we convert Firmware regions 

### ISSUE THREAD

**Issue by salukanipun** [ProfessorJTJ/HISuite-Proxy#99]
I'm currently using  Mate 30 pro  4g  C636  Asia Pacific region. Can I convert my  device to  China C00

**Comment by ProfessorJTJ** [comment]
Hisuite proxy cannot do that, you might be able to install another global firmware like C432 but not Chinese firmware on your global phone.

You can re-brand your phone using paid tools like dc phoneix.

**Comment by salukanipun** [comment]
Thanks For the advice  ,  Just wanted to update harmony os by changing regions to  China.

**Comment by ProfessorJTJ** [comment]
> Thanks For the advice , Just wanted to update harmony os by changing regions to China. Is There any possibility of installing harmony os ?

Just by using paid tools... You can get someone to do it for you, like this guy
https://ministryofsolutions.com
